<a href="https://colab.research.google.com/github/zolocapricorn/Senior_Project/blob/main/Preparing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Github Zone**

### Cloning git and basic set up

In [1]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/

In [2]:
!git clone https://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@github.com/zolocapricorn/Senior_Project.git

Cloning into 'Senior_Project'...
remote: Enumerating objects: 284, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (68/68), done.
Receiving objects: 100% (284/284), 95.26 MiB | 20.64 MiB/s, done.
remote: Total 284 (delta 66), reused 63 (delta 32), pack-reused 184
Resolving deltas: 100% (140/140), done.

In [152]:
%cd /content/Senior_Project/cleaned_dataset

/content/Senior_Project/cleaned_dataset

In [4]:
! git config --global user.email "suijuku@outlook.com"
! git config --global user.name "zolocapricorn"

In [5]:
!git remote -v

origin	https://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@github.com/zolocapricorn/Senior_Project.git (fetch)
origin	https://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@github.com/zolocapricorn/Senior_Project.git (push)

In [ ]:
!git log

commit 61ec5424fa27100bbb3be0cb5b2caff0dab1636b (HEAD -> main, origin/main, origin/HEAD)
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 10:34:40 2024 +0000

    Update cleaned_title_after_check_condition.pkl file.

commit e663293976b7a4b8cf4b8c43570ee56eae8ad462
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 10:31:25 2024 +0000

    Update cleaned_raw_title_after_check_condition.pkl file.

commit bf5ae99c49e4b002aa16ae1244ab628fa2333b12
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 10:30:31 2024 +0000

    Update cleaned_raw_title.pkl file.

commit 8b3ea05e7aacc9d78e8dfc0ecdb772f93c97a1b7
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 10:24:11 2024 +0000

    Update cleaned_imdb_after_check_condition.pkl file.

commit e47201ccc1b2db4fda5e6718f3541305ed36c4ab
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 10:22:28 2024 +0000

    Update cleaned_imdb.pkl file.

commit c5e3db9c33e44aee26decbcae136ad24ca92eb8c
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 10:09:45 2024 +0000

    Upload raw dataset.

commit dd45e03d415d5ca869d57aa0aba321ea85959029
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 09:55:32 2024 +0000

    Upload raw dataset.

commit 3564ef5021579223d9d5b6ea150554fec8db63c1
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Feb 16 16:19:27 2024 +0700

    Delete Number_Instead/csv directory

commit 91bde49441bdc5e2dde228b6e2817e3cf042e898
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Feb 16 09:14:54 2024 +0000

    Update pkl file in Number_Instead folder.

commit 145867d9a5890e46c487054d07ba570b80f01785
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Feb 16 16:00:20 2024 +0700

    Update and rename actor_cleaning.csv to actor_cleaning.csv

commit 4595f868068265443418ea0d7d8b69de7ee435e7
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Feb 16 15:21:25 2024 +0700

    Delete raw_dataset directory

commit 2dd1b2bbf6c48daa864d51b9eef7ecedd0da713d
Author: zolocapricorn <suijuku@outlook.com>
Date:   Thu Feb 15 17:27:55 2024 +0700

    Update git attributes.

commit 7027601a7cc6e32c65cccff66a2ba8cb8ceba3b0
Author: zolocapricorn <suijuku@outlook.com>
Date:   Thu Feb 15 09:35:50 2024 +0000

    Update git attribute.

commit b72c77693a8365b89b80052ad2bba71e4bfe115d
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Thu Feb 15 12:19:55 2024 +0700

    Delete Number_Instead/read

commit 47d62b1b5261af8f22074e56ffcca7f1b6cd3c37
Author: zolocapricorn <suijuku@outlook.com>
Date:   Thu Feb 15 12:18:17 2024 +0700

    Add csv file for cleaning.

commit 514a3ce44d41e15cf0bea229aa9445229e3a3163
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Thu Feb 15 11:58:25 2024 +0700

    Create read

commit a307d9a2b688e7b1734012a7658256f7bdc4b343
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Wed Feb 14 17:54:21 2024 +0700

    Delete Number_Instead directory

commit ba976865fe3552eec4d88966cf66a87b58fe26fa
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Wed Feb 14 17:53:23 2024 +0700

    Create read

commit 738fddec08085a8ff4dd65af3acd26eebd9c5a21
Author: zolocapricorn <suijuku@outlook.com>
Date:   Sun Jan 28 09:24:22 2024 +0000

    Update dataset.

commit a613e413da85f1d60470b23b678208c93b749373
Author: zolocapricorn <suijuku@outlook.com>
Date:   Tue Dec 26 09:32:03 2023 +0000

    Update condition

commit d45f37d21aeb96e4104a23a4d1348cc4502564d6
Author: zolocapricorn <suijuku@outlook.com>
Date:   Tue Dec 26 09:30:10 2023 +0000

    Delete condition

commit 74eea07233b323b339c17959d15282e37c79039d
Author: zolocapricorn <suijuku@outlook.com>
Date:   Tue Dec 26 09:27:03 2023 +0000

    Delete condition

commit 8aa3453a14a22473d8c2b2b240bb2b97447a72b9
Author: zolocapricorn <suijuku@outlook.com>
Date:   Tue Dec 26 09:08:29 2023 +0000

    Upload condition

commit d709913e990ebcd4635a0712dd1f282858489008
Author: zolocapricorn <suijuku@outlook.com>
Date:   Tue Dec 26 09:02:57 2023 +0000

    Upload condition

commit ef9f173949627d71afb827340c574960f375efab
Author: zolocapricorn <suijuku@outlook.com>
Date:   Tue Dec 26 08:22:59 2023 +0000

    Upload cleaned dataset

commit 7d898aa5859b188eeeb8bc578905af6e16914b51
Author: zolocapricorn <suijuku@outlook.com>
Date:   Mon Dec 25 08:33:01 2023 +0000

    Upload cleaned dataset

commit f77a49741df86902ea173adb1eba3417e25a2dc5
Author: zolocapricorn <suijuku@outlook.com>
Date:   Mon Dec 25 08:29:41 2023 +0000

    Upload cleaned dataset

commit 4440ef45a1864824e14eb573e451b74ff02c4f94
Author: zolocapricorn <suijuku@outlook.com>
Date:   Mon Dec 25 08:29:10 2023 +0000

    Delete cleaned dataset

commit 6741b48b65dc7b0b993150c4c2aa78e7cf30f708
Author: zolocapricorn <suijuku@outlook.com>
Date:   Mon Dec 25 08:28:02 2023 +0000

    Delete cleaned dataset

commit acd5a1d67a0957d45e0fd23aea586be7a2ab5491
Author: zolocapricorn <suijuku@outlook.com>
Date:   Mon Dec 25 08:24:06 2023 +0000

    Delete cleaned dataset

commit 2cb3303a936ca34b9c3c0eac783885112b271298
Author: zolocapricorn <suijuku@outlook.com>
Date:   Mon Dec 25 07:59:02 2023 +0000

    Upload cleaned dataset

commit 2fbaa0fbc15063c18bc94ba7c113c9cca1fba5ad
Author: zolocapricorn <suijuku@outlook.com>
Date:   Mon Dec 25 06:24:17 2023 +0000

    Upload cleaned dataset

commit 7912d27e1e6e775c50de671f0063166d33e6e5a2
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 11:48:50 2023 +0000

    Create cleaned dataset

commit 11f8edf68fa510b2619340f566e95ae35b76bd27
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 11:26:37 2023 +0000

    Upload raw dataset

commit 2700a2d27096b29cd9eab9182bc072121b858b69
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 11:24:47 2023 +0000

    Add csv file

commit 9e6ee75670eea7603be4446c71fd4f34476b5318
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 11:03:09 2023 +0000

    Add design file

commit 331bf7d3af8cfcce3aad9bd501fa5277c8cea3cc
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Dec 22 17:41:55 2023 +0700

    Delete Netflix_Dataset_Movie.csv

commit dc46f2710a2400f6462afeebb0e55ff12fc5be28
Merge: 42e0b92 2797c3f
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 10:38:25 2023 +0000

    merge branch

commit 42e0b926fe6d3f1e1e6104c1e56826d3e6ed0ccd
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 10:31:21 2023 +0000

    test to upload file

commit 2797c3f4e8eca1d55c0edfebf3e786acdc63c104
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Dec 22 17:29:41 2023 +0700

    Delete new.md

commit ceef617e0d4a838a7ae30b704d68284320b10bec
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 10:28:36 2023 +0000

    test to upload file

commit 9662e6994f63123ae6ddc0da4b9ad2d527d09e62
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Dec 22 16:27:35 2023 +0700

    Create dataset.md

commit dc7d49d77e39652de8b2d7a5dadecf15a6a8d079
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Dec 22 16:26:57 2023 +0700

    Delete raw_dataset/gg

commit 669deb7c198c6acba0455b568e0c5926a1bec80c
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Dec 22 16:26:19 2023 +0700

    Create raw_dataset

commit 729e61b73c3864b94da03db338e0009674db9e3a
Author: Kamolchanok Sinraksa <77113968+zolocapricorn@users.noreply.github.com>
Date:   Fri Dec 22 15:49:51 2023 +0700

    สร้างโดยใช้ Colaboratory

commit da4523e619b08e1f348f0818368c84d3dd33bca3
Author: zolocapricorn <suijuku@outlook.com>
Date:   Fri Dec 22 15:48:42 2023 +0700

    first commit

## Usage git

In [ ]:
!git push --force origin b72c77693a8365b89b80052ad2bba71e4bfe115d:main

Everything up-to-date

In [6]:
!git fetch

In [7]:
!git pull https://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@github.com/zolocapricorn/Senior_Project.git

From https://github.com/zolocapricorn/Senior_Project
 * branch            HEAD       -> FETCH_HEAD
Already up to date.

In [174]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [173]:
!git add entertainment_media_dataset.pkl
!git commit -m "Update entertainment_media_dataset.pkl file."
!git push

[main 84464a8] Update entertainment_media_dataset.pkl file.
 1 file changed, 0 insertions(+), 0 deletions(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 111.77 KiB | 381.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/zolocapricorn/Senior_Project.git
   8ac9c2e..84464a8  main -> main

In [ ]:
!git config http.postBuffer 524288000

fatal: not in a git directory

In [ ]:
!git reset --hard HEAD~1

HEAD is now at 5779eb6 Update Netflix_Dataset_Rating.pkl file.

# **Installer Zone**

In [ ]:
!pip install faker

Collecting faker
  Downloading Faker-21.0.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 14.2 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.16.0)
Installing collected packages: faker
Successfully installed faker-21.0.0

In [ ]:
!pip install spacy-langdetect

Collecting spacy-langdetect
  Downloading spacy_langdetect-0.1.2-py3-none-any.whl (5.0 kB)
Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (from spacy-langdetect) (7.4.3)
Collecting langdetect==1.0.7 (from spacy-langdetect)
  Downloading langdetect-1.0.7.zip (998 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 998.1/998.1 kB 13.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect==1.0.7->spacy-langdetect) (1.16.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest->spacy-langdetect) (2.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest->spacy-langdetect) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest->spacy-langdetect) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest->spacy-langdetect) (1.2.0)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pytest->spacy-langdetect) (2.0.1)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.7-py3-none-any.whl size=993413 sha256=e678753fe64308ac2c76e0bbbc909279746ba1e38b71fdb732ff620f50eb723f
  Stored in directory: /root/.cache/pip/wheels/97/f1/e4/8b73f7a0421b132755956892d29b1e764d3e0857a6e92e32fe
Successfully built langdetect
Installing collected packages: langdetect, spacy-langdetect
Successfully installed langdetect-1.0.7 spacy-langdetect-0.1.2

In [ ]:
!python -m spacy download en

2023-12-26 07:55:04.028929: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-26 07:55:04.028988: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-26 07:55:04.031094: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-26 07:55:04.047732: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-26 07:55:06.656429: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the
full pipeline package name 'en_core_web_sm' instead.
Collecting en-core-web-sm==3.6.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 53.8 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.7.0,>=3.6.0 in /usr/local/lib/python3.10/dist-packages (from en-core-web-sm==3.6.0) (3.6.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (3.0.9)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (8.1.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (2.0.10)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (0.9.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (0.10.3)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (4.66.1)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (1.23.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (1.10.13)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (23.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (2023.11.17)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (0.1.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.7.0,>=3.6.0->en-core-web-sm==3.6.0) (2.1.3)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [ ]:
!pip install blosc

Collecting blosc
  Downloading blosc-1.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 11.8 MB/s eta 0:00:00
Installing collected packages: blosc
Successfully installed blosc-1.11.1

# **Library Zone**

In [9]:
import numpy as np
import pandas as pd
# from faker import Faker
from tqdm import tqdm
import random
import re
# from spacy_langdetect import LanguageDetector
# import spacy
# from spacy.language import Language

In [ ]:
def get_lang_detector(nlp, name):
  return LanguageDetector()


nlp = spacy.load("en_core_web_sm")
Language.factory("language_detector", func=get_lang_detector)
nlp.add_pipe('language_detector', last=True)

# **Dictionary Zone**

In [10]:
country_dict = {'US':'United States', 'BY':'Belarus', 'SK':'Slovakia', 'KG':'Kyrgyzstan', 'MZ':'Mozambique',
                'GB':'United Kingdom', 'EG':'Egypt', 'DE':'Germany', 'IN':'India', 'SU':'Soviet Union',
                'LB':'Lebanon', 'CA':'Canada', 'FR':'France', 'DZ':'Algeria', 'IT':'Italy','JP':'Japan',
                'AR':'Argentina', 'PE':'Peru', 'BR':'Brazil', 'IE':'Ireland', 'HK':'Hong Kong', 'AU':'Australia',
                'GH':'Ghana','BF':'Burkina Faso', 'MX':'Mexico', 'ES':'Spain','PS':'Palestine','NO':'Norway',
                'BE':'Belgium', 'DK':'Denmark', 'BS':'Bahamas', 'CZ':'Czech Republic', 'MT':'Malta',
                'ZA':'South Africa', 'CN':'China', 'RU':'Russia', 'KR':'Korea', 'CO':'Colombia', 'CL':'Chile',
                'MA':'Morocco', 'UY':'Uruguay', 'TR':'Turkey', 'NL':'Netherlands', 'SE':'Sweden', 'TW':'Taiwan',
                'NG':'Nigeria', 'MY':'Malaysia','CH':'Switzerland', 'PH':'Philippines', 'KW':'Kuwait',
                'AT':'Austria', 'AE':'United Arab Emirates', 'HU':'Hungary', 'XX':'stateless', 'ID':'Indonesia',
                'SA':'Saudi Arabia', 'SG':'Singapore', 'FI':'Finland', 'IL':'Israel', 'CD':'Congo', 'PL':'Poland',
                'VE':'Venezuela', 'RO':'Romania', 'IS':'Iceland', 'UA':'Ukraine', 'NZ':'New Zealand',
                'LU':'Luxembourg', 'BG':'Bulgaria', 'IR':'Iran', 'JO':'Jordan','QA':'Qatar', 'HR':'Croatia',
                'TN':'Tunisia', 'GL':'Greenland', 'PT':'Portugal', 'PK':'Pakistan', 'VN':'Vietnam',
                'PR':'Puerto Rico', 'IQ':'Iraq', 'TH':'Thailand', 'GE':'Georgia', 'KH':'Cambodia', 'CU':'Cuba',
                'VA':'Vatican', 'SY':'Syria', 'RS':'Serbia', 'TZ':'Tanzania', 'AL':'Albania', 'PY':'Paraguay',
                'ZW':'Zimbabwe', 'NP':'Nepal', 'CM':'Cameroon', 'BD':'Bangladesh', 'BT':'Bhutan', 'LT':'Lithuania',
                'MC':'Monaco', 'MW':'Malawi', 'CY':'Cyprus', 'SN':'Senegal', 'LK':'Sri Lanka', 'MU':'Mauritius',
                'IO':'British Indian Ocean Territory', 'GT':'Guatemala', 'AO':'Angola', 'GR':'Greece',
                'KN':'Saint Kitts and Nevis', 'KE':'Kenya', 'FO':'Faroe Islands', 'NA':'Namibia', 'AF':'Afghanistan',
                "korea": "south korea", "stateless": ""}

type_dict = {'tv movie': 'movie', 'tv series': 'show', 'episode': 'show',
             'tv mini series': 'show', 'video movie': 'movie',
             "tv short": "show", "series": "show"}

genre_dict = {"scifi": "sci-fi", "documentary": "documentation"}

language_dict = {"none": "none language", "old": "old language"}

cleaning_dict = str.maketrans({"[": "", "]": "", "'": "", "(": "", ")": ""})

#**Processing Zone**

##Calling Data

### Node Data

In [ ]:
# Actor Node Data
!gdown --id 10noKzT2u7fxH9P0qbrWlwae_vRI7qPEL

# Age Certification Node Data
!gdown --id 16XR-Lm9Z_Brghf215aYIpKxvTeofxsXN

# Character Node Data
!gdown --id 1ja4uUJ79zuxl78dZpG6PLy2xSOI1kFTO

# Director Node Data
!gdown --id 17lVFj7OGo1lPoSfD41KuttUwRWZt9dvZ

# Entertainment Node Data
!gdown --id 1Im9X0ilQnh69jwLNYnI0nsw4KdsJItHX

# Genre Node Data
!gdown --id 1xJZYoVPM8VbpTt-uCHYMOm1nXylw4YA5

# Language Node Data
!gdown --id 187kkXftQt1NeWAaI5tWGfBFcLp08S3yf

# Production Country Node Data
!gdown --id 1mydgUG6PwbGE6E27blWJA4F6YpvNEiYE

# Release Year Node Data
!gdown --id 1Ast-AR8wU5Vb5YTvaLygli1H-ZIXfgg0

# Type Node Data
!gdown --id 1uTM7Rd8jBbTOpVp8POiQmgwskBXBhwtS

# User Node Data
!gdown --id 1VQLAwv4YppZFb7eoC4lNehqVC_mFcMvO

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=10noKzT2u7fxH9P0qbrWlwae_vRI7qPEL
To: /content/node_actor.csv
100% 5.18M/5.18M [00:00<00:00, 156MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=16XR-Lm9Z_Brghf215aYIpKxvTeofxsXN
To: /content/node_age_certification.csv
100% 156/156 [00:00<00:00, 531kB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1ja4uUJ79zuxl78dZpG6PLy2xSOI1kFTO
To: /content/node_character.csv
100% 1.83M/1.83M [00:00<00:00, 167MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=17lVFj7OGo1lPoSfD41KuttUwRWZt9dvZ
To: /content/node_director.csv
100% 201k/201k [00:00<00:00, 90.3MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1Im9X0ilQnh69jwLNYnI0nsw4KdsJItHX
To: /content/node_entertainment_media.csv
100% 1.99M/1.99M [00:00<00:00, 198MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1xJZYoVPM8VbpTt-uCHYMOm1nXylw4YA5
To: /content/node_genre.csv
100% 492/492 [00:00<00:00, 2.56MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=187kkXftQt1NeWAaI5tWGfBFcLp08S3yf
To: /content/node_language.csv
100% 2.92k/2.92k [00:00<00:00, 15.3MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1mydgUG6PwbGE6E27blWJA4F6YpvNEiYE
To: /content/node_production_country.csv
100% 2.99k/2.99k [00:00<00:00, 16.5MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1Ast-AR8wU5Vb5YTvaLygli1H-ZIXfgg0
To: /content/node_release_year.csv
100% 1.76k/1.76k [00:00<00:00, 11.0MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1uTM7Rd8jBbTOpVp8POiQmgwskBXBhwtS
To: /content/node_type.csv
100% 90.0/90.0 [00:00<00:00, 300kB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1VQLAwv4YppZFb7eoC4lNehqVC_mFcMvO
To: /content/node_user.csv
100% 9.39M/9.39M [00:00<00:00, 59.8MB/s]

### Relationship Data

In [ ]:
# Relationship Character and Actor
!gdown --id 1RdZO6kBhfIRI8wnK1Qj6Wmu2BL9JyH5o

# Relationship Director and Actor
!gdown --id 1PPNoXtU2kFc5v9yTXcwR6SP6w-6PRFUZ

# Relationship Director and Entertainment Media
!gdown --id 1XQvdaThJ3cXy7cbG4AaBb4sCJ7iTuGTV

# Relationship Entertainment Media and Actor
!gdown --id 1eKFWLK061ebQx7znAyHme13GMSe8l5sq

# Relationship Entertainment Media and Age Certification
!gdown --id 1s_pUoQcdQM16KbJKsOg4sF58MClJjAlL

# Relationship Entertainment Media and Character
!gdown --id 1y2ofwg7zLSmJRgWfHHxl8Jy4AvNHRsSs

# Relationship Entertainment Media and Genre
!gdown --id 1Kb5qP1vhJ0O6DLVktMG7GxHpQ3JUBJ0e

# Relationship Entertainment Media and Language
!gdown --id 1qvIRT-ZU1UPcwuRnWc4HG8NO5tctd0ZM

# Relationship Entertainment Media and Production Country
!gdown --id 1BA_TND5T9PufR61Ls6SaQrHurHFkH0vv

# Relationship Entertainment Media and Release Year
!gdown --id 1avEFEhKDrbwHzWT2jgMmdybKUMsjcyDc

# Relationship Entertainment Media and Type
!gdown --id 1AMOtPrx-3TEcY2owNp0rs2H-jtoEMuPp

# Relationship User and Entertainment Media
!gdown --id 1sFxvfAXrHCdmbd8nK6JeKezqhuB0vt2X

# Relationship User and Friend
!gdown --id 1UJNzK9pTA59BFY0OMkhe3HVwKO9Lq_fu

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1RdZO6kBhfIRI8wnK1Qj6Wmu2BL9JyH5o
To: /content/relationship_character_actor.csv
100% 1.56M/1.56M [00:00<00:00, 195MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1PPNoXtU2kFc5v9yTXcwR6SP6w-6PRFUZ
To: /content/relationship_director_actor.csv
100% 22.2k/22.2k [00:00<00:00, 68.5MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1XQvdaThJ3cXy7cbG4AaBb4sCJ7iTuGTV
To: /content/relationship_director_movie.csv
100% 228k/228k [00:00<00:00, 123MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1eKFWLK061ebQx7znAyHme13GMSe8l5sq
To: /content/relationship_movie_actor.csv
100% 7.10M/7.10M [00:00<00:00, 17.8MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1s_pUoQcdQM16KbJKsOg4sF58MClJjAlL
To: /content/relationship_movie_age_certification.csv
100% 54.3k/54.3k [00:00<00:00, 58.6MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1y2ofwg7zLSmJRgWfHHxl8Jy4AvNHRsSs
To: /content/relationship_movie_character.csv
100% 1.48M/1.48M [00:00<00:00, 182MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1Kb5qP1vhJ0O6DLVktMG7GxHpQ3JUBJ0e
To: /content/relationship_movie_genre.csv
100% 625k/625k [00:00<00:00, 140MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1qvIRT-ZU1UPcwuRnWc4HG8NO5tctd0ZM
To: /content/relationship_movie_language.csv
100% 197k/197k [00:00<00:00, 116MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1BA_TND5T9PufR61Ls6SaQrHurHFkH0vv
To: /content/relationship_movie_production_country.csv
100% 366k/366k [00:00<00:00, 133MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1avEFEhKDrbwHzWT2jgMmdybKUMsjcyDc
To: /content/relationship_movie_release_year.csv
100% 295k/295k [00:00<00:00, 82.2MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1AMOtPrx-3TEcY2owNp0rs2H-jtoEMuPp
To: /content/relationship_movie_type.csv
100% 251k/251k [00:00<00:00, 97.6MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1sFxvfAXrHCdmbd8nK6JeKezqhuB0vt2X
To: /content/relationship_user_movie.csv
100% 76.9M/76.9M [00:01<00:00, 71.9MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1UJNzK9pTA59BFY0OMkhe3HVwKO9Lq_fu
To: /content/relationship_user_friends.csv
100% 9.67M/9.67M [00:00<00:00, 26.3MB/s]

## EDA Data

In [175]:
# Raw Dataset
path_name = "/content/Senior_Project/raw_dataset/"
# ndm = pd.read_csv(path_name + "Netflix_Dataset_Movie.csv", encoding="utf-8")
# ndr = pd.read_csv(path_name + "Netflix_Dataset_Rating.csv", encoding="utf-8")
# uk_movie = pd.read_csv(path_name + "vodclickstream_uk_movies_03.csv")
imdb = pd.read_pickle(path_name + "imdb.pkl")
r_title = pd.read_pickle(path_name + "raw_titles.pkl")
title = pd.read_pickle(path_name + "titles.pkl")
r_credits = pd.read_pickle(path_name + "raw_credits.pkl")
credits = pd.read_pickle(path_name + "credits.pkl")


# Cleaned dataset
path_name = "/content/Senior_Project/cleaned_dataset/"
clean_imdb = pd.read_pickle(path_name + "cleaned_imdb_after_check_condition.pkl")
clean_raw_title = pd.read_pickle(path_name + "cleaned_raw_title_after_check_condition.pkl")
clean_title = pd.read_pickle(path_name + "cleaned_title_after_check_condition.pkl")
entertainment_media = pd.read_pickle(path_name + "entertainment_media_dataset.pkl")


# Number for instead dataset
path_name = "/content/Senior_Project/Number_Instead/pkl/"
actor_cleaning = pd.read_pickle(path_name + "actor_cleaning.pkl")
age_cleaning = pd.read_pickle(path_name + "age_certificate_cleaning.pkl")
composer_cleaning = pd.read_pickle(path_name + "composer_cleaning.pkl")
director_cleaning = pd.read_pickle(path_name + "director_cleaning.pkl")
genre_cleaning = pd.read_pickle(path_name + "genre_cleaning.pkl")
language_cleaning = pd.read_pickle(path_name + "language_cleaning.pkl")
country_cleaning = pd.read_pickle(path_name + "production_country_cleaning.pkl")
runtime_cleaning = pd.read_pickle(path_name + "runtime_cleaning.pkl")
type_cleaning = pd.read_pickle(path_name + "type_cleaning.pkl")
writer_cleaning = pd.read_pickle(path_name + "writer_cleaning.pkl")


# # Node Dataset
# actor = pd.read_csv("/content/node_actor.csv", encoding="utf-8")
# age = pd.read_csv("/content/node_age_certification.csv", encoding="utf-8")
# character = pd.read_csv("/content/node_character.csv", encoding="utf-8")
# country = pd.read_csv("/content/node_production_country.csv", encoding="utf-8")
# director = pd.read_csv("/content/node_director.csv", encoding="utf-8")
# media = pd.read_csv("/content/node_entertainment_media.csv",
#                     encoding="utf-8")
# genre = pd.read_csv("/content/node_genre.csv", encoding="utf-8")
# language = pd.read_csv("/content/node_language.csv", encoding="utf-8")
# year = pd.read_csv("/content/node_release_year.csv", encoding="utf-8")
# tpe = pd.read_csv("/content/node_type.csv", encoding="utf-8")
# user = pd.read_csv("/content/node_user.csv", encoding="utf-8")

# # Relationship Dataset
# cha_act = pd.read_csv("/content/relationship_character_actor.csv",
#                       encoding="utf-8")
# dir_act = pd.read_csv("/content/relationship_director_actor.csv",
#                       encoding="utf-8")
# dir_ent = pd.read_csv("/content/relationship_director_movie.csv",
#                       encoding="utf-8")
# ent_act = pd.read_csv("/content/relationship_movie_actor.csv", encoding="utf-8")
# ent_age = pd.read_csv("/content/relationship_movie_age_certification.csv",
#                       encoding="utf-8")
# ent_cha = pd.read_csv("/content/relationship_movie_character.csv",
#                       encoding="utf-8")
# ent_gen = pd.read_csv("/content/relationship_movie_genre.csv", encoding="utf-8")
# ent_lang = pd.read_csv("/content/relationship_movie_language.csv",
#                        encoding="utf-8")
# ent_prod = pd.read_csv("/content/relationship_movie_production_country.csv",
#                        encoding="utf-8")
# ent_year = pd.read_csv("/content/relationship_movie_release_year.csv",
#                        encoding="utf-8")
# ent_type = pd.read_csv("/content/relationship_movie_type.csv", encoding="utf-8")
# user_friend = pd.read_csv("/content/relationship_user_friends.csv",
#                           encoding="utf-8")
# user_ent = pd.read_csv("/content/relationship_user_movie.csv", encoding="utf-8")

In [ ]:
actor_cleaning

     old_id  instead_id
0         9       17205
1       116       17104
2       148       19633
3       168       17148
4       433       17372
..      ...         ...
558   15000       20886
559   15006       20711
560   15009       20545
561   15032       20741
562   17304        1432

[563 rows x 2 columns]

In [ ]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9826 entries, 0 to 9825
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  9826 non-null   int64
 1   title       9825 non-null   object
 2   year        9756 non-null   float64
 3   kind        9788 non-null   object
 4   genre       9733 non-null   object
 5   rating      8949 non-null   float64
 6   vote        8949 non-null   float64
 7   country     9161 non-null   object
 8   language    9033 non-null   object
 9   cast        9482 non-null   object
 10  director    7966 non-null   object
 11  composer    6204 non-null   object
 12  writer      8170 non-null   object
 13  runtime     8770 non-null   float64
dtypes: float64(4), int64(1), object(9)
memory usage: 1.0+ MB

In [ ]:
imdb

,Unnamed: 0,title,year,kind,genre,rating,vote,country,language,cast,director,composer,writer,runtime
0,0,Dinosaur Planet,2003.0,tv mini series,"['Documentary', 'Animation', 'Family']",7.7,474.0,['United States'],['English'],"['Christian Slater', 'Scott Sampson']",NaN,NaN,"['Mike Carrol', 'Mike Carroll', 'Georgann Kane']",50.0
1,1,Character,2021.0,movie,"['Crime', 'Horror', 'Thriller']",8.3,46.0,['Japan'],['Japanese'],"['Masaki Suda', 'Fukase', 'Mitsuki Takahata', ...",['Akira Nagai'],['Youki Kojima'],"['Takashi Nagasaki', 'Takashi Nagasaki', 'Anna...",125.0
2,2,Get Up and Dance!,1994.0,video movie,['Family'],8.1,18.0,['United States'],['English'],"['Paula Abdul', 'Aurorah Allain', 'Bill Bohl',...",['Steve Purcell'],NaN,NaN,54.0
3,3,The Rise and Fall of El Chapo,2016.0,tv movie,['Documentary'],6.9,42.0,['United States'],NaN,NaN,NaN,NaN,NaN,85.0
4,4,Sick - IMDb,NaN,NaN,['Thriller'],NaN,NaN,['United States'],NaN,"['Marc Menchaca', 'Gideon Adlon', 'Dylan Spray...",['John Hyams'],NaN,"['Katelyn Crabb', 'Kevin Williamson']",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9821,9821,All Monsters Attack,1969.0,movie,"['Adventure', 'Family', 'Fantasy']",3.9,4384.0,['Japan'],['Japanese'],"['Tomonori Yazaki', 'Hideyo Amamoto', 'Sachio ...","['Ishirô Honda', 'Jun Fukuda', 'Kengo Furusawa']",['Kunio Miyauchi'],"[""Shin'ichi Sekizawa""]",69.0
9822,9822,Fidel Castro,2005.0,episode,"['Documentary', 'Biography', 'History']",6.4,44.0,NaN,"['English', 'Spanish']","['Rena Baskin', 'Fulgencio Batista', 'James Bl...","['Adriana Bosch', 'M Pink Christofalo']",['Mason Daring'],['Adriana Bosch'],NaN
9823,9823,Epoch,2001.0,tv movie,"['Sci-Fi', 'Thriller']",4.9,2376.0,['United States'],['English'],"['David Keith', 'Stephanie Niznik', ""Ryan O'Ne...",['Matt Codd'],['Richard McHugh'],"['Jonathan Raymond', 'Jonathan Raymond', 'Phil...",96.0
9824,9824,The Company,2003.0,movie,"['Drama', 'Music', 'Romance']",6.3,6501.0,"['United States', 'Germany', 'United Kingdom']",['English'],"['Neve Campbell', 'Malcolm McDowell', 'James F...",['Robert Altman'],['Van Dyke Parks'],"['Neve Campbell', 'Barbara Turner', 'Barbara T...",112.0
9825,9825,Predator,1987.0,movie,"['Action', 'Adventure', 'Sci-Fi', 'Thriller']",7.8,386850.0,"['United States', 'Mexico']","['English', 'Spanish', 'Russian']","['Arnold Schwarzenegger', 'Carl Weathers', 'El...",['John McTiernan'],['Alan Silvestri'],"['Jim Thomas', 'John Thomas']",107.0

In [ ]:
title.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5850 entries, 0 to 5849
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5850 non-null   object
 1   title                 5849 non-null   object
 2   type                  5850 non-null   object
 3   description           5832 non-null   object
 4   release_year          5850 non-null   int64
 5   age_certification     3231 non-null   object
 6   runtime               5850 non-null   int64
 7   genres                5850 non-null   object
 8   production_countries  5850 non-null   object
 9   seasons               2106 non-null   float64
 10  imdb_id               5447 non-null   object
 11  imdb_score            5368 non-null   float64
 12  imdb_votes            5352 non-null   float64
 13  tmdb_popularity       5759 non-null   float64
 14  tmdb_score            5539 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 685.7+ KB

In [ ]:
title

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5845,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.8,45.0,1.466,NaN
5846,tm898842,C/O Kaadhal,MOVIE,A heart warming film that explores the concept...,2021,NaN,134,['drama'],[],NaN,tt11803618,7.7,348.0,NaN,NaN
5847,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,tt14585902,3.8,68.0,26.005,6.300
5848,tm1035612,Dad Stop Embarrassing Me - The Afterparty,MOVIE,"Jamie Foxx, David Alan Grier and more from the...",2021,PG-13,37,[],['US'],NaN,NaN,NaN,NaN,1.296,10.000
5849,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,7,"['family', 'animation', 'comedy']",[],1.0,tt13711094,7.8,18.0,2.289,10.000

In [ ]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77801 entries, 0 to 77800
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   person_id  77801 non-null  int64
 1   id         77801 non-null  object
 2   name       77801 non-null  object
 3   character  68029 non-null  object
 4   role       77801 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.0+ MB

In [ ]:
credits

,person_id,id,name,character,role
0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR
1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR
2,7064,tm84618,Albert Brooks,Tom,ACTOR
3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR
...,...,...,...,...,...
77796,736339,tm1059008,Adelaida Buscato,María Paz,ACTOR
77797,399499,tm1059008,Luz Stella Luengas,Karen Bayona,ACTOR
77798,373198,tm1059008,Inés Prieto,Fanny,ACTOR
77799,378132,tm1059008,Isabel Gaona,Cacica,ACTOR
77800,1950416,tm1059008,Julian Gaviria,NaN,DIRECTOR

In [ ]:
r_title.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5806 entries, 0 to 5805
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 5806 non-null   int64
 1   id                    5806 non-null   object
 2   title                 5805 non-null   object
 3   type                  5806 non-null   object
 4   release_year          5806 non-null   int64
 5   age_certification     3196 non-null   object
 6   runtime               5806 non-null   int64
 7   genres                5806 non-null   object
 8   production_countries  5806 non-null   object
 9   seasons               2047 non-null   float64
 10  imdb_id               5362 non-null   object
 11  imdb_score            5283 non-null   float64
 12  imdb_votes            5267 non-null   float64
dtypes: float64(3), int64(3), object(7)
memory usage: 589.8+ KB

In [ ]:
r_title

,index,id,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,0,ts300399,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN
1,1,tm84618,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0
2,2,tm127384,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0
3,3,tm70993,Life of Brian,MOVIE,1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0
4,4,tm190788,The Exorcist,MOVIE,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5801,5801,tm1014599,Fine Wine,MOVIE,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0
5802,5802,tm1108171,Edis Starlight,MOVIE,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN
5803,5803,tm1045018,Clash,MOVIE,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0
5804,5804,tm1098060,Shadow Parties,MOVIE,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0
5805,5805,ts271048,Mighty Little Bheem: Kite Festival,SHOW,2021,NaN,0,"['family', 'comedy', 'animation']",[],1.0,tt13711094,8.8,16.0

In [ ]:
r_credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77213 entries, 0 to 77212
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      77213 non-null  int64
 1   person_id  77213 non-null  int64
 2   id         77213 non-null  object
 3   name       77213 non-null  object
 4   character  67586 non-null  object
 5   role       77213 non-null  object
dtypes: int64(2), object(4)
memory usage: 3.5+ MB

In [ ]:
r_credits

,index,person_id,id,name,character,role
0,0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR
1,1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR
2,2,7064,tm84618,Albert Brooks,Tom,ACTOR
3,3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR
...,...,...,...,...,...,...
77208,77208,1347054,tm1098060,Nnenna Rachael Okonkwo,Afinni,ACTOR
77209,77209,157590,tm1098060,Lucien Morgan,Dr. Ian Stones,ACTOR
77210,77210,129059,tm1098060,Magdalena Korpas,Jane,ACTOR
77211,77211,2050199,tm1098060,Mistura Olusanya,Nurse Titi,ACTOR
77212,77212,2050423,tm1098060,Yemi Amodu,NaN,DIRECTOR

In [ ]:
title[title["id"] == "ts300399"]

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.6,NaN

In [ ]:
r_title[r_title["id"] == "ts300399"]

,index,id,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,0,ts300399,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN

In [ ]:
clean_raw_title

,id,title,description,runtime,release_year,season,type,age_certification,genre,language,production_country,character,actor,director,writer,composer,imdb_score,imdb_vote
0,1,five came back: the reference films,-,48,1945,1,show,tv-ma,"(documentation,)","(,)","(united states,)","(,)","(,)","(,)","(,)","(,)",0.0,0
1,2,monty python's flying circus,-,30,1969,4,show,tv-14,"(comedy, european)","(,)","(united kingdom,)","(,)","(,)","(,)","(,)","(,)",8.8,72895
2,3,we are all for the fatherland,-,74,1979,0,movie,-,"(documentation,)","(,)","(canada, france, lebanon)","(,)","(,)","(,)","(,)","(,)",6.2,43
3,4,whispers,-,93,1980,0,movie,-,"(documentation,)","(,)","(canada, france, lebanon)","(,)","(,)","(,)","(,)","(,)",7.8,75
4,5,lal patthar,-,153,1971,0,movie,-,"(drama,)","(,)","(india,)","(,)","(,)","(,)","(,)","(,)",6.2,137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5799,5800,momshies! your soul is mine,-,108,2021,0,movie,-,"(comedy,)","(,)","(philippines,)","(jolene, karlene, mylene)","(eris aragoza, francis mata, jason francisco, ...","(easy ferrer,)","(,)","(,)",5.8,26
5800,5801,fine wine,-,100,2021,0,movie,-,"(drama, romance)","(,)","(nigeria,)","(akin, ame, andrew, kaima, kamsi, mr. george, ...","(ademola adedoyin, baaj adebule, bofie itombra...","(seyi babatope,)","(,)","(,)",6.9,39
5801,5802,edis starlight,-,74,2021,0,movie,-,"(documentation, music)","(,)","(,)","(self,)","(edis görgülü,)","(kürşad bayhan,)","(,)","(,)",0.0,0
5802,5803,clash,-,88,2021,0,movie,-,"(drama, family)","(,)","(canada, nigeria)","(ada, chief okereke, dr. johnson, emeka, glady...","(brian hooks, chealse howell, dashawn francis,...","(pascal atuma,)","(,)","(,)",6.5,32
5803,5804,shadow parties,-,116,2021,0,movie,-,"(action, thriller)","(,)","(,)","(afinni, akanji's father, akinola, amoke, arem...","(jibola dabo, jide kosoko, ken erics, lucien m...","(yemi amodu,)","(,)","(,)",6.2,9

## Cleaning

Note:
- กรณีคำที่เขียนไม่เหมือนกันแต่เป็นชื่อเดียวกัน (Optional)
- ถ้า actor ไม่รู้บท ให้ character เขียนว่า "unknow"
- ตรง Title ลบ Space กับอักขระพิเศษแล้วตรวจสอบอีกครั้ง

### Utility function

#### Function for cleaning

In [92]:
def manage_title_credits(data, credits):
  credits_group = credits.groupby(["id", "role"])
  actor_character_list, director_list = [], []
  for key, dataframe in credits_group:
    temp_list = []
    temp_list.append(key[0])
    if dataframe["role"].iloc[0] == "DIRECTOR":
      # temp_list.append(sorted(dataframe["name"].values.tolist()))
      temp_list.append(dataframe["name"].values.tolist())
      director_list.append(temp_list)
    else:
      # temp_list.append(sorted(dataframe["name"].values.tolist()))
      # temp_list.append(sorted(dataframe["character"].values.tolist()))
      temp_list.append(dataframe["name"].values.tolist())
      temp_list.append(dataframe["character"].values.tolist())
      actor_character_list.append(temp_list)
  actor_character_dataframe = pd.DataFrame(actor_character_list,
                                           columns=["id", "actor", "character"])
  director_dataframe = pd.DataFrame(director_list, columns=["id", "director"])
  merge_credits = actor_character_dataframe.merge(director_dataframe, on='id')
  merge_credits_data = data.merge(merge_credits, on="id")
  concat_credits_data = pd.concat([data, merge_credits_data], axis=0)
  concat_credits_data.drop_duplicates(subset=["id"], keep="last", inplace=True)
  return concat_credits_data


def rename_title(data):
  column_name_dict = {"production_countries": "production_country",
                      "genres": "genre", "seasons": "season",
                      "imdb_votes": "imdb_vote"}
  change1 = data.rename(columns=column_name_dict)
  name_list = []
  for name in change1["title"]:
    name = name.lower().replace(" - imdb", "")
    name_list.append(name)
  change1["title"] = name_list
  return change1


def fill_title(data):
  fill_na_value_title = {"actor": "[]", "character": "[]", "director": "[]"}
  data = data.fillna(value=fill_na_value_title)
  return data


def float_to_integer_title(data):
  change2 = data.astype({"season": int, "imdb_vote": int})
  return change2


def string_to_list(data):
  def class_list(data):
    data_list = []
    if data != "[]" and type(data) != list:
      tran = data.translate(cleaning_dict)
      split = tran.split(", ")
      data_list.append(split)
    elif type(data) != list:
      data_list.append([""])
    else:
      data_list.append(data)
    return data_list

  genre_list, country_list, language_list, actor_list = [], [], [], []
  director_list, composer_list, writer_list, character_list = [], [], [], []
  genre = data["genre"]
  country = data["production_country"]
  language = data["language"]
  actor = data["actor"]
  director = data["director"]
  composer = data["composer"]
  writer = data["writer"]
  character = data["character"]
  zipping = zip(genre, country, language, actor, director, composer, writer, character)
  for gen, cty, lan, act, dir, com, wrt, cha in zipping:
    genre_list += class_list(gen)
    country_list += class_list(cty)
    language_list += class_list(lan)
    actor_list += class_list(act)
    director_list += class_list(dir)
    composer_list += class_list(com)
    writer_list += class_list(wrt)
    character_list += class_list(cha)
  data["genre"] = genre_list
  data["production_country"] = country_list
  data["language"] = language_list
  data["actor"] = actor_list
  data["director"] = director_list
  data["composer"] = composer_list
  data["writer"] = writer_list
  data["character"] = character_list
  return data


def replace_title(data):
  genre = data["genre"]
  character = data["character"]
  country = data["production_country"]
  data["genre"] = [[genre_dict.get(g) if g in (genre_dict.keys()) else g for g in gen] for gen in genre]
  data["character"] = [list(filter(lambda c: c != "-", cha)) for cha in character]
  country = [[country_dict.get(c).lower() if c in (country_dict.keys()) else c.lower() for c in cty] for cty in country]
  data["production_country"] = [[country_dict.get(c) if c in (country_dict.keys()) else c for c in cty] for cty in country]
  return data


def arrange(data):
  data = data[["id", "title", "description", "runtime", "release_year",
               "season", "type", "age_certification", "genre", "language",
               "production_country", "character", "actor", "director", "writer",
               "composer", "imdb_score", "imdb_vote"]]
  data = data.reset_index()
  data["id"] = data.index + 1
  data["id"] = data["id"].apply(lambda x: x)
  if data.shape[1] == 19:
    data.drop(["index"], axis=1, inplace=True)
  return data


def manage_case(data):
  data["genre"] = data["genre"].apply(tuple)
  data["production_country"] = data["production_country"].apply(tuple)
  data["language"] = data["language"].apply(tuple)
  data["actor"] = data["actor"].apply(tuple)
  data["director"] = data["director"].apply(tuple)
  data["composer"] = data["composer"].apply(tuple)
  data["writer"] = data["writer"].apply(tuple)
  data["character"] = data["character"].apply(tuple)
  return data

#### Function for checking

In [13]:
def first_title(data):
  check = data.drop_duplicates(subset=["title", "release_year", "type", "genre",
                                       "production_country", "actor", "season",
                                       "director", "runtime", "age_certification"])
  merging = data.merge(check, indicator = True, how = 'outer')
  result = merging.loc[lambda x : x['_merge'] != 'both']
  return data

### Cleaning imdb dataset (Netflix Prize Shows Information (9000 Shows))

Task List for imdb dataset (complete)
  - Drop na in title
  - Add column
    - description
    - age_certification
    - season
  - Replace "NaN" to "-"
  - Change column name
    - year -> release_year
    - kind -> type
    - rating -> imdb_score
    - vote -> imdb_vote
    - country -> production_country
    - cast -> actor
  - Turn every string to lower
  - Change data type
    - year, imdb_vote, runtime: float -> int
    - genre, production_country, language, actor, director, composer, writer: str -> list
  - Replace type from dictionary
  - Replace language
    - none -> ""
    - old -> "old language"

In [138]:
def drop_imdb(data):
  drop = data.dropna(subset=["Unnamed: 0", 'title'])
  drop = drop[drop["kind"] != "video game"]
  return drop


def add_imdb(data):
  data[["description", "age_certification"]] = "-"
  data["season"] = 0
  data["character"] = "[]"
  return data


def rename_imdb(data):
  column_name_dict = {"Unnamed: 0": "id", "year": "release_year",
                      "kind": "type", "rating": "imdb_score",
                      "vote": "imdb_vote", "country" : "production_country",
                      "cast": "actor"}
  change1 = data.rename(columns=column_name_dict)
  name_list = []
  for name in change1["title"]:
    name = name.lower().replace(" - imdb", "")
    name_list.append(name)
  change1["title"] = name_list
  return change1


def fill_imdb(data):
  fill_na_value = {"release_year": 0, "type": "-", "genre": "[]",
                   "imdb_score": 0.0, "imdb_vote": 0.0, "runtime": 0,
                   "production_country": "[]", "language": "[]", "actor": "[]",
                   "director": "[]", "composer": "[]", "writer": "[]"}
  data = data.fillna(value=fill_na_value)
  return data


def lowercase_imdb(data):
  original_title_name = data["title"].values.tolist()
  data["title"] = data["title"].str.lower()
  data["type"] = data["type"].str.lower()
  data["genre"] = data["genre"].str.lower()
  data["production_country"] = data["production_country"].str.lower()
  data["language"] = data["language"].str.lower()
  data["actor"] = data["actor"].str.lower()
  data["director"] = data["director"].str.lower()
  data["composer"] = data["composer"].str.lower()
  data["writer"] = data["writer"].str.lower()
  return original_title_name, data


def float_to_integer_imdb(data):
  change2 = data.astype({"release_year": int, "imdb_vote": int, "runtime": int})
  return change2


def replace_imdb(data):
  language = data["language"]
  genre = data["genre"]
  country = data["production_country"]
  language_list = [[language_dict.get(l) if l in (language_dict.keys()) else l for l in lan] for lan in language]
  genre_list = [[genre_dict.get(g) if g in (genre_dict.keys()) else g for g in gen] for gen in genre]
  country_list = [[country_dict.get(c) if c in (country_dict.keys()) else c for c in cty] for cty in country]
  data["type"] = data["type"].replace(type_dict)
  data["language"] = language_list
  data["genre"] = genre_list
  data["production_country"] = country_list
  return data


def main_imdb(imdb):
  dropping = drop_imdb(imdb)
  adding = add_imdb(dropping)
  renaming = rename_imdb(adding)
  filling = fill_imdb(renaming)
  title_name, turning = lowercase_imdb(filling)
  changing = float_to_integer_imdb(turning)
  changing2 = string_to_list(changing)
  replacing = replace_imdb(changing2)
  arranging = arrange(replacing)
  return arranging


cleaned_imdb = main_imdb(imdb)
cleaned_imdb.to_pickle("cleaned_imdb.pkl")

2 cases for handling
 - ชื่อหนัง ปีที่ฉาย ประเภทของหนัง ประเทศที่ผลิต นักแสดง ระยะเวลาที่ฉาย ผู้กำกับ นักแสดง และผู้แต่งเป็นคนเดียวกัน แสดงว่าเป็นเรื่องเดียวกัน ให้ตัดออก
 - ชื่อหนัง ปีที่ฉายเหมือนกัน แต่นักแสดง ระยะเวลาที่ฉาย และผู้กำกับคนละชุดกัน แสดงว่าเป็นหนังคนละเรื่อง (ประเภทของหนัง(type) อาจจะเหมือนหรือต่างกันก็ได้ ถ้าต่างกันก็คือหนังคนละประเภทกันเลย)


 หมายเหตุ: กรณีชื่อหนังต่างกัน แสดงว่าเป็นหนังที่ฉายคนละประเทศ ให้ไปตรวจสอบข้อมูลเมื่อ concat ข้อมูลแล้ว แล้วสร้าง Relationship เพิ่ม (Optional)

In [139]:
def first_imdb(data):
  data.drop_duplicates(subset=["title", "release_year", "type", "genre",
                               "language", "production_country", "actor",
                               "director", "writer", "runtime"],
                       keep="last", inplace=True)
  return data


def second_imdb(data):
  check = data.drop_duplicates(subset=["title", "release_year"])
  merging = data.merge(check, indicator = True, how = 'outer')
  result = merging.loc[lambda x : x['_merge'] != 'both']
  data = arrange(data)
  return data


def checking_imdb():
  # imdb_file = pd.read_pickle("/content/Senior_Project/cleaned_dataset/cleaned_imdb.pkl")
  imdb_file = pd.read_pickle("/content/cleaned_imdb.pkl")
  managing = manage_case(imdb_file)
  first_condition = first_imdb(managing)
  second_condition = second_imdb(first_condition)
  return second_condition


check_cases_imdb = checking_imdb()
check_cases_imdb.to_pickle("cleaned_imdb_after_check_condition.pkl")

### Cleaning raw title dataset (Netflix TV Shows and Movies (2022 Updated) [May 2022])

Task List for raw title dataset (Task complete)
  - Drop na in title
  - Drop column imdb_id
  - Manage credits dataset in 3 lists are character, actor and director
  - Add column
    - description
    - language
    - composer
    - writer
  - Replace "NaN" to "-" , [] or 0
  - Change column name
    - genres -> genre
    - seasons -> season
    - imdb_votes -> imdb_vote
    - production_countries -> production_country
  - Turn every string to lower
  - Change data type
    - season, imdb_vote: float -> int
    - genre, production_country: str -> list
  - Replace genre and production_country from dictionary

In [25]:
def drop_raw_title(data):
  drop_na_data = data.dropna(subset=["title"])
  drop_column = drop_na_data.drop(columns=["index", "imdb_id"])
  drop_column = drop_column[drop_column["type"] != "video game"]
  return drop_column


def fill_raw_title_raw_credits(data, credits):
  fill_na_value_title = {"age_certification": "-", "seasons": 0.0,
                         "imdb_score": 0.0, "imdb_votes": 0.0}
  fill_na_value_credits = {"character": "-"}
  data = data.fillna(value=fill_na_value_title)
  credits = credits.fillna(value=fill_na_value_credits)
  return data, credits


def lowercase_raw_title_raw_credits(data, credits):
  original_title_name = data["title"].values.tolist()
  data["id"] = data["id"].str.lower()
  data["title"] = data["title"].str.lower()
  data["type"] = data["type"].str.lower()
  data["age_certification"] = data["age_certification"].str.lower()
  data["genres"] = data["genres"].str.lower()
  credits["id"] = credits["id"].str.lower()
  credits["name"] = credits["name"].str.lower()
  credits["character"] = credits["character"].str.lower()
  return original_title_name, data, credits


def add_raw_title(data):
  data[["language", "composer", "writer"]] = "[]"
  data[["description"]] = "-"
  return data


def main_raw_title(raw_title, raw_credits):
  dropping = drop_raw_title(raw_title)
  filling_raw_title, filling_raw_credits = fill_raw_title_raw_credits(dropping, raw_credits)
  title_name, turning_raw_title, turning_raw_credits = lowercase_raw_title_raw_credits(filling_raw_title, filling_raw_credits)
  managing  = manage_title_credits(turning_raw_title, turning_raw_credits)
  adding = add_raw_title(managing)
  renaming = rename_title(adding)
  filling = fill_title(renaming)
  changing = float_to_integer_title(filling)
  changing2 = string_to_list(changing)
  replacing = replace_title(changing2)
  arranging = arrange(replacing)
  return arranging


cleaned_raw_title = main_raw_title(r_title, r_credits)
cleaned_raw_title.to_pickle("cleaned_raw_title.pkl")

2 cases for handling
 - ชื่อหนัง ปีที่ฉาย ประเภทของหนัง ประเทศที่ผลิต นักแสดง ระยะเวลาที่ฉาย ผู้กำกับ นักแสดง และผู้แต่งเป็นคนเดียวกัน แสดงว่าเป็นเรื่องเดียวกัน ให้ตัดออก
 - ชื่อหนัง ปีที่ฉายเหมือนกัน แต่นักแสดง ระยะเวลาที่ฉาย และผู้กำกับคนละชุดกัน แสดงว่าเป็นหนังคนละเรื่อง (ประเภทของหนัง(type) อาจจะเหมือนหรือต่างกันก็ได้ ถ้าต่างกันก็คือหนังคนละประเภทกันเลย)


 หมายเหตุ: กรณีชื่อหนังต่างกัน แสดงว่าเป็นหนังที่ฉายคนละประเทศ ให้ไปตรวจสอบข้อมูลเมื่อ concat ข้อมูลแล้ว แล้วสร้าง Relationship เพิ่ม (Optional)

In [26]:
def second_raw_title(data):
  age = data["age_certification"]
  age[data["id"] == 2335] = "tv-14"
  data = data.loc[data["id"] != 135]
  data = arrange(data)
  return data


def checking_raw_title():
  # title_file = pd.read_pickle("/content/Senior_Project/cleaned_dataset/cleaned_raw_title.pkl")
  title_file = pd.read_pickle("/content/cleaned_raw_title.pkl")
  managing = manage_case(title_file)
  first_condition = first_title(managing)
  second_condition = second_raw_title(first_condition)
  return second_condition


check_cases_raw_title = checking_raw_title()
check_cases_raw_title.to_pickle("cleaned_raw_title_after_check_condition.pkl")

<ipython-input-26-947930aa837f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age[data["id"] == 2335] = "tv-14"

### Cleaning title dataset (Netflix TV Shows and Movies) [July 2022]

Task List for title dataset
  - Drop na in title and id
  - Drop column imdb_id, tmdb_popularity and tmdb_score
  - Manage credits dataset in 3 lists are character, actor and director
  - Add column
    - language
    - composer
    - writer
  - Replace "NaN" to "-" , [] or 0
  - Change column name
    - genres -> genre
    - seasons -> season
    - imdb_votes -> imdb_vote
    - production_countries -> production_country
  - Turn every string to lower
  - Change data type
    - imdb_vote: float -> int
    - genre, production_country: str -> list
  - Replace genre and production_country from dictionary

In [15]:
def drop_title(data):
  drop_na_data = data.dropna(subset=["id", 'title'])
  drop_column = drop_na_data.drop(columns=["imdb_id", "tmdb_popularity",
                                      "tmdb_score"])
  drop_column = drop_column[drop_column["type"] != "video game"]
  return drop_column


def fill_title_credits(data, credits):
  fill_na_value_title = {"description": "-", "age_certification": "-",
                         "seasons": 0.0, "imdb_score": 0.0, "imdb_votes": 0.0}
  fill_na_value_credits = {"character": "-"}
  data = data.fillna(value=fill_na_value_title)
  credits = credits.fillna(value=fill_na_value_credits)
  return data, credits


def lowercase_title_credits(data, credits):
  original_title_name = data["title"].values.tolist()
  data["id"] = data["id"].str.lower()
  data["title"] = data["title"].str.lower()
  data["type"] = data["type"].str.lower()
  data["description"] = data["description"].str.lower()
  data["age_certification"] = data["age_certification"].str.lower()
  data["genres"] = data["genres"].str.lower()
  credits["id"] = credits["id"].str.lower()
  credits["name"] = credits["name"].str.lower()
  credits["character"] = credits["character"].str.lower()
  return original_title_name, data, credits


def add_title(data):
  data[["language", "composer", "writer"]] = "[]"
  return data


def replace_title(data):
  genre = data["genre"]
  character = data["character"]
  country = data["production_country"]
  data["genre"] = [[genre_dict.get(g) if g in (genre_dict.keys()) else g for g in gen] for gen in genre]
  data["character"] = [list(filter(lambda c: c != "-", cha)) for cha in character]
  data["production_country"] = [[country_dict.get(c).lower() if c in (country_dict.keys()) else c.lower() for c in cty] for cty in country]
  return data


def main_title(title, credits):
  dropping = drop_title(title)
  filling_title, filling_credits = fill_title_credits(dropping, credits)
  title_name, turning_title, turning_credits = lowercase_title_credits(filling_title, filling_credits)
  managing  = manage_title_credits(turning_title, turning_credits)
  adding = add_title(managing)
  renaming = rename_title(adding)
  filling = fill_title(renaming)
  changing = float_to_integer_title(filling)
  changing2 = string_to_list(changing)
  replacing = replace_title(changing2)
  arranging = arrange(replacing)
  return arranging


cleaned_title = main_title(title, credits)
cleaned_title.to_pickle("cleaned_title.pkl")

2 cases for handling
 - ชื่อหนัง ปีที่ฉาย ประเภทของหนัง ประเทศที่ผลิต นักแสดง ระยะเวลาที่ฉาย ผู้กำกับ นักแสดง และผู้แต่งเป็นคนเดียวกัน แสดงว่าเป็นเรื่องเดียวกัน ให้ตัดออก
 - ชื่อหนัง ปีที่ฉายเหมือนกัน แต่นักแสดง ระยะเวลาที่ฉาย และผู้กำกับคนละชุดกัน แสดงว่าเป็นหนังคนละเรื่อง (ประเภทของหนัง(type) อาจจะเหมือนหรือต่างกันก็ได้ ถ้าต่างกันก็คือหนังคนละประเภทกันเลย)


 หมายเหตุ: กรณีชื่อหนังต่างกัน แสดงว่าเป็นหนังที่ฉายคนละประเทศ ให้ไปตรวจสอบข้อมูลเมื่อ concat ข้อมูลแล้ว แล้วสร้าง Relationship เพิ่ม (Optional)

In [16]:
def second_title(data):
  age = data["age_certification"]
  age[data["id"] == 2282] = "tv-14"
  data = data.loc[data["id"] != 125]
  data = arrange(data)
  return data


def checking_title():
  # title_file = pd.read_pickle("/content/Senior_Project/cleaned_dataset/cleaned_title.pkl")
  title_file = pd.read_pickle("/content/cleaned_title.pkl")
  managing = manage_case(title_file)
  first_condition = first_title(managing)
  second_condition = second_title(first_condition)
  return second_condition


check_cases_title = checking_title()
check_cases_title.to_pickle("cleaned_title_after_check_condition.pkl")

<ipython-input-16-3a91df68c1a3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age[data["id"] == 2282] = "tv-14"

### Cleaning data after concatination 3 datasets

Task List for entertainment media dataset
- concat raw_title and title, then concat imdb
- Re-index and re-id column based on index
- Check 2 conditions
  1. ชื่อหนัง ปีที่ฉาย ประเภทของหนัง ประเทศที่ผลิต นักแสดง ระยะเวลาที่ฉาย ผู้กำกับ นักแสดง และผู้แต่งเป็นคนเดียวกัน แสดงว่าเป็นเรื่องเดียวกัน ให้ตัดออก
  2. ชื่อหนัง ปีที่ฉายเหมือนกัน แต่นักแสดง ระยะเวลาที่ฉาย และผู้กำกับคนละชุดกัน แสดงว่าเป็นหนังคนละเรื่อง (ประเภทของหนัง(type) อาจจะเหมือนหรือต่างกันก็ได้ ถ้าต่างกันก็คือหนังคนละประเภทกันเลย)
- Title name to original name
- String lower case -> Capitalize
- Replacing
  - "-" -> NaN
  - 0 -> NaN
  - Tuple -> List
    - Blank list -> NaN

In [ ]:
def concat(imdb, raw_title, title):
  data = pd.concat([imdb, raw_title, title], axis=0)
  return data

In [ ]:
def replacing_actor(data):
  old_id_actor = actor_cleaning["old_id"]
  instead_id_actor = actor_cleaning["instead_id"]
  for index in range(len(old_id_actor)):
    new_data = data["actor"].loc[data["id"] == old_id_actor[index]].values[0]
    data.at[data.index[data['id'] == instead_id_actor[index]].tolist()[0], "actor"] = new_data
  return data


def replacing_age_certificate(data):
  old_id_age = age_cleaning["old_id"]
  instead_id_age = age_cleaning["instead_id"]
  for index in range(len(old_id_age)):
    new_data = data["age_certification"].loc[data["id"] == old_id_age[index]].values[0]
    data.at[data.index[data['id'] == instead_id_age[index]].tolist()[0], "age_certification"] = new_data
  return data


def replacing_composer(data):
  old_id_composer = composer_cleaning["old_id"]
  instead_id_composer = composer_cleaning["instead_id"]
  for index in range(len(old_id_composer)):
    new_data = data["composer"].loc[data["id"] == old_id_composer[index]].values[0]
    data.at[data.index[data['id'] == instead_id_composer[index]].tolist()[0], "composer"] = new_data
  return data


def replacing_director(data):
  old_id_director = director_cleaning["old_id"]
  instead_id_director = director_cleaning["instead_id"]
  for index in range(len(old_id_director)):
    new_data = data["director"].loc[data["id"] == old_id_director[index]].values[0]
    data.at[data.index[data['id'] == instead_id_director[index]].tolist()[0], "director"] = new_data
  return data


def replacing_genre(data):
  old_id_genre = genre_cleaning["old_id"]
  instead_id_genre = genre_cleaning["instead_id"]
  for index in range(len(old_id_genre)):
    new_data = data["genre"].loc[data["id"] == old_id_genre[index]].values[0]
    data.at[data.index[data['id'] == instead_id_genre[index]].tolist()[0], "genre"] = new_data
  return data


def replacing_language(data):
  old_id_language = language_cleaning["old_id"]
  instead_id_language = language_cleaning["instead_id"]
  for index in range(len(old_id_language)):
    new_data = data["language"].loc[data["id"] == old_id_language[index]].values[0]
    data.at[data.index[data['id'] == instead_id_language[index]].tolist()[0], "language"] = new_data
  return data


def replacing_production_country(data):
  old_id_country = country_cleaning["old_id"]
  instead_id_country = country_cleaning["instead_id"]
  for index in range(len(old_id_country)):
    new_data = data["production_country"].loc[data["id"] == old_id_country[index]].values[0]
    data.at[data.index[data['id'] == instead_id_country[index]].tolist()[0], "production_country"] = new_data
  return data


def replacing_runtime(data):
  old_id_runtime = runtime_cleaning["old_id"]
  instead_id_runtime = runtime_cleaning["instead_id"]
  for index in range(len(old_id_runtime)):
    new_data = data["runtime"].loc[data["id"] == old_id_runtime[index]].values[0]
    data.at[data.index[data['id'] == instead_id_runtime[index]].tolist()[0], "runtime"] = new_data
  return data


def replacing_type(data):
  old_id_type = type_cleaning["old_id"]
  instead_id_type = type_cleaning["instead_id"]
  for index in range(len(old_id_type)):
    new_data = data["type"].loc[data["id"] == old_id_type[index]].values[0]
    data.at[data.index[data['id'] == instead_id_type[index]].tolist()[0], "type"] = new_data
  return data


def replacing_writer(data):
  old_id_writer = writer_cleaning["old_id"]
  instead_id_writer = writer_cleaning["instead_id"]
  for index in range(len(old_id_writer)):
    new_data = data["writer"].loc[data["id"] == old_id_writer[index]].values[0]
    data.at[data.index[data['id'] == instead_id_writer[index]].tolist()[0], "writer"] = new_data
  return data


def delete_row(data):
  delete_list = delete["delete_number"].tolist()
  for d in delete_list:
    data = data[data.id != d]
  return data


def first_condition_entertainment_media_dataset(data):
  data.drop_duplicates(subset=["title", "release_year", "type", "genre",
                               "production_country", "actor", "director",
                               "runtime", "age_certification"],
                       keep="last", inplace=True)
  return data
  # check = data.drop_duplicates(subset=["title", "release_year", "type", "genre",
  #                                      "production_country", "actor", "director",
  #                                      "runtime", "age_certification"])
  # merging = data.merge(check, indicator = True, how = 'outer')
  # result = merging.loc[lambda x : x['_merge'] != 'both']
  # return result


def second_condition_entertainment_media_dataset(data):
  check = data.drop_duplicates(subset=["title", "release_year"])
  merging = data.merge(check, indicator = True, how = 'outer')
  result = merging.loc[lambda x : x['_merge'] != 'both']
  return result


def third_condition_entertainment_media_dataset(data):
  check = data.drop_duplicates(subset=["title"])
  merging = data.merge(check, indicator = True, how = 'outer')
  result = merging.loc[lambda x : x['_merge'] != 'both']
  return result


def tuple_to_list(data):
  data["genre"] = data["genre"].apply(list)
  data["production_country"] = data["production_country"].apply(list)
  data["language"] = data["language"].apply(list)
  data["actor"] = data["actor"].apply(list)
  data["director"] = data["director"].apply(list)
  data["composer"] = data["composer"].apply(list)
  data["writer"] = data["writer"].apply(list)
  data["character"] = data["character"].apply(list)
  return data


def entertainment_media_dataset(imdb, raw_title, title):
  concating = concat(imdb, raw_title, title)
  arranging = arrange(concating)
  first_condition = first_condition_entertainment_media_dataset(concating)
  # lt = tuple_to_list(concating)
  # stl = string_to_list(lt)
  # mc = manage_case(data)
  # cleaning_actor = replacing_actor(lt)
  # cleaning_age_certificate = replacing_age_certificate(cleaning_actor)
  # cleaning_composer = replacing_composer(cleaning_age_certificate)
  # cleaning_director = replacing_director(cleaning_composer)
  # cleaning_genre = replacing_genre(cleaning_director)
  # cleaning_language = replacing_language(cleaning_genre)
  # cleaning_production_country = replacing_production_country(cleaning_language)
  # cleaning_runtime = replacing_runtime(cleaning_production_country)
  # cleaning_type = replacing_type(cleaning_runtime)
  # cleaning_writer = replacing_writer(cleaning_type)
  # deleting_row = delete_row(cleaning_writer)
  # arranging = arrange(deleting_row)
  # second_condition = second_condition_entertainment_media_dataset(arranging)
  # third_condition = third_condition_entertainment_media_dataset(data)
  return first_condition



# test_file = pd.read_pickle("/content/Senior_Project/cleaned_dataset/entertainment_media_dataset.pkl")
emd = entertainment_media_dataset(clean_imdb, clean_raw_title, clean_title)
# emd = entertainment_media_dataset(test_file)
# test_file.to_pickle("third_condition.csv")

In [63]:
read_file = pd.read_pickle("/content/cleaned_raw_title_after_check_condition.pkl")

In [62]:
ct = pd.read_pickle("/content/cleaned_title_after_check_condition.pkl")

In [140]:
ib = pd.read_pickle("/content/cleaned_imdb_after_check_condition.pkl")

In [166]:
read_file[read_file["title"] == "love, life & everything in between"]

,id,title,description,runtime,release_year,season,type,age_certification,genre,language,production_country,character,actor,director,writer,composer,imdb_score,imdb_vote
1795,1796,"love, life & everything in between",-,27,2022,1,show,tv-14,"(comedy, drama, romance)","(,)","(saudi arabia,)","(,)","(,)","(,)","(,)","(,)",5.3,65

In [167]:
ct[ct["title"] == "love, life & everything in between"]

,id,title,description,runtime,release_year,season,type,age_certification,genre,language,production_country,character,actor,director,writer,composer,imdb_score,imdb_vote
5578,5579,"love, life & everything in between",this black humor pan-arabic anthology series i...,27,2022,1,show,tv-14,"(comedy, drama, romance)","(,)","(egypt, lebanon, morocco, saudi arabia, tunisia)","(sona, lotfi, suad, sultan, amina, diab, hassa...","(saif mohsen, alaa nashat, nasser akabab, fati...","(mahmoud sabbagh, sandra nashaat, kaouther ben...","(,)","(,)",5.6,94

In [64]:
df_c, df_a = pd.DataFrame(), pd.DataFrame()
title_list, replace_character, old_character = [], [], []
replace_actor, old_actor = [], []
for title in tqdm(read_file["title"]):
  if title in entertainment_media["title"].tolist():
    title_list.append(title)
    replace_character.append(read_file.loc[read_file["title"] == title, "character"].values[0])
    replace_actor.append(read_file.loc[read_file["title"] == title, "actor"].values[0])
    old_character.append(entertainment_media.loc[entertainment_media["title"] == title, "character"].values[0])
    old_actor.append(entertainment_media.loc[entertainment_media["title"] == title, "actor"].values[0])
df_c["title"] = title_list
df_c["replace_character"] = replace_character
df_c["old_character"] = old_character
df_a["title"] = title_list
df_a["replace_actor"] = replace_actor
df_a["old_actor"] = old_actor

100%|██████████| 5804/5804 [00:37<00:00, 156.00it/s]

In [65]:
df_c

,title,replace_character,old_character
0,five came back: the reference films,"(,)","('',)"
1,monty python's flying circus,"(,)","('',)"
2,we are all for the fatherland,"(,)","('',)"
3,whispers,"(,)","('',)"
4,lal patthar,"(,)","('',)"
...,...,...,...
5796,momshies! your soul is mine,"(jolene, mylene, karlene)","('jolene', 'karlene', 'mylene')"
5797,fine wine,"(mr. george, kaima, akin, tunji, temisan, ame,...","('akin', 'ame', 'andrew', 'kaima', 'kamsi', 'm..."
5798,edis starlight,"(self,)","('self',)"
5799,clash,"(nneka, iolo chinyere, gladys, dr. johnson, ch...","('ada', 'chief okereke', 'dr. johnson', 'emeka..."
5800,shadow parties,"(chief atilola, princess fadekemi, owuteru, am...","('""akanjis father""', 'afinni', 'akinola', 'amo..."

In [66]:
df_a

,title,replace_actor,old_actor
0,five came back: the reference films,"(,)",()
1,monty python's flying circus,"(,)",()
2,we are all for the fatherland,"(,)",()
3,whispers,"(,)",()
4,lal patthar,"(,)",()
...,...,...,...
5796,momshies! your soul is mine,"(jolina magdangal, melai cantiveros, karla est...",()
5797,fine wine,"(richard mofe-damijo, ego nwosu, keppy ekpenyo...",()
5798,edis starlight,"(edis görgülü,)",()
5799,clash,"(omoni oboli, stephanie okereke-linus, merlisa...",()
5800,shadow parties,"(jide kosoko, omotola jalade-ekeinde, yemi bla...",()

In [91]:
df_a[df_a["title"] == "zz top: that little ol' band from texas"]

,title,replace_actor,old_actor
4546,zz top: that little ol' band from texas,"(frank beard, billy gibbons, dusty hill, joshu...",()

In [93]:
for name in tqdm(entertainment_media["title"]):
  for title in df_c["title"]:
    if name == title:
      entertainment_media.loc[entertainment_media["title"] == name, "character"] = str(df_c.loc[df_c["title"] == title, "replace_character"].values[0])
      entertainment_media.loc[entertainment_media["title"] == name, "actor"] = str(df_a.loc[df_a["title"] == title, "replace_actor"].values[0])

100%|██████████| 15249/15249 [00:58<00:00, 258.94it/s]

In [95]:
stl = string_to_list(entertainment_media)
stl.to_pickle("entertainment_media_dataset.pkl")

In [127]:
title_list = []
for a in tqdm(ct["title"]):
  for b in entertainment_media["title"]:
    if a == b:
      c = len(ct.loc[ct["title"] == a, "actor"].values[0])
      d = len(entertainment_media.loc[entertainment_media["title"] == b, "actor"].values[0])
      if c > d:
        entertainment_media.loc[entertainment_media["title"] == b, "actor"] = str(ct.loc[ct["title"] == a, "actor"].values[0])
        entertainment_media.loc[entertainment_media["title"] == b, "character"] = str(ct.loc[ct["title"] == a, "character"].values[0])
        title_list.append(a)

100%|██████████| 5848/5848 [00:33<00:00, 175.44it/s]

In [129]:
stl = string_to_list(entertainment_media)
stl.to_pickle("entertainment_media_dataset.pkl")

In [147]:
for name in tqdm(entertainment_media["title"]):
  for title in ib["title"]:
    if name == title:
      entertainment_media.loc[entertainment_media["title"] == name, "actor"] = str(ib.loc[ib["title"] == title, "actor"].values[0])

100%|██████████| 15249/15249 [01:05<00:00, 232.64it/s]

In [153]:
stl = string_to_list(entertainment_media)
stl.to_pickle("entertainment_media_dataset.pkl")

In [156]:
for name in tqdm(entertainment_media["title"]):
  for title in ib["title"]:
    if name == title:
      entertainment_media.loc[entertainment_media["title"] == name, "composer"] = str(ib.loc[ib["title"] == title, "composer"].values[0])
      entertainment_media.loc[entertainment_media["title"] == name, "writer"] = str(ib.loc[ib["title"] == title, "writer"].values[0])

100%|██████████| 15249/15249 [01:34<00:00, 162.13it/s]

In [158]:
stl = string_to_list(entertainment_media)
stl.to_pickle("entertainment_media_dataset.pkl")

In [162]:
for name in tqdm(entertainment_media["title"]):
  for title in read_file["title"]:
    if name == title:
      entertainment_media.loc[entertainment_media["title"] == name, "director"] = str(read_file.loc[read_file["title"] == title, "director"].values[0])

100%|██████████| 15249/15249 [00:36<00:00, 414.96it/s]

In [164]:
director_list = []
for a in tqdm(ct["title"]):
  for b in entertainment_media["title"]:
    if a == b:
      c = len(ct.loc[ct["title"] == a, "director"].values[0])
      d = len(entertainment_media.loc[entertainment_media["title"] == b, "director"].values[0])
      if c > d:
        entertainment_media.loc[entertainment_media["title"] == b, "director"] = str(ct.loc[ct["title"] == a, "director"].values[0])
        director_list.append(a)

100%|██████████| 5848/5848 [00:33<00:00, 174.87it/s]

In [169]:
for name in tqdm(entertainment_media["title"]):
  for title in ib["title"]:
    if name == title:
      entertainment_media.loc[entertainment_media["title"] == name, "director"] = str(ib.loc[ib["title"] == title, "director"].values[0])

100%|██████████| 15249/15249 [01:09<00:00, 218.99it/s]

In [171]:
stl = string_to_list(entertainment_media)
stl.to_pickle("entertainment_media_dataset.pkl")

In [176]:
entertainment_media[entertainment_media["id"] == 54]

,id,title,description,runtime,release_year,season,type,age_certification,genre,language,production_country,character,actor,director,writer,composer,imdb_score,imdb_vote
53,54,¡vampiros en la habana!,-,69,1985,0,movie,-,"[animation, comedy, horror, romance]","[english, spanish]","[cuba, spain, west germany]","[,]","[frank gonzález, manuel marín, irela bravo, ca...","[juan padrón,]","[ernesto padrón, ernesto padrón, juan padrón]","[rembert egües,]",7.0,1322

In [ ]:
for character in tqdm(entertainment_media["character"]):
  for cha in df_c["old_character"]:
    if cha == character:
      new_value = read_file.loc[read_file["title"] == "fine wine", "character"].values[0]
      entertainment_media["character"].replace(cha, character)

In [ ]:
count = 0
for i in tqdm(range(entertainment_media.shape[0])):
  for j in range(old_title.shape[0]):
    if entertainment_media["title"].iloc[[i]][i] == old_title["old_title"].iloc[[j]][j]:
      old = entertainment_media["title"].iloc[[i]][i]
      new = old_title["new_title"].iloc[[j]][j]
      entertainment_media = entertainment_media.replace(old, new)
      count += 1

100%|██████████| 15249/15249 [10:59<00:00, 23.12it/s]

In [ ]:
cutoff = ["argentina's luciano mellera emphasizes the humorous and fantastical aspects of childhood through comedic impersonations and insights on daily life.",
          "fed up with his wife’s distancing from him, hadi goes on a business trip to turkey where he meets a special woman, an encounter that changes his life forever.",
          "the world is on the verge of a devastating war with monsters who are coming to retrieve the scaling stone. yin yang master qingming's life is in danger and he travels to different worlds to prepare for the upcoming assaults. on his journey, qingming finds that the key to all the calamities is embracing his hybrid identity of both human and monster.",
          "years after his father disowns his adopted brother for marrying a woman of lower social standing, a young man goes on a mission to reunite his family."]
new_instead = []
for d in sorted(des):
  if d not in cutoff and d not in new_instead:
    new_instead.append(d)
    # print(d)
print(len(new_instead))
print(new_instead)

910

In [ ]:
entertainment_media["character"] = entertainment_media["character"].astype(str)

In [ ]:
for i in entertainment_media["character"]:
  print(type(i))

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [ ]:
name_list, result = [], []
for title in test_file["title"]:
  # if not title.isalpha():
  #   s1 = re.sub("[^A-Za-z]","",title)
  #   if s1 in test_file["title"]:
  #     print(title)
  # if title not in emd["title"].tolist():
  if " " in title and title not in emd["title"].tolist():
    name = title.replace(" ", "")
    name_list.append(name)
    print(name)
for n in name_list:
  if n in test_file["title"].tolist() or name_list.count(n) > 1 and n not in result:
    result.append(n)
result
# test_file["title"] = name_list

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
remarriage&desires
remastered:devilatthecrossroads
remastered:massacreatthestadium
remastered:thelion'sshare
remastered:themiamishowbandmassacre
remastered:thetwokillingsofsamcooke
remastered:trickydick&themaninblack
remastered:whokilledjammasterjay?
remastered:whoshotthesheriff
rememberthetitans
rememberyou
remembranceofthedaleks:partthree
renaissanceman
rennie'slanding
reospeedwagonlive
reply1988
reptile2001
requiemforadream
requiemforavampire
requiemformurder
requiemfromthedarkness
rescuefromgilligan'sisland
rescueheroes:themovie
rescuemeseason4
rescueofemeraldcity:part1
rescuedbyruby
residentevil
residentevil:apocalypse
residentevil:infinitedarkness
residentevil:welcometoraccooncity
resistingarrest4specialedition
resorttolove
restaurantsontheedge
restlesssouls
resurrectionofthedaleks:parttwo
resurrection:ertugrul
returnofthechineseboxer
returnofthekillertomatoes
returnofthelivingdeadiii
returnofthesecaucusseven
returnofthevampire
returnto'sincity':atributetogramparsons
returntoabettertomorrow
returntolonesomedove
returntome
returntooz
returntoparadise
returntosender
returntosnowyriver
returntospace
returntothebatcave:themisadventuresofadamandburt
returntothelostworld
returnwithhonor
revelations:themastersoftheuniverse:revelationaftershow
revengeinolympia
revengeoffrankenstein
revengeofthedead
revengeofthemusketeers
revengeoftheninja
revengeofthepontianak
reversaloffortune
reversingroe
revolutionos
revolutionarygirlutena
revolutionarygirlutena:themovie
revolutionarylove
rextherunt
rhapsodyinaugust
rheagallforce
rhyme&reason
rhymetimetown
rhysnicholson:liveattheathenaeum
rhythm+flow
rhythm+flowfrance
ricardoo'farrill:abrazogenial
ricardoo'farrill:abrazonavide‚àö¬±o
ricardoquevedo:haygenteas‚àö‚â†
ricardoquevedo:losamargadossomosm‚àö¬∞s
richinlove
richardavedon:darknessandlight
richarddreyfuss:jaws,goodbyegirl,closeencountersofthethirdkind,bookclub,andastronaut
richardjeni:abigsteamingpileofme
richardpryor:iain'tdeadyet,#*%$#@!!
richardpryor:liveandsmokin'
richardpryor:liveinconcert
richardpryor:liveonthesunsetstrip
richardpryor...hereandnow
richardrodgers:thesweetestsounds
rickandmortyseason3...whatwillhappen?!fullepisodediscussion!
rickandmorty'ssecretsbehindthecitadel?!-rickandmortyseason3cartoonconspiracy
rickygervais:humanity
rickygervais:supernature
rickymartin:onenightonly
rickyzoom
ridelikeagirl
rideontime
ridin'therails:thegreatamericantrainstory
ridingfaith
ridinggiants
ridinginvanswithboys
ridingtherails
ridleyjones
righthererightnow
rilakkumaandkaoru
rimoftheworld
ring0:birthday
ring2
ringofbrightwater
ringofdarkness
ringoffire:theemilegriffithstory
ringoutyourdead
riogrande
ripitoff
riptide
riphagentheuntouchable
rippingyarns
riseofempires:ottoman
riseoftheguardians
riseoftheteenagemutantninjaturtles
riseoftheundead
rise:inikalilah
risinghigh
risingphoenix
ritamoreno:justagirlwhodecidedtogoforit
river'sedge
riverdance:theanimatedadventure
riversandtides
rknagar
rko281
roadgames
roadrage:partone
roadtohigh&low
roadtoperdition
roadtoroma
roadtrip
roadwarriors
roadie:mydocumentary
robschneider:asianmomma,mexicankids
robvandam:oneofakind
robertrauschenberg:inventivegenius
roberttownsendandhispartnersincrime
robinandthe7hoods
robinhooddifinemillennio
robinrobin
robinsoncrusoe
robocarpoli
robocop:primedirectives
robotchicken
robottrains
rock'n'rollforever:edsullivan'sgreatesthits
rockacapella
rockandrule
rockmyheart
rockmyworld
rockon!!
rockschool
rockstar
rockthekasbah
rocketsredglare!
rocko'smodernlife:staticcling
rockymarciano
rodserling:submittedforyourapproval
rodstewart:storyteller1984-1991
rodgers&hammerstein:thesoundofmovies
rodneycarrington:herecomesthetruth
rodneyking
rodrigosant'anna:i'mhere,i'mqueer!
roger&me
rogerwaters:inthefleshlive
roguecity
roguetrader
roguewarfare:deathofanation
roguewarfare:thehunt
roliepolieolie:thegreatdefenderoffun
rollinginthesky:f/a-18blueangels
rollingkansas
rollingthunderrevue:abobdylanstorybymartinscorsese
romanempire
romancedoll
romanceisabonusbook
romantikkomedi
romantikkomedi2:bekarl∆í¬±∆í√ºaveda
rome:power&glory
romeoakbarwalter
romeoisbleeding
romperstomper
ronhoward:adirector'sjournal
ronwhite:ifyouquitlistening,i'llshutup
ronwhite:theycallmetatersalad
ronaldreagan:alegacyremembered
ronniecoleman:theking
ronnychieng:asiancomediandestroysamerica!
ronnychieng:speakeasy
rookiehistoriangoohae-ryung
room2806:theaccusation
roomatthetop
rootingforroona
rootsofrhythm
roperandgoodie
roryo'sheawashere
roryscoveltriesstand-upforthefirsttime
rosariotijeras
rosehill
roseisland
rosered
roseanna'sgrave
roseanne:anunauthorizedbiography
rosencrantzandguildensternaredead,andabsurd
roswell,newmexico
rotikapadaaurmakaan
roughmagic
roughingit
roughnecks:thestarshiptrooperschronicles
roujinz
route9
routes:dancingtoneworleans
rowdyrathore
rowingwiththewind
roxanne,roxanne
roxette:allvideosevermade&more!-thecompletecollection1987-2001
roxymusic:liveattheapollo
royjonesjr'sgreatestknockouts
royorbison:blackandwhitenight30
royorbison:liveataustincitylimits
royaldeceit
royalshakespearecompany:thetempest
royaltramp
royalwarriors
royalwedding
rub&tug
rubaruroshni
ruby&thebeast/max&ruby'shalloweenhouse/max'strickortreat
rubysparks
ruby'sbucketofblood
rudeboy
rudolphandfrosty'schristmasinjuly
rudolphthered-nosedreindeer&theislandofmisfittoys
rudra:secretoftheblackmoon
rudy:therudygiulianistory
rufus!rufus!rufus!doesjudy!judy!judy!
rugratsgowild
rugratstalesfromthecrib:snowwhite
ruinexplorers
rules:pyaarkasuperhitformula
rumandcoke
rumbleinthebronx
rumble:theindianswhorockedtheworld
rumictheater:mermaidforest
rumorhasit...
rumpoleofthebailey,seriesi:rumpoleandthemarriedlady
rumspringa-einamishinberlin
runlolarun
runon
runsilentrundeep
runthewildfields
runningbrave
runningfree
runningman
runningonkarma
runningonthesun:thebadwater135
runningoutoftime
runningoutoftime2
rurounikenshinparti:origins
rurounikenshin:thebeginning
rurounikenshin:thefinal
rurounikenshin:trustandbetrayal
rushinrio
rush:chronicles
russellbrand:re:birth
russellhoward:lubricant
russellhoward:recalibrate
russellpeters:almostfamous
russia,landofthetsars
russianark
russiandoll
rustcreek
rustneversleeps
rustvalleyrestorers
rustlers'rhapsody
ruthlesspeople
ryanhamilton:happyface
sstorm
s.i.c.k.serialinsaneclownkiller
s.w.a.t.:undersiege
s‚àö‚â†,miamor
s21:thekhmerrougekillingmachine
sabel-burumbah
sabermarionettej
sabrinatheteenagewitch
sabrinatheteenagewitchinfriendsforever
sacredgames
sacredheart
sacredplanet
sacredsilence
sacrificio:whobetrayedcheguevara
sadhillunearthed
sade-lifepromisepridelove
sadelive
sade:loverslive
safeconduct
sahebbiwiaurgangsterreturns
sahibbibiaurghulam
sailormoon
sailormooncrystal
sailormoonr:themovie:thepromiseoftherose
sailormoonsupers:ami'sfirstlove
sailormoonsupers:themovie:blackdreamhole
saintseiya:knightsofthezodiac
saintsinner
sakalingmagingtayo
sakho&mangane
sakuradiaries
sakurawars
sakurawars:themovie
salaambombay!
saladinthevictorious
salam-thefirst******nobellaureate
salarymankintaro
salemwitchtrials
sallyhemings:anamericanscandal
sallyofthesawdust
saltfatacidheat
saltofthissea
saludosamigos
salvatoregiuliano
sam&cat
samjay:3inthemorning
samkinison:breakingtherules
samkinison:familyentertainmenthour
samkinison:liveinvegas
samkinison:thescreamcontinues
samkinison:whydidwelaugh?
samsmith:lovegoes‚Äö√Ñ√¨liveatabbeyroadstudios
samaritangirl
samerivertwice
sametime,nextchristmas
sammy&co
samouniroad
samurai7
samuraiassassin
samuraichamploo
samuraideeperkyo
samuraifiction
samuraigirl:realbouthighschool
samuraigourmet
samuraigun
samuraijack
samuraijackseason5
samurairabbit:theusagichronicles
samuraishodown:themotionpicture
samuraispy
sandcastle
sandstorm
sandrabernhard:i'mstillhere...damnit!
sandywexler
sanitationday
sanpa:sinsofthesavior
santabantapvtltd
santaclaritadiet
santaclausconquersthemartians
santaclausiscomin'totown
santapac'smerryberryday
santana:sacredfire-liveinmexico
santana:supernaturallive
santocach‚àö‚â•n
sapseason
sara'snotebook
sarahbrightmaninconcert
sarahbrightman:harem-adesertfantasy
sarahbrightman:onenightineden-liveinconcert
sarahbrightman:theharemworldtour-livefromlasvegas
sarahcooper:everything'sfine
sarahmclachlan
sarahmclachlan:afterglowlive
sarahmclachlan:mirrorball
sarahmclachlan:videocollection1989-1998
sarahsilverman:aspeckofdust
sardarkagrandson
sarvamthaalamayam
sas:rednotice
sasquatchhunters
satan'sbrew
satinrouge
satriaheroes:revengeofthedarkness
sattepesatta
saturdaymorningallstarhits!
saturdaynightandsundaymorning
saturdaynightlive:40thanniversaryspecial
saturdaynightlive:christmas
saturdaynightlive:halloween
saturdaynightlive:thebestofadamsandler
saturdaynightlive:thebestofchrisfarley
saturdaynightlive:thebestofchriskattan
saturdaynightlive:thebestofchrisrock
saturdaynightlive:thebestofchristopherwalken
saturdaynightlive:thebestofdanaykroyd
saturdaynightlive:thebestofdanacarvey
saturdaynightlive:thebestofgildaradner
saturdaynightlive:thebestofjimmyfallon
saturdaynightlive:thebestofjohnbelushi
saturdaynightlive:thebestofjonlovitz
saturdaynightlive:thebestofmikemyers
saturdaynightlive:thebestofmollyshannon
saturdaynightlive:thebestofphilhartman
saturdaynightlive:thebestofstevemartin
saturdaynightlive:thebestoftomhanks
saturdaynightlive:thebestoftracymorgan
saturdaynightlive:thebestofwillferrell
saturn3
saudadedofuturo
saudiarabiauncovered
savagebeauty
savagegarden:superstarsandcannonballs:liveandontourinaustralia
savagegarden:thevideocollection
savagemessiah
savagerhythm
savethegreenplanet!
savethetiger
savedbythebell
savedbythebell:thecollegeyears
savedbythebell:thenewclass
saverioraimondo:ilsatiroparlante
savingcapitalism
savingprivateryan
savingsilverman
saviourofthesoul
sayanything
sayido
sayedtheservant
scarcity
scaretactics
scarecrowgonewild
scaredstraight!
scaredycats
scarefulwhatyouwishfor
scarletdiva
scarsofdracula
scarygodparents
scarymovie4
scarymovie5
scarystoriestotellinthedark
scenesfromamarriage
schitt'screek
schlock!thesecrethistoryofamericanmovies
schoollife
schoolofchocolate
schoolofrock
schoolties
school'sout
school'sout!themusical
schubertinlove
schultzegetstheblues
schulzsavesamerica
sci-fispecialfeature
scienceandtheswastika
scissorseven
scoobydoo,whereareyou!
scoobygoeshollywood
scooby-dooandthealieninvaders
scooby-dooandthecyberchase
scooby-dooandtheghoulschool
scooby-dooandthelegendofthevampire
scooby-dooandthelochnessmonster
scooby-dooandthemonsterofmexico
scooby-dooandthereluctantwerewolf
scooby-dooandthewitch'sghost
scooby-doomeetstheboobrothers
scooby-dooonzombieisland
scooby-doo!winterwonderdog
scoretvseason1
score:ahockeymusical
scrappedprincess
scream:thetvseries
screwloose
sdgundamforce
sdu:sexdutiesunit
seapower
sealteam
sealteamseason1-tourofduty:settour
sealteamseason2-operation:puertorico
sealteam:season1-sealteamseasononedebriefing
seanceonawetafternoon
searchforasafecigarette
searchforthegreatsharks
searchparty
search:www
searchingforsheela
season1
season10
season2reunion
season3buildsintroducingmonstersubie-milsgarage
season4
seasonsinthesun
sebasti‚àö¬∞nmarcelowainraich
sebastianmaniscalco:stayhungry
sebastianmaniscalco:what'swrongwithpeople?
sebastianmaniscalco:whywouldyoudothat?
secondnature
secondskin
secondstring
secretagentselection:ww2
secretballot
secretcity
secretdiaryofacallgirl
secrethonor
secretlives:hiddenchildrenandtheirrescuersduringwwii
secretmagiccontrolagency
secretobsession
secretofsuccess
secretsuperstar
secretthings
secretwarinvietnam
secretobienguardado
secretsandlies
secretsinthehotspring
secretsofangels,demonsandmasons
secretsofgreatbritishcastles
secretsoflostempires:medievalsiege
secretsofsummer
secretsoftheheart
secretsofthesaqqaratomb
sedona'srule
seducingdoctorlewis
seducingmaarya
seespotrun
seethesea
seeyouyesterday
seeingallred
seekingaman
seetaaurgeeta
seidenrgveda
seismanos
selectionday
selenalive:thelastconcert
selena:theseries
selfmade:inspiredbythelifeofmadamc.j.walker
selfportrait
selfie69
sellingsunset
sellingtampa
selma,lord,selma
senbenimher‚âà√ºeyimsin
senioryear
senoraacero
senseandsensibility
senzo:murderofasoccerstar
separatebutequal
separatetables
septembersofshiraz
sergeantcribb,seriesii:waxwork
serialkillerwithpiersmorgan
serialkillers:profilingthecriminalmind
serialkilling4dummys
series1grandfinal
seriousmen
seriouslysingle
servantofthepeople
servantofthepeople2
servantsoftwilight
sesamestreet
sesamestreetpresents:thestreetweliveon
sesamestreet:acelebrationofme,grover
sesamestreet:beinggreen
sesamestreet:cinderelmo
sesamestreet:cookiemonster'sbestbites
sesamestreet:dothealphabet
sesamestreet:elmosaveschristmas
sesamestreet:elmo'ssing-alongguessinggame
sesamestreet:elmo'sworld-allaboutanimals
sesamestreet:elmo'sworld-favoritethings
sesamestreet:fiesta!
sesamestreet:happyhealthymonsters
sesamestreet:kids'favoritesongs
sesamestreet:learningaboutletters
sesamestreet:learningaboutnumbers
sesamestreet:let'smakemusic!
sesamestreet:singalong
sesamestreet:singyourselfsilly!
sesamestreet:what'sthenameofthatsong?
session9
setitup
sethmeyers:lobbybaby
sethrogen'shilarityforcharity
sethumaayirampon
sevenbeauties
sevendialsmystery
sevensamurai
sevenseconds
sevensignsofchrist'sreturn
sevensoulsintheskullcastle
sevensundays
sevenyearsintibet
seventhson
sex&fury
sex&mrs.x
sexandluc‚àö‚â†a
sexandthebeauties
sexandthesinglegirl
sexat24framespersecond
sexeducation
sexinchains
sexiscomedy
sexwithstrangers
sex,explained
sex,love&goop
sex:unzipped
sexyanddangerous
sexybeast
sexybeasts
sexycentral
sgt.kabukimann.y.p.d.
shackleton'santarcticadventure
shadowandbone
shadowandbone-theafterparty
shadowbuilder
shadowofadoubt
shadowparties
shadowraiders
shadowhunters:season1stardustcompilation
shadowsandlight
shadowsrising:part2
shaftinafrica
shakazulu
shakeit
shakespeareinlove
shakespeare'sglobe:amidsummernight'sdream
shakira:liveandofftherecord
shallwedance
shamanking
shamelessseason3:anofficerandagallagher
shanghaiaffairs
shanghaifortress
shanghaighetto
shanghaigrand
shanghainoon
shanghaisurprise
shanghaitriad
shaniatwainspecial
shaniatwain:theplatinumcollection
shaolinyingxiongzhifengshi-yuhongzhi-guan
shaolininvinciblesticks
shaolinsoccer
shaolinulysses:kungfumonksinamerica
shaolinvs.evildead
shaolinwarrior
shaolin:wheeloflife
shapeofabear
sharkattack2
sharkattack3:megalodon
sharkskinmanandpeachhipgirl
sharkdog‚Äö√Ñ√¥sfintastichalloween
sharksofhawaii
sharky'smachine
sharonneedles:andywarholisdead
sharpe'sbattle
sharpe'scompany
sharpe'seagle
sharpe'senemy
sharpe'sgold
sharpe'shonour
sharpe'sjustice
sharpe'smission
sharpe'sregiment
sharpe'srevenge
sharpe'srifles:part1
sharpe'ssiege
sharpe'ssword
sharpe'swaterloo
shaunofthedead
shaunthesheep
shaunthesheep:adventuresfrommossybottom
shaunthesheep:thefarmer'sllamas
shaunthesheep:theflightbeforechristmas
shawnmendes:inwonder
shawnmendes:liveinconcert
shecreature
shefoughtalone
shegetswhatshewants
sheis
shekilledinecstasy
sheshootsstraight
shewouldneverknow
she-raandtheprincessesofpower
she,theultimateweapon
she'sallthat
she'sdatingthegangster
she'shavingababy
she'stooyoung
shepherdsandbutchers
sherlockholmes
sherlockholmesandpursuittoalgiers
sherlockholmesandthecaseofthesilkstocking
sherlockholmesandthepearlofdeath
sherlockholmes:agameofshadows
sherlockhound
sherman'smarch
sherylcrow:c'monamerica2003
sherylcrow:rockin'theglobelive
shimlamirchi
shimmerlake
shineyoureyes
shiningthrough
shinjukutriadsociety
shiny_flakes:theteenagedruglord
shivavsautobots
shiva:thesecretworldofvedascity
shobdojobdo
shockwaves
shootingfish
shootingwar:worldwariicombatcameramen
shootoutatlokhandwala
shorinthecity
short2:dreams
shortcuttonirvana:kumbhmela
shortcuts
shortdiversity5
shortshorts
shotcaller
shotinthedark
shotintheheart
shotsfiredspecialedition
showboat
showdogs
showmelove
showtime1958
shrekforeverafter
shrekthemusical
shriekifyouknowwhatididlastfridaythethirteenth
shubhaarambh
shufflingwiththebestofprimetime
shuranotoki:ageofchaos
shyamsingharoy
sidoelthemovie
sidoelthemovie2
sidoelthemovie3
sisabenc‚àö‚â•momepongo¬¨√∏pa'qu‚àö¬©meinvitan?
siamsunset
sicknote
sidandnancy
sidewalksofnewyork
sidneypoitier:onebrightlight
sierraburgessisaloser
sigaramthodu
sightings:heartlandghost
sigmundandtheseamonsters
silasamayangalil
silenceiswelcome
silentfall
silentmobius-case:titanic
silentservice
silentwarnings
sillukarupatti
silverhawk
silverliningsplaybook
silverskates
silvertonsiege
simisola:parttwo
simonamstell:setfree
simonandgarfunkel:oldfriends-liveonstage
simplementemanunna
sincity
sinsenoss‚àö‚â†haypara‚àö‚â†so
sinatra:allornothingatall
sinatra:theclassicduets
sinbad:afrosandbellbottoms
sinbad:nothin'butthefunk
sinbad:sonofapreacherman
sinceotarleft
sinceyou'vebeengone
sincerelyyours,dhaka
sing2
singasongofsixpants
singalongsongs:brotherbear-onmyway
singalongsongs:disneyprincess-onceuponadream
singalongsongs:singasongwithpoohbearandpiglettoo
singfaster:thestagehands'ringcycle
singon!
singon!germany
singon!spain
sing,dance,act:kabukifeaturingtomaikuta
singaporesocial
singlealltheway
singleslippersize-7
singlewhitefemale2:thepsycho
single‚Äö√Ñ√¥sinferno
singlesvilla
sinister2
sinkthebismarck!
sinsofthesisters
sir!nosir!
siriusthejaeger
sisterhelen
sistermysister
sisterprincess
sisterwendy'samericancollection
sister,sister
sistersofsin
sistersontrack
sittinginlimbo
sivaji:theboss
sixwaystosunday
sixwindowsinthedesert
six:themarkunleashed
skatergirl
skibum:thewarrenmillerstory
skimovie2:highsociety
skischool2
skindecision:beforeandafter
skinneddeep
skinnytigerandfattydragon
skippedparts
skycastle
skyhigh
skyladder:theartofcaiguo-qiang
skyrojo
skytour:themovie
skylandersacademy
slamdunkernest
slapshot2:breakingtheice
slaughterhigh
slaughterhousefive
slavegirlsfrombeyondinfinity
slaveryandthemakingofamerica
slavesoftherealm
slayer:stillreigning
slayer:waratthewarfield
slayersgorgeous
slayersgreat
slayerspremium
slayersreturn
slayers:excellent
slayers:thebookofspells
slayers:themotionpicture
sleepingwiththeenemy
sleeplessnights
sleeplesssocietynyctophobia
sleeplesstown
sleepovernightmare
slipknot:disasterpieces
slipknot:welcometoourneighborhood
slipperywhenwet
slumsofbeverlyhills
smallchange
smallchops
smallcrimes
smalltowncrime
smallerandsmallercircles
smallvilleseason3promo
smallville:thecompleteseriesretrospective
smashingpumpkins:vieuphoria
smileprecure!
smilesofasummernight
smiley'speople
smilingfish&goatonfire
smilla'ssenseofsnow
smoke&mirrors
smokersonly
smokeyjoe'scafereunion
smoothtalk
snabbacash
snakeandcraneartsofshaolin
snakeintheeagle'sshadow
snapdecision
snervoustyleroakley
sniper2
sniper3
sniper:ghostshooter
sniper:legacy
sniper:reloaded
snoopdogg'sf*cnaroundcomedyspecial
snowinaugust
snowqueen
snowwhiteandthehuntsman
snowwhiteandthesevendwarfs
snowflakemountain
snowyriver:themcgregorsaga
soclosetoparadise
somuchlovetogive
somygrandma'salesbian!
sonotworthit
soap:season2:episodes1-8
soccerdog:themovie
sochanatha
socialdistance
socialman
sof‚àö‚â†ani‚àö¬±oderivera:exposed
sof‚àö‚â†ani‚àö¬±oderivera:naturalselection
sofiathefirst
softhearts
sohnimahiwal
sohryuden:legendofthedragonkings
sollevante
soldierchild
soldieroforange
soldier'sgirl
soloelamor
solomon&gaenor
someassemblyrequired
somefolkscallitaslingblade
somelikeithot
somethingsneverchange
somebodyfeedphil
someday'sdreamers
someonegreat
someonehastodie
someonelikeyou
somethinghuge
somethingintherain
somethingthelordmade
something'sgottagive
sometimesinapril
sometimestheycomebackformore
sometimestheycomeback...again
somewherebetween
somewhereonlyweknow
sommore:chandelierstatus
sommore:thereigncontinues
sonofadam
sonofgod
sonofgodzilla
sonofpaleface
sonofthebeach
sonofthebride
sonofthesheik
sondheim:acelebrationatcarnegiehall
songexploder
songsfromthesecondfloor
songsfromtsongas:yes35thanniversaryconcert
sonicimpact
sonicthehedgehog:themovie
sonicx
sonsofthecaliphate
soo:revengeforatwistedfate
sophie:amurderinwestcork
sopranosunauthorized:shootingsitesuncovered
sorcererhunters
sorcerousstabberorphen
sorceryandchips
sorrytobotheryou
sorrytodisturb
soukbazaar
soulhunter
soulinthehole
soulofthegame
soulplane
soulsurfer
soulthieves
soundandfury

['crisscross', 'justintime', 'thegamechangers']

- จัดการตัวพิมพ์ใหญ่พิมพ์เล็ก ดังนี้
  - Title และ describtion ให้อิงจาก db ต้นฉบับ
  - Type จนถึง Composer ให้เป็น Title Letter ทั้งหมด (ใช้ title)

### Recycle bin

In [ ]:
def third_imdb(data, nlp):
  title_list, index_list = [], []
  id = data["id"]
  language = data["language"]
  country = data["production_country"]
  for i, lan, cty in zip(id, language, country):
    cdt_lan1 = "english" in list(lan) or "" in list(lan)
    cdt_lan2 = len(list(lan)) == 1
    cdt_cty1 = "united states" in list(cty) or "united kingdom" in list(cty) or "" in list(cty)
    cdt_cty2 = len(list(cty)) == 1 or len(list(cty)) == 2
    if (cdt_lan1 and cdt_lan2) and (cdt_cty1 and cdt_cty2):
      index_list.append(i)
  data = data[~data["id"].isin(index_list)]
  # for title in tqdm(data["title"]):
  #   doc = nlp(title)
  #   detect = doc._.language
  #   condition_1 = detect.get("language") != "en"
  #   condition_2 = detect.get("language") == "en" and detect.get("score") <= 0.5
  #   if condition_1 or condition_2:
  #     title_list.append(title)
  # return data[data["title"].isin(title_list)]
  check = data.drop_duplicates(subset=["actor", "director"])
  # check = data.drop_duplicates(subset=["actor", "type", "runtime", "director", "release_year"])
  merging = data.merge(check, indicator = True, how = 'outer')
  result = merging.loc[lambda x : x['_merge'] != 'both']
  return result

## Node and Relationship

### Nodes

In [ ]:
def main()

#### Entertainment Media Node

In [ ]:
def node_entertainment_media_test(media, user_ent):
  movie_list = user_ent["ent_id"].unique().tolist()
  media_test = media[media["ent_id"].isin(movie_list)].reset_index()
  media_test["index"] = media_test.index + 1
  media_test["index"] = media_test["index"].apply(lambda x: f"mov-{x}").astype(str)
  media_old = media_test.copy()
  media_test["ent_id"] = media_test["index"]
  media_test = media_test.drop("index", axis=1)
  return media_test, media_old
media_test, media_old = node_entertainment_media_test(media, user_ent)
media_old
# media_test.to_csv("node_entertainment_media_test.csv", index=False)

,index,ent_id,title,description,runtime,seasons,imdb_score,imdb_votes
0,mov-1,mov-100,The Talented Mr. Ripley,Tom Ripley is a calculating young man who beli...,139.0,NaN,7.4,207524.0
1,mov-2,mov-103,Titanic,101-year-old Rose DeWitt Bukater tells the sto...,194.0,NaN,7.9,1146825.0
2,mov-3,mov-10426,Return to Paradise,NaN,111.0,NaN,6.9,14257.0
3,mov-4,mov-10529,Clerks,NaN,22.0,NaN,7.4,12256.0
4,mov-5,mov-10850,The Return of the Living Dead,NaN,91.0,NaN,7.3,57501.0
...,...,...,...,...,...,...,...,...
300,mov-301,mov-9214,Dawn of the Dead,NaN,127.0,NaN,7.9,115624.0
301,mov-302,mov-9217,Cyborg,NaN,86.0,NaN,5.1,30394.0
302,mov-303,mov-9619,Beauty and the Beast,NaN,84.0,NaN,8.0,428088.0
303,mov-304,mov-964,Highway,"Right before her wedding, a young woman finds ...",133.0,NaN,7.6,28688.0
304,mov-305,mov-9846,The Longest Yard,NaN,113.0,NaN,6.4,169038.0

#### User Node

In [ ]:
def node_user_test(user, user_ent, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = user_ent["ent_id"].isin(movie_list)
  user1 = user_ent["user_id"][condition].unique().tolist()
  user_test = user[user["user_id"].isin(user1)].reset_index()
  user_test["index"] = user_test.index + 1
  user_test["index"] = user_test["index"].apply(lambda x: f"user-{x}").astype(str)
  user_old = user_test.copy()
  user_test["user_id"] = user_test["index"]
  user_test = user_test.drop("index", axis=1)
  return user_test, user_old
user_test, user_old = node_user_test(user, user_ent, media_old)
user_old
# user_test.to_csv("node_user_test.csv", index=False)

,index,user_id,name,email,phone number
0,user-1,user-1,Jacqueline Gonzalez,jamiemunoz@example.com,(815)448-7940x224
1,user-2,user-2,Katherine Beltran,jmunoz@example.net,606-374-3708x96800
2,user-3,user-3,Samantha Kent,grahamandre@example.com,677-391-3132x873
3,user-4,user-4,Renee Montgomery,sanderslaura@example.net,580.693.4656
4,user-5,user-5,Erin May,wheelereric@example.org,392.511.6381x9655
...,...,...,...,...,...
143451,user-143452,user-143454,Julia Gilmore,grant95@example.com,001-312-734-6427
143452,user-143453,user-143455,Brian Hudson,patrick70@example.com,530.829.4214x0516
143453,user-143454,user-143456,Maria Watkins,garywright@example.org,839.611.2497
143454,user-143455,user-143457,Kathryn Murphy,ejones@example.net,+1-780-850-5627
143455,user-143456,user-143458,Julie Cruz,colleenjones@example.net,710.656.9714

#### Director Node

In [ ]:
def node_director_test(director, dir_ent, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = dir_ent["ent_id"].isin(movie_list)
  director1 = dir_ent["dir_id"][condition].unique().tolist()
  director_test = director[director["dir_id"].isin(director1)].reset_index()
  director_test["index"] = director_test.index + 1
  director_test["index"] = director_test["index"].apply(lambda x: f"dir-{x}").astype(str)
  director_old = director_test.copy()
  director_test["dir_id"] = director_test["index"]
  director_test = director_test.drop("index", axis=1)
  return director_test, director_old
director_test, director_old = node_director_test(director, dir_ent, media_old)
director_test
# director_test.to_csv("node_director_test.csv", index=False)

      dir_id                 name
0      dir-1        Albert Hughes
1      dir-2         Allen Hughes
2      dir-3       Alan J. Pakula
3      dir-4          Mike Hodges
4      dir-5        Donald Petrie
..       ...                  ...
266  dir-267         Hideaki Anno
267  dir-268     Kazuya Tsurumaki
268  dir-269         Stuart Baird
269  dir-270  Jean-Jacques Annaud
270  dir-271      Eduardo Roy Jr.

[271 rows x 2 columns]

#### Actor Node

In [ ]:
def node_actor_test(actor, ent_act, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_act["ent_id"].isin(movie_list)
  actor1 = ent_act["act_id"][condition].unique().tolist()
  actor_test = actor[actor["act_id"].isin(actor1)].reset_index()
  actor_test["index"] = actor_test.index + 1
  actor_test["index"] = actor_test["index"].apply(lambda x: f"act-{x}").astype(str)
  actor_old = actor_test.copy()
  actor_test["act_id"] = actor_test["index"]
  actor_test = actor_test.drop("index", axis=1)
  return actor_test, actor_old
actor_test, actor_old = node_actor_test(actor, ent_act, media_old)
actor_old
# actor_test.to_csv("node_actor_test.csv", index=False)

           index     act_id                     name
0          act-1  act-10018            Aaron Eckhart
1          act-2   act-1003              Chevy Chase
2          act-3  act-10033                    LeJon
3          act-4   act-1004         Beverly D'Angelo
4          act-5  act-10041  Tiffany Sander McKenzie
...          ...        ...                      ...
12057  act-12058   act-9950         Nestor Carbonell
12058  act-12059   act-9953                Tom Conti
12059  act-12060   act-9968                Rob Brown
12060  act-12061   act-9973       David Dayan Fisher
12061  act-12062   act-9981            Robert Wisdom

[12062 rows x 3 columns]

#### Age Certificate Node

In [ ]:
def node_age_certification_test(age, ent_age, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_age["ent_id"].isin(movie_list)
  age1 = ent_age["age_id"][condition].unique().tolist()
  age_test = age[age["age_id"].isin(age1)].reset_index()
  age_test["index"] = age_test.index + 1
  age_test["index"] = age_test["index"].apply(lambda x: f"age-{x}").astype(str)
  age_old = age_test.copy()
  age_test["age_id"] = age_test["index"]
  age_test = age_test.drop("index", axis=1)
  return age_test, age_old
age_test, age_old = node_age_certification_test(age, ent_age, media_old)
age_old
# age_test.to_csv("node_age_certification_test.csv", index=False)

   index  age_id age_certification
0  age-1   age-1                 G
1  age-2  age-11             TV-Y7
2  age-3   age-3                PG
3  age-4   age-4             PG-13
4  age-5   age-5                 R
5  age-6   age-6             TV-14
6  age-7   age-8             TV-MA
7  age-8   age-9             TV-PG

#### Character Node

In [ ]:
def node_character_test(character, ent_cha, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_cha["ent_id"].isin(movie_list)
  character1 = ent_cha["role_id"][condition].unique().tolist()
  character_test = character[character["role_id"].isin(character1)].reset_index()
  character_test["index"] = character_test.index + 1
  character_test["index"] = character_test["index"].apply(lambda x: f"cha-{x}").astype(str)
  character_old = character_test.copy()
  character_test["role_id"] = character_test["index"]
  character_test = character_test.drop("index", axis=1)
  return character_test, character_old
character_test, character_old = node_character_test(character, ent_cha, media_old)
character_old
# character_test.to_csv("node_character_test.csv", index=False)

         index    role_id                  name
0        cha-1  cha-14762    Lin Bao Zhu (2011)
1        cha-2  cha-14763  Wang Jia Zhen (2011)
2        cha-3  cha-14764  Xiao Jian Hai (2011)
3        cha-4  cha-14765    Yan Qiu Hua (2011)
4        cha-5  cha-14766      Liang Xin (2011)
...        ...        ...                   ...
1801  cha-1802   cha-8886            Tasha Mack
1802  cha-1803   cha-8887          Malik Wright
1803  cha-1804   cha-8888        Keira Whitaker
1804  cha-1805   cha-8889            Chardonnay
1805  cha-1806   cha-8890       Bryce Westbrook

[1806 rows x 3 columns]

#### Genre Node

In [ ]:
def node_genre_test(genre, ent_gen, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_gen["ent_id"].isin(movie_list)
  genre1 = ent_gen["gen_id"][condition].unique().tolist()
  genre_test = genre[genre["gen_id"].isin(genre1)].reset_index()
  genre_test["index"] = genre_test.index + 1
  genre_test["index"] = genre_test["index"].apply(lambda x: f"gen-{x}").astype(str)
  genre_old = genre_test.copy()
  genre_test["gen_id"] = genre_test["index"]
  genre_test = genre_test.drop("index", axis=1)
  return genre_test, genre_old
genre_test, genre_old = node_genre_test(genre, ent_gen, media_old)
genre_old
# genre_test.to_csv("node_genre_test.csv", index=False)

     index  gen_id         genres
0    gen-1   gen-1  documentation
1    gen-2  gen-10        romance
2    gen-3  gen-11        western
3    gen-4  gen-12        history
4    gen-5  gen-13          music
5    gen-6  gen-14         family
6    gen-7  gen-15         horror
7    gen-8  gen-16         sci-fi
8    gen-9  gen-17      animation
9   gen-10  gen-18        reality
10  gen-11  gen-19          sport
11  gen-12   gen-2          drama
12  gen-13  gen-20    documentary
13  gen-14  gen-21        mystery
14  gen-15  gen-23      adventure
15  gen-16  gen-24        musical
16  gen-17  gen-25          short
17  gen-18  gen-26      biography
18  gen-19  gen-29      film-noir
19  gen-20   gen-3          crime
20  gen-21   gen-4         action
21  gen-22   gen-5       thriller
22  gen-23   gen-6       european
23  gen-24   gen-7        fantasy
24  gen-25   gen-8         comedy
25  gen-26   gen-9            war

#### Language Node

In [ ]:
def node_language_test(language, ent_lang, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_lang["ent_id"].isin(movie_list)
  language1 = ent_lang["lang_id"][condition].unique().tolist()
  language_test = language[language["lang_id"].isin(language1)].reset_index()
  language_test["index"] = language_test.index + 1
  language_test["index"] = language_test["index"].apply(lambda x: f"lang-{x}").astype(str)
  language_old = language_test.copy()
  language_test["lang_id"] = language_test["index"]
  language_test = language_test.drop("index", axis=1)
  return language_test, language_old
language_test, language_old = node_language_test(language, ent_lang, media_old)
language_old
# language_test.to_csv("node_language_test.csv", index=False)

      index   lang_id                  language
0    lang-1    lang-1                   English
1    lang-2   lang-10                      Thai
2    lang-3   lang-11                  Mandarin
3    lang-4   lang-12                    Arabic
4    lang-5   lang-13                    Hebrew
5    lang-6   lang-15                   Italian
6    lang-7  lang-151          Apache languages
7    lang-8   lang-16                   Chinese
8    lang-9   lang-18                   Kurdish
9   lang-10    lang-2                  Japanese
10  lang-11   lang-21                    Polish
11  lang-12   lang-22                   Turkish
12  lang-13   lang-23                Aboriginal
13  lang-14   lang-24                   Swedish
14  lang-15   lang-25                      None
15  lang-16   lang-27                     Latin
16  lang-17   lang-28     British Sign Language
17  lang-18   lang-29              Shanghainese
18  lang-19    lang-3                    German
19  lang-20   lang-30                    Danish
20  lang-21   lang-31                Vietnamese
21  lang-22   lang-33                 Mongolian
22  lang-23   lang-34                   Klingon
23  lang-24   lang-35                     Greek
24  lang-25   lang-37                  Armenian
25  lang-26    lang-4                   Spanish
26  lang-27   lang-40                   Tagalog
27  lang-28   lang-44                     Maori
28  lang-29   lang-45                    Korean
29  lang-30   lang-49    American Sign Language
30  lang-31    lang-5                   Russian
31  lang-32   lang-51  Greek, Ancient (to 1453)
32  lang-33   lang-53                   Serbian
33  lang-34    lang-6                     Hindi
34  lang-35   lang-64                     Sioux
35  lang-36    lang-7                    French
36  lang-37   lang-70                   Yiddish
37  lang-38   lang-71                    Romany
38  lang-39   lang-72                  Romanian
39  lang-40    lang-8                Portuguese
40  lang-41   lang-80                   Finnish
41  lang-42   lang-82                      Cree
42  lang-43   lang-83                   Quechua
43  lang-44   lang-84                Mapudungun
44  lang-45   lang-85                 Bulgarian
45  lang-46   lang-88                  Croatian
46  lang-47    lang-9                 Cantonese
47  lang-48   lang-91                   Aramaic
48  lang-49   lang-93                   Scanian

#### Production Country Node

In [ ]:
def node_production_country_test(country, ent_prod, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_prod["ent_id"].isin(movie_list)
  country1 = ent_prod["country_id"][condition].unique().tolist()
  country_test = country[country["country_id"].isin(country1)].reset_index()
  country_test["index"] = country_test.index + 1
  country_test["index"] = country_test["index"].apply(lambda x: f"country-{x}").astype(str)
  country_old = country_test.copy()
  country_test["country_id"] = country_test["index"]
  country_test = country_test.drop("index", axis=1)
  return country_test, country_old
country_test, country_old = node_production_country_test(country, ent_prod, media_old)
country_old
# country_test.to_csv("node_production_country_test.csv", index=False)

         index   country_id            name
0    country-1    country-1   United States
1    country-2   country-10         Algeria
2    country-3   country-11           Italy
3    country-4  country-111    West Germany
4    country-5  country-113         Czechia
5    country-6  country-117     South Korea
6    country-7   country-12           Japan
7    country-8   country-13       Argentina
8    country-9   country-14            Peru
9   country-10   country-15          Brazil
10  country-11   country-16         Ireland
11  country-12   country-17       Hong Kong
12  country-13   country-18       Australia
13  country-14    country-2  United Kingdom
14  country-15   country-21          Mexico
15  country-16   country-22           Spain
16  country-17   country-23        Colombia
17  country-18   country-25          Norway
18  country-19   country-26         Belgium
19  country-20   country-27          Turkey
20  country-21   country-28         Denmark
21  country-22    country-3           Egypt
22  country-23   country-33           China
23  country-24   country-34        Bulgaria
24  country-25   country-35          Russia
25  country-26   country-36           Korea
26  country-27   country-37           Chile
27  country-28    country-4         Germany
28  country-29   country-41          Sweden
29  country-30   country-42          Taiwan
30  country-31   country-43       Singapore
31  country-32   country-46     Switzerland
32  country-33   country-47     Philippines
33  country-34    country-5           India
34  country-35   country-52         Hungary
35  country-36   country-58          Poland
36  country-37    country-6    Soviet Union
37  country-38   country-60         Romania
38  country-39   country-62         Ukraine
39  country-40   country-63     New Zealand
40  country-41   country-75         Vietnam
41  country-42   country-77            Iraq
42  country-43   country-78        Thailand
43  country-44    country-8          Canada
44  country-45    country-9          France

#### Release Year Node

In [ ]:
def node_release_year_test(year, ent_year, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_year["ent_id"].isin(movie_list)
  year1 = ent_year["year_id"][condition].unique().tolist()
  year_test = year[year["year_id"].isin(year1)].reset_index()
  year_test["index"] = year_test.index + 1
  year_test["index"] = year_test["index"].apply(lambda x: f"year-{x}").astype(str)
  year_old = year_test.copy()
  year_test["year_id"] = year_test["index"]
  year_test = year_test.drop("index", axis=1)
  return year_test, year_old
year_test, year_old = node_release_year_test(year, ent_year, media_old)
year_old
# year_test.to_csv("node_release_year_test.csv", index=False)

      index    year_id  year
0    year-1  year-1925  1925
1    year-2  year-1946  1946
2    year-3  year-1949  1949
3    year-4  year-1951  1951
4    year-5  year-1954  1954
..      ...        ...   ...
60  year-61  year-2018  2018
61  year-62  year-2019  2019
62  year-63  year-2020  2020
63  year-64  year-2021  2021
64  year-65  year-2022  2022

[65 rows x 3 columns]

#### Type Node

In [ ]:
def node_type_test(tpe, ent_type, media_old):
  movie_list = media_old["ent_id"].unique().tolist()
  condition = ent_type["ent_id"].isin(movie_list)
  type1 = ent_type["type_id"][condition].unique().tolist()
  type_test = tpe[tpe["type_id"].isin(type1)].reset_index()
  type_test["index"] = type_test.index + 1
  type_test["index"] = type_test["index"].apply(lambda x: f"type-{x}").astype(str)
  type_old = type_test.copy()
  type_test["type_id"] = type_test["index"]
  type_test = type_test.drop("index", axis=1)
  return type_test, type_old
type_test, type_old = node_type_test(tpe, ent_type, media_old)
type_old
# type_test.to_csv("node_type_test.csv", index=False)

    index type_id      type
0  type-1  type-1     movie
1  type-2  type-2    series
2  type-3  type-3      show
3  type-4  type-4  tv short

### Relationships

#### Relationship Between Actor Node and Character Node

In [ ]:
def actor_node_and_character_node(character_old, actor_old, act_cha):
  act_cha_test = act_cha.merge(character_old, left_on="role_id",
                                    right_on="role_id")
  act_cha_test["role_id"] = act_cha_test["index"]
  act_cha_test = act_cha_test.drop(["index", "name"], axis=1)
  act_cha_test = act_cha_test.merge(actor_old, left_on="act_id",
                                    right_on="act_id")
  act_cha_test["act_id"] = act_cha_test["index"]
  act_cha_test = act_cha_test.drop(["index", "name"], axis=1)
  return act_cha_test

act_cha_test = actor_node_and_character_node(character_old, actor_old, cha_act)
act_cha_test
# act_cha_test.to_csv("actor_character_test.csv", index=False)

        act_id   role_id
0     act-2545  cha-1534
1     act-1233   cha-131
2     act-1773   cha-119
3     act-2190   cha-397
4     act-2190  cha-1407
...        ...       ...
1801  act-3988  cha-1629
1802  act-3989  cha-1630
1803  act-3991  cha-1631
1804  act-3992  cha-1632
1805  act-3993  cha-1634

[1806 rows x 2 columns]

#### Relationship Between Director Node and Actor Node

In [ ]:
def director_node_and_actor_node(director_old, actor_old, dir_act):
  dir_act_test = dir_act.merge(director_old, left_on="dir_id",
                                    right_on="dir_id")
  dir_act_test["dir_id"] = dir_act_test["index"]
  dir_act_test = dir_act_test.drop(["index", "name"], axis=1)
  dir_act_test = dir_act_test.merge(actor_old, left_on="act_id",
                                    right_on="act_id")
  dir_act_test["act_id"] = dir_act_test["index"]
  dir_act_test = dir_act_test.drop(["index", "name"], axis=1)
  return dir_act_test

dir_act_test = director_node_and_actor_node(director_old, actor_old, dir_act)
dir_act_test
# dir_act_test.to_csv("director_actor_test.csv", index=False)

       act_id   dir_id
0    act-5592  dir-112
1    act-1945  dir-253
2    act-2171  dir-149
3    act-3482   dir-26
4    act-3530  dir-254
5    act-7920  dir-106
6     act-504   dir-83
7     act-899  dir-127
8     act-900  dir-160
9    act-2234  dir-157
10   act-2249   dir-55
11   act-3043  dir-189
12   act-3460   dir-50
13   act-3871  dir-209
14   act-4160  dir-164
15   act-4358   dir-73
16   act-4704   dir-78
17   act-4733  dir-257
18   act-5696  dir-101
19   act-5966  dir-185
20   act-6220  dir-104
21   act-6445  dir-119
22   act-6733  dir-140
23   act-6760  dir-126
24   act-7001  dir-130
25   act-7247  dir-135
26   act-7428  dir-142
27   act-7919  dir-116
28   act-8385   dir-68
29   act-8422  dir-159
30   act-8457  dir-240
31   act-8677  dir-241
32   act-8880  dir-168
33   act-9409  dir-173
34   act-9428  dir-174
35   act-9456  dir-175
36   act-9962  dir-186
37  act-10045  dir-187
38  act-10046  dir-188
39  act-10198  dir-194
40  act-10803  dir-204
41  act-10804  dir-203
42  act-10807  dir-256
43  act-11521  dir-219
44    act-508  dir-266
45    act-574  dir-247
46    act-949  dir-249

#### Relationship Between Director Node and Entertainment Media Node

In [ ]:
def director_node_and_media_node(director_old, media_old, dir_ent):
  dir_ent_test = dir_ent.merge(director_old, left_on="dir_id",
                                    right_on="dir_id")
  dir_ent_test["dir_id"] = dir_ent_test["index"]
  dir_ent_test = dir_ent_test.drop(["index", "name"], axis=1)
  dir_ent_test = dir_ent_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  dir_ent_test["ent_id"] = dir_ent_test["index"]
  dir_ent_test = dir_ent_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return dir_ent_test

dir_ent_test = director_node_and_media_node(director_old, media_old, dir_ent)
dir_ent_test
# dir_ent_test.to_csv("director_media_test.csv", index=False)

      dir_id   ent_id
0    dir-112  mov-253
1    dir-263  mov-300
2     dir-44  mov-212
3     dir-48   mov-69
4    dir-234  mov-280
..       ...      ...
289  dir-258   mov-23
290  dir-258   mov-24
291  dir-259   mov-20
292  dir-260   mov-25
293  dir-261   mov-25

[294 rows x 2 columns]

#### Relationship Between Entertainment Media Node and Actor Node

In [ ]:
def media_node_and_actor_node(actor_old, media_old, ent_act):
  ent_act_test = ent_act.merge(actor_old, left_on="act_id",
                                    right_on="act_id")
  ent_act_test["act_id"] = ent_act_test["index"]
  ent_act_test = ent_act_test.drop(["index", "name"], axis=1)
  ent_act_test = ent_act_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_act_test["ent_id"] = ent_act_test["index"]
  ent_act_test = ent_act_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_act_test

ent_act_test = media_node_and_actor_node(actor_old, media_old, ent_act)
ent_act_test
# ent_act_test.to_csv("media_actor_test.csv", index=False)

          act_id   ent_id
0       act-3109  mov-142
1       act-3197  mov-142
2       act-3357  mov-142
3       act-3456  mov-142
4      act-12059  mov-142
...          ...      ...
12798  act-10605  mov-248
12799  act-10606  mov-248
12800  act-10607  mov-248
12801  act-10608  mov-248
12802  act-10609  mov-248

[12803 rows x 2 columns]

#### Relationship Between Entertainment Media Node and Age Certification Node

In [ ]:
def media_node_and_age_node(age_old, media_old, ent_age):
  ent_age_test = ent_age.merge(age_old, left_on="age_id",
                                    right_on="age_id")
  ent_age_test["age_id"] = ent_age_test["index"]
  ent_age_test = ent_age_test.drop(["index", "age_certification"], axis=1)
  ent_age_test = ent_age_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_age_test["ent_id"] = ent_age_test["index"]
  ent_age_test = ent_age_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_age_test

ent_age_test = media_node_and_age_node(age_old, media_old, ent_age)
ent_age_test
# ent_age_test.to_csv("media_age_test.csv", index=False)

     ent_id age_id
0    mov-42  age-7
1    mov-46  age-7
2    mov-56  age-7
3    mov-58  age-7
4    mov-59  age-7
5    mov-62  age-7
6    mov-65  age-7
7    mov-76  age-7
8    mov-69  age-5
9     mov-1  age-5
10    mov-9  age-5
11   mov-36  age-5
12   mov-37  age-5
13   mov-39  age-5
14   mov-49  age-5
15   mov-51  age-5
16   mov-52  age-5
17   mov-53  age-5
18   mov-55  age-5
19   mov-57  age-5
20   mov-61  age-5
21   mov-74  age-5
22   mov-79  age-5
23   mov-81  age-5
24   mov-83  age-5
25   mov-84  age-5
26   mov-86  age-5
27   mov-88  age-5
28   mov-43  age-3
29   mov-50  age-3
30   mov-72  age-3
31   mov-78  age-3
32   mov-80  age-3
33   mov-82  age-3
34   mov-89  age-3
35   mov-47  age-6
36   mov-66  age-6
37   mov-90  age-6
38  mov-296  age-6
39   mov-67  age-6
40    mov-2  age-4
41   mov-26  age-4
42   mov-38  age-4
43   mov-45  age-4
44   mov-54  age-4
45   mov-64  age-4
46  mov-304  age-4
47   mov-48  age-4
48   mov-85  age-4
49   mov-87  age-4
50   mov-30  age-8
51   mov-75  age-2
52   mov-63  age-1

#### Relationship Between Entertainment Media Node and Character Node

In [ ]:
def media_node_and_character_node(character_old, media_old, ent_cha):
  ent_cha_test = ent_cha.merge(character_old, left_on="role_id",
                                    right_on="role_id")
  ent_cha_test["role_id"] = ent_cha_test["index"]
  ent_cha_test = ent_cha_test.drop(["index", "name"], axis=1)
  ent_cha_test = ent_cha_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_cha_test["ent_id"] = ent_cha_test["index"]
  ent_cha_test = ent_cha_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_cha_test

ent_cha_test = media_node_and_character_node(character_old, media_old, ent_cha)
ent_cha_test
# ent_cha_test.to_csv("media_character_test.csv", index=False)

      ent_id   role_id
0     mov-69  cha-1731
1     mov-69  cha-1732
2     mov-69  cha-1733
3     mov-69  cha-1734
4     mov-69  cha-1735
...      ...       ...
1801  mov-89  cha-1630
1802  mov-89  cha-1631
1803  mov-89  cha-1632
1804  mov-89  cha-1633
1805  mov-89  cha-1634

[1806 rows x 2 columns]

#### Relationship Between Entertainment Media Node and Genre Node

In [ ]:
def media_node_and_genre_node(genre_old, media_old, ent_gen):
  ent_gen_test = ent_gen.merge(genre_old, left_on="gen_id",
                                    right_on="gen_id")
  ent_gen_test["gen_id"] = ent_gen_test["index"]
  ent_gen_test = ent_gen_test.drop(["index", "genres"], axis=1)
  ent_gen_test = ent_gen_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_gen_test["ent_id"] = ent_gen_test["index"]
  ent_gen_test = ent_gen_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_gen_test

ent_gen_test = media_node_and_genre_node(genre_old, media_old, ent_gen)
ent_gen_test
# ent_gen_test.to_csv("media_genre_test.csv", index=False)

      ent_id  gen_id
0     mov-49   gen-1
1     mov-49  gen-12
2     mov-49  gen-20
3     mov-49  gen-22
4     mov-61   gen-1
..       ...     ...
893  mov-271  gen-13
894  mov-274  gen-13
895  mov-289  gen-13
896  mov-289  gen-18
897  mov-163  gen-15

[898 rows x 2 columns]

#### Relationship Between Entertainment Media Node and Language Node

In [ ]:
def media_node_and_language_node(language_old, media_old, ent_lang):
  ent_lang_test = ent_lang.merge(language_old, left_on="lang_id",
                                    right_on="lang_id")
  ent_lang_test["lang_id"] = ent_lang_test["index"]
  ent_lang_test = ent_lang_test.drop(["index", "language"], axis=1)
  ent_lang_test = ent_lang_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_lang_test["ent_id"] = ent_lang_test["index"]
  ent_lang_test = ent_lang_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_lang_test

ent_lang_test = media_node_and_language_node(language_old, media_old, ent_lang)
ent_lang_test
# ent_lang_test.to_csv("media_language_test.csv", index=False)

      ent_id  lang_id
0     mov-92   lang-1
1     mov-93   lang-1
2     mov-95   lang-1
3     mov-98   lang-1
4     mov-99   lang-1
..       ...      ...
378  mov-290  lang-41
379  mov-290  lang-49
380  mov-208  lang-21
381  mov-170  lang-29
382  mov-263  lang-29

[383 rows x 2 columns]

#### Relationship Between Entertainment Media Node and Production Country Node

In [ ]:
def media_node_and_country_node(country_old, media_old, ent_prod):
  ent_prod_test = ent_prod.merge(country_old, left_on="country_id",
                                    right_on="country_id")
  ent_prod_test["country_id"] = ent_prod_test["index"]
  ent_prod_test = ent_prod_test.drop(["index", "name"], axis=1)
  ent_prod_test = ent_prod_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_prod_test["ent_id"] = ent_prod_test["index"]
  ent_prod_test = ent_prod_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_prod_test

ent_prod_test = media_node_and_country_node(country_old, media_old, ent_prod)
ent_prod_test
# ent_prod_test.to_csv("media_country_test.csv", index=False)

      ent_id  country_id
0     mov-69   country-1
1     mov-69  country-14
2      mov-1   country-1
3      mov-2   country-1
4      mov-9   country-1
..       ...         ...
444   mov-74  country-40
445   mov-65  country-43
446  mov-125   country-4
447  mov-170   country-6
448  mov-263   country-6

[449 rows x 2 columns]

#### Relationship Between Entertainment Media Node and Release Year Node

In [ ]:
def media_node_and_year_node(year_old, media_old, ent_year):
  ent_year_test = ent_year.merge(year_old, left_on="year_id",
                                    right_on="year_id")
  ent_year_test["year_id"] = ent_year_test["index"]
  ent_year_test = ent_year_test.drop(["index", "year"], axis=1)
  ent_year_test = ent_year_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_year_test["ent_id"] = ent_year_test["index"]
  ent_year_test = ent_year_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_year_test

ent_year_test = media_node_and_year_node(year_old, media_old, ent_year)
ent_year_test
# ent_year_test.to_csv("media_year_test.csv", index=False)

      ent_id  year_id
0    mov-105  year-23
1    mov-245  year-19
2    mov-135  year-22
3    mov-156  year-22
4    mov-115  year-17
..       ...      ...
300  mov-283   year-3
301  mov-229   year-8
302  mov-182  year-18
303   mov-11   year-2
304  mov-282   year-1

[305 rows x 2 columns]

#### Relationship Between Entertainment Media Node and Type Node

In [ ]:
def media_node_and_type_node(type_old, media_old, ent_type):
  ent_type_test = ent_type.merge(type_old, left_on="type_id",
                                    right_on="type_id")
  ent_type_test["type_id"] = ent_type_test["index"]
  ent_type_test = ent_type_test.drop(["index", "type"], axis=1)
  ent_type_test = ent_type_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  ent_type_test["ent_id"] = ent_type_test["index"]
  ent_type_test = ent_type_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return ent_type_test

ent_type_test = media_node_and_type_node(type_old, media_old, ent_type)
ent_type_test
# ent_type_test.to_csv("media_type_test.csv", index=False)

      ent_id type_id
0      mov-2  type-2
1     mov-36  type-2
2     mov-55  type-2
3    mov-304  type-2
4     mov-74  type-2
..       ...     ...
300  mov-305  type-3
301    mov-5  type-3
302    mov-8  type-3
303   mov-11  type-3
304   mov-35  type-3

[305 rows x 2 columns]

#### Relationship Between User Node and User Node

In [ ]:
def user_node_and_user_node(user_old, user_friend):
  user_friend_test = user_friend.merge(user_old, left_on="user_id",
                                    right_on="user_id")
  user_friend_test["user_id"] = user_friend_test["index"]
  user_friend_test = user_friend_test.drop(["index", "name", "email",
                                            "phone number"], axis=1)
  user_friend_test = user_friend_test.merge(user_old, left_on="friend_id",
                                    right_on="user_id")
  user_friend_test["friend_id"] = user_friend_test["index"]
  user_friend_test = user_friend_test.drop(["index", "user_id_y", "name",
                                            "email", "phone number"], axis=1)
  user_friend_test.rename(columns={"user_id_x": "user_id"}, inplace=True)
  return user_friend_test

user_friend_test = user_node_and_user_node(user_old, user_friend)
user_friend_test
user_friend_test.to_csv("user_friend_test.csv", index=False)

#### Relationship Between User Node and Entertainment Media Node

In [ ]:
def user_node_and_media_node(user_old, media_old, user_ent):
  user_ent_test = user_ent.merge(user_old, left_on="user_id",
                                    right_on="user_id")
  user_ent_test["user_id"] = user_ent_test["index"]
  user_ent_test = user_ent_test.drop(["index", "name", "email",
                                      "phone number"], axis=1)
  user_ent_test = user_ent_test.merge(media_old, left_on="ent_id",
                                    right_on="ent_id")
  user_ent_test["ent_id"] = user_ent_test["index"]
  user_ent_test = user_ent_test.drop(["index", "title", "description", "runtime",
                                    "seasons", "imdb_score", "imdb_votes"],
                                   axis=1)
  return user_ent_test

user_ent_test = user_node_and_media_node(user_old, media_old, user_ent)
user_ent_test
# user_ent_test.to_csv("user_media_test.csv", index=False)

             user_id  user_rating   ent_id
0             user-1            3   mov-54
1             user-2            5   mov-54
2             user-3            3   mov-54
3             user-7            4   mov-54
4             user-8            3   mov-54
...              ...          ...      ...
3468254  user-142684            4  mov-271
3468255  user-142720            3  mov-271
3468256  user-142835            4  mov-271
3468257  user-142962            4  mov-271
3468258  user-143024            4  mov-271

[3468259 rows x 3 columns]

### Seperate File Zone

In [ ]:
# Read and EDA CSV file
dfs = pd.read_csv("/content/relationship_user_movie.csv", encoding="utf-8")
dfs

             user_id  user_rating     ent_id
0             user-1            3    mov-282
1             user-1            2   mov-6232
2             user-1            3  mov-10529
3             user-1            3   mov-6503
4             user-1            3   mov-6529
...              ...          ...        ...
3468254  user-143458            5   mov-9846
3468255  user-143458            5   mov-5916
3468256  user-143458            3   mov-2090
3468257  user-143458            4  mov-13483
3468258  user-143458            4    mov-254

[3468259 rows x 3 columns]

In [ ]:
# Seperate file using number of row
def seperate_file_1(data):
  count = 0
  prob = 1000000
  for i in range(4):
    if i == 3:
      newdata = data.iloc[count:data.shape[0]]
    else:
      newdata = data.iloc[count:prob]
      count += 1000000
      prob += 1000000
    newdata.to_csv("relationship_user_movie_%d.csv" % (i+1), index=False)
seperate_file_1(dfs)

In [ ]:
# Seperate file using id
def seperate_file_2(data):
  movie_id = data["ent_id"].unique().tolist()
  start = 0
  end = 0
  df = pd.DataFrame()
  for i in range(4):
    if i == 3:
      start = data.shape[0]-end
      end = data.shape[0]
    else:
      start += end
      end += 3674
    temp = movie_id[start:end]
    for j in tqdm(temp):
      result = pd.DataFrame(actor[actor["ent_id"] == j].values.tolist())
      pd.concat([df, result], ignore_index=True)
    df.to_csv("relationship_movie_actor_%d.csv" % (i+1), index=False)
seperate_file_2(dfs)

### Recheck Zone

In [ ]:
# Read and EDA CSV file
recheck = pd.read_csv("/content/relationship_entertainment_user.csv")
recheck

           user_id  user_rating    ent_id
0           user-1            3  mov-7580
1           user-1            2  mov-7934
2           user-1            3   mov-964
3           user-1            3  mov-5749
4           user-1            3  mov-6679
...            ...          ...       ...
238081  user-10000            3  mov-6541
238082  user-10000            3  mov-6468
238083  user-10000            3  mov-2253
238084  user-10000            4  mov-6433
238085  user-10000            4  mov-2253

[238086 rows x 3 columns]

In [ ]:
def check_duplicate_value(data):
  duplicate = data[data.duplicated(["user_id", "ent_id"])]
  return duplicate
result = check_duplicate_value(recheck)
display = recheck.drop_duplicates(subset=["user_id", "ent_id"])
display.to_csv("data1.csv", index=False)

In [ ]:
def check_duplicate_value(data):
  result = []
  start_id = data["ent_id"].unique().tolist()
  for i in tqdm(start_id):
    temp = data["user_id"][data["ent_id"] == i].values.tolist()
    for j in temp:
      if temp.count(j) > 1:
        result.append(j)
  result = set(result)
  return result
result = check_duplicate_value(recheck)
result

100%|██████████| 305/305 [00:12<00:00, 23.62it/s]

{'user-2661',
 'user-620',
 'user-5896',
 'user-5221',
 'user-1809',
 'user-9112',
 'user-388',
 'user-135',
 'user-3690',
 'user-327',
 'user-5866',
 'user-5765',
 'user-200',
 'user-3732',
 'user-3218',
 'user-3454',
 'user-77',
 'user-9040',
 'user-3068',
 'user-10000',
 'user-6867',
 'user-9189',
 'user-9168',
 'user-1282',
 'user-3291',
 'user-462',
 'user-6753',
 'user-3667',
 'user-8233',
 'user-8052',
 'user-3543',
 'user-1198',
 'user-8660',
 'user-6600',
 'user-3858',
 'user-5990',
 'user-6658',
 'user-6881',
 'user-8275',
 'user-3124',
 'user-5424',
 'user-245',
 'user-6259',
 'user-3778',
 'user-3211',
 'user-6455',
 'user-8595',
 'user-337',
 'user-3602',
 'user-1561',
 'user-6904',
 'user-4409',
 'user-4967',
 'user-8351',
 'user-9096',
 'user-8967',
 'user-6464',
 'user-9088',
 'user-9809',
 'user-7972',
 'user-8821',
 'user-8679',
 'user-6690',
 'user-6851',
 'user-7180',
 'user-5942',
 'user-2573',
 'user-591',
 'user-9863',
 'user-6525',
 'user-4692',
 'user-3192',
 'user-5905',
 'user-2988',
 'user-1313',
 'user-1045',
 'user-1194',
 'user-7846',
 'user-5980',
 'user-8415',
 'user-7746',
 'user-7209',
 'user-1232',
 'user-3923',
 'user-7512',
 'user-5390',
 'user-3939',
 'user-3102',
 'user-3942',
 'user-5492',
 'user-444',
 'user-8827',
 'user-8739',
 'user-9757',
 'user-8080',
 'user-3390',
 'user-845',
 'user-4958',
 'user-4059',
 'user-2364',
 'user-1730',
 'user-6521',
 'user-3246',
 'user-885',
 'user-6895',
 'user-2493',
 'user-8163',
 'user-7920',
 'user-2718',
 'user-6412',
 'user-2743',
 'user-9487',
 'user-5339',
 'user-4387',
 'user-7004',
 'user-9497',
 'user-4773',
 'user-5139',
 'user-5910',
 'user-8155',
 'user-6270',
 'user-97',
 'user-6317',
 'user-3955',
 'user-6792',
 'user-8367',
 'user-6191',
 'user-9270',
 'user-4566',
 'user-7074',
 'user-8292',
 'user-1690',
 'user-795',
 'user-8086',
 'user-159',
 'user-5504',
 'user-5441',
 'user-771',
 'user-4704',
 'user-7894',
 'user-2225',
 'user-2720',
 'user-9258',
 'user-4782',
 'user-4322',
 'user-2861',
 'user-7408',
 'user-7682',
 'user-4237',
 'user-2646',
 'user-531',
 'user-9220',
 'user-5398',
 'user-7776',
 'user-3929',
 'user-683',
 'user-2499',
 'user-3013',
 'user-4527',
 'user-672',
 'user-3169',
 'user-8622',
 'user-5711',
 'user-1324',
 'user-3992',
 'user-6448',
 'user-362',
 'user-7581',
 'user-8953',
 'user-8200',
 'user-4225',
 'user-1008',
 'user-2790',
 'user-3610',
 'user-7714',
 'user-9857',
 'user-7128',
 'user-2867',
 'user-4220',
 'user-4504',
 'user-243',
 'user-8336',
 'user-3669',
 'user-6790',
 'user-6615',
 'user-9287',
 'user-8757',
 'user-3126',
 'user-7386',
 'user-7964',
 'user-2659',
 'user-871',
 'user-1594',
 'user-3819',
 'user-9806',
 'user-8806',
 'user-4386',
 'user-6437',
 'user-5839',
 'user-5590',
 'user-2309',
 'user-6192',
 'user-3403',
 'user-1090',
 'user-9118',
 'user-4295',
 'user-3895',
 'user-4171',
 'user-1266',
 'user-676',
 'user-9419',
 'user-9069',
 'user-3394',
 'user-6826',
 'user-6928',
 'user-6122',
 'user-7067',
 'user-7599',
 'user-4317',
 'user-6735',
 'user-3310',
 'user-9205',
 'user-9906',
 'user-4681',
 'user-7138',
 'user-8874',
 'user-4942',
 'user-3349',
 'user-5028',
 'user-1367',
 'user-7670',
 'user-3212',
 'user-7198',
 'user-2148',
 'user-5272',
 'user-4180',
 'user-1725',
 'user-2606',
 'user-6010',
 'user-4712',
 'user-6151',
 'user-4941',
 'user-4085',
 'user-993',
 'user-2559',
 'user-5634',
 'user-4078',
 'user-6358',
 'user-1366',
 'user-7800',
 'user-9316',
 'user-4729',
 'user-1410',
 'user-5676',
 'user-7761',
 'user-5808',
 'user-4980',
 'user-2223',
 'user-5411',
 'user-9921',
 'user-5056',
 'user-3002',
 'user-383',
 'user-7054',
 'user-233',
 'user-841',
 'user-1452',
 'user-9188',
 'user-4893',
 'user-721',
 'user-8524',
 'user-7391',
 'user-2690',
 'user-505',
 'user-4856',
 'user-4455',
 'user-6483',
 'user-9865',
 'user-4258',
 'user-8467',
 'user-4245',
 'user-3744',
 'user-9805',
 'user-3397',
 'user-9158',
 'user-5724',
 'user-9714',
 'user-7014',
 'user-8663',
 'user-4926',
 'user-1742',
 'user-1791',
 'user-1407',
 'user-1038',
 'user-6557',
 'user-7780',
 'user-2454',
 'user-6996',
 'user-9777',
 'user-1455',
 'user-3017',
 'user-5575',
 'user-6933',
 'user-738',
 'user-6703',
 'user-1362',
 'user-4380',
 'user-7962',
 'user-8401',
 'user-6674',
 'user-5453',
 'user-8631',
 'user-4065',
 'user-8847',
 'user-7470',
 'user-3807',
 'user-3214',
 'user-8240',
 'user-113',
 'user-4612',
 'user-8176',
 'user-5883',
 'user-8589',
 'user-581',
 'user-6534',
 'user-7859',
 'user-9190',
 'user-822',
 'user-3470',
 'user-2571',
 'user-8693',
 'user-6272',
 'user-8687',
 'user-8036',
 'user-9057',
 'user-252',
 'user-7628',
 'user-8728',
 'user-804',
 'user-2523',
 'user-9598',
 'user-4309',
 'user-7970',
 'user-1303',
 'user-6051',
 'user-325',
 'user-760',
 'user-7879',
 'user-4267',
 'user-8808',
 'user-4694',
 'user-5944',
 'user-554',
 'user-2028',
 'user-5242',
 'user-8399',
 'user-1206',
 'user-6078',
 'user-7694',
 'user-7164',
 'user-2056',
 'user-5860',
 'user-3012',
 'user-6083',
 'user-5297',
 'user-563',
 'user-1100',
 'user-4998',
 'user-6141',
 'user-2100',
 'user-3635',
 'user-187',
 'user-7220',
 'user-3971',
 'user-5247',
 'user-8623',
 'user-1813',
 'user-5585',
 'user-3831',
 'user-9117',
 'user-6486',
 'user-5820',
 'user-5520',
 'user-3109',
 'user-8893',
 'user-163',
 'user-9282',
 'user-8015',
 'user-7834',
 'user-4324',
 'user-216',
 'user-1576',
 'user-8974',
 'user-2129',
 'user-8142',
 'user-6194',
 'user-8711',
 'user-4055',
 'user-5241',
 'user-1249',
 'user-3328',
 'user-9899',
 'user-3290',
 'user-1740',
 'user-651',
 'user-3115',
 'user-3048',
 'user-590',
 'user-8608',
 'user-6357',
 'user-9592',
 'user-828',
 'user-489',
 'user-8920',
 'user-882',
 'user-9583',
 'user-4338',
 'user-2472',
 'user-2089',
 'user-5593',
 'user-4400',
 'user-7227',
 'user-9383',
 'user-9235',
 'user-8322',
 'user-4290',
 'user-2073',
 'user-3096',
 'user-3213',
 'user-3944',
 'user-1920',
 'user-1943',
 'user-6827',
 'user-774',
 'user-715',
 'user-8830',
 'user-3418',
 'user-7858',
 'user-3032',
 'user-1658',
 'user-7431',
 'user-1623',
 'user-4221',
 'user-6246',
 'user-4777',
 'user-4725',
 'user-3358',
 'user-961',
 'user-2050',
 'user-619',
 'user-2232',
 'user-6372',
 'user-1708',
 'user-2533',
 'user-6038',
 'user-3330',
 'user-3681',
 'user-6519',
 'user-4406',
 'user-2155',
 'user-1935',
 'user-7695',
 'user-2227',
 'user-6505',
 'user-9298',
 'user-7657',
 'user-6675',
 'user-6847',
 'user-7030',
 'user-5191',
 'user-7127',
 'user-9513',
 'user-4634',
 'user-1654',
 'user-1763',
 'user-5370',
 'user-5362',
 'user-6541',
 'user-6734',
 'user-5627',
 'user-5899',
 'user-8471',
 'user-3446',
 'user-1976',
 'user-4323',
 'user-1402',
 'user-4645',
 'user-7526',
 'user-6319',
 'user-469',
 'user-1298',
 'user-2550',
 'user-6902',
 'user-6657',
 'user-5299',
 'user-1731',
 'user-9728',
 'user-1445',
 'user-6955',
 'user-1001',
 'user-5659',
 'user-452',
 'user-865',
 'user-1630',
 'user-247',
 'user-1878',
 'user-5116',
 'user-5596',
 'user-6706',
 'user-6231',
 'user-46',
 'user-4526',
 'user-2779',
 'user-5823',
 'user-2593',
 'user-4993',
 'user-9920',
 'user-2152',
 'user-4733',
 'user-7685',
 'user-2054',
 'user-9123',
 'user-8635',
 'user-8064',
 'user-2925',
 'user-5280',
 'user-3855',
 'user-4668',
 'user-8318',
 'user-6128',
 'user-3512',
 'user-6106',
 'user-3557',
 'user-6866',
 'user-4488',
 'user-678',
 'user-8276',
 'user-6281',
 'user-994',
 'user-2307',
 'user-345',
 'user-7223',
 'user-5145',
 'user-8871',
 'user-9252',
 'user-4989',
 'user-1380',
 'user-2086',
 'user-4674',
 'user-397',
 'user-8793',
 'user-3515',
 'user-4475',
 'user-4823',
 'user-2680',
 'user-5038',
 'user-1705',
 'user-6400',
 'user-4321',
 'user-108',
 'user-87',
 'user-5564',
 'user-4714',
 'user-9151',
 'user-6018',
 'user-4548',
 'user-6245',
 'user-6490',
 'user-3758',
 'user-2296',
 'user-5208',
 'user-7095',
 'user-5560',
 'user-2614',
 'user-9828',
 'user-5971',
 'user-805',
 'user-2253',
 'user-7437',
 'user-7479',
 'user-7536',
 'user-1831',
 'user-8416',
 'user-103',
 'user-662',
 'user-3991',
 'user-7820',
 'user-7636',
 'user-6059',
 'user-343',
 'user-4328',
 'user-5673',
 'user-9751',
 'user-9690',
 'user-72',
 'user-4391',
 'user-569',
 'user-1553',
 'user-8040',
 'user-544',
 'user-9183',
 'user-3094',
 'user-2335',
 'user-4212',
 'user-7829',
 'user-8771',
 'user-8022',
 'user-2487',
 'user-692',
 'user-8962',
 'user-4092',
 'user-3549',
 'user-9867',
 'user-6487',
 'user-5700',
 'user-2209',
 'user-7159',
 'user-4556',
 'user-9344',
 'user-759',
 'user-7687',
 'user-8669',
 'user-8579',
 'user-1507',
 'user-4218',
 'user-3157',
 'user-52',
 'user-4252',
 'user-6344',
 'user-8795',
 'user-181',
 'user-3755',
 'user-1729',
 'user-6123',
 'user-1363',
 'user-1292',
 'user-5250',
 'user-9696',
 'user-9719',
 'user-7995',
 'user-6121',
 'user-3432',
 'user-1798',
 'user-4361',
 'user-1702',
 'user-1744',
 'user-547',
 'user-9596',
 'user-296',
 'user-510',
 'user-424',
 'user-7872',
 'user-9460',
 'user-2231',
 'user-2911',
 'user-1641',
 'user-2195',
 'user-5655',
 'user-1143',
 'user-798',
 'user-1698',
 'user-8151',
 'user-6654',
 'user-3254',
 'user-8998',
 'user-7876',
 'user-4564',
 'user-6949',
 'user-2170',
 'user-2594',
 'user-2167',
 'user-8140',
 'user-8977',
 'user-499',
 'user-4255',
 'user-7590',
 'user-3141',
 'user-5061',
 'user-7607',
 'user-7292',
 'user-597',
 'user-2876',
 'user-2026',
 'user-433',
 'user-2631',
 'user-9796',
 'user-6221',
 'user-6991',
 'user-1546',
 'user-1828',
 'user-9501',
 'user-5060',
 'user-8696',
 'user-9448',
 'user-477',
 'user-6258',
 'user-1351',
 'user-3138',
 'user-8350',
 'user-1853',
 'user-5506',
 'user-1761',
 'user-9357',
 'user-2619',
 'user-598',
 'user-8016',
 'user-6431',
 'user-3294',
 'user-2319',
 'user-3859',
 'user-8458',
 'user-132',
 'user-5045',
 'user-1816',
 'user-5493',
 'user-3572',
 'user-2676',
 'user-929',
 'user-6163',
 'user-6395',
 'user-1582',
 'user-6523',
 'user-4113',
 'user-731',
 'user-8260',
 'user-2287',
 'user-308',
 'user-7651',
 'user-387',
 'user-3183',
 'user-4432',
 'user-2962',
 'user-9574',
 'user-3340',
 'user-1912',
 'user-1835',
 'user-1191',
 'user-8862',
 'user-1499',
 'user-9961',
 'user-1433',
 'user-3445',
 'user-2724',
 'user-5940',
 'user-7626',
 'user-5932',
 'user-1356',
 'user-7023',
 'user-4357',
 'user-7340',
 'user-5891',
 'user-8190',
 'user-9044',
 'user-4182',
 'user-5078',
 'user-2361',
 'user-8644',
 'user-6201',
 'user-5154',
 'user-1946',
 'user-3479',
 'user-3600',
 'user-7015',
 'user-5483',
 'user-5092',
 'user-1447',
 'user-1378',
 'user-3103',
 'user-9000',
 'user-4106',
 'user-580',
 'user-1596',
 'user-7902',
 'user-4890',
 'user-9688',
 'user-5068',
 'user-4399',
 'user-1058',
 'user-4666',
 'user-5725',
 'user-9339',
 'user-1897',
 'user-6652',
 'user-9984',
 'user-2038',
 'user-8745',
 'user-2639',
 'user-8680',
 'user-9985',
 'user-1169',
 'user-5847',
 'user-3194',
 'user-5482',
 'user-4018',
 'user-1837',
 'user-305',
 'user-4627',
 'user-8162',
 'user-1165',
 'user-1848',
 'user-7511',
 'user-8034',
 'user-1026',
 'user-6011',
 'user-2359',
 'user-6911',
 'user-7993',
 'user-6857',
 'user-2589',
 'user-2714',
 'user-4665',
 'user-7815',
 'user-6217',
 'user-4262',
 'user-9948',
 'user-5580',
 'user-5160',
 'user-7738',
 'user-6502',
 'user-8789',
 'user-7908',
 'user-545',
 'user-6802',
 'user-7131',
 'user-3227',
 'user-3271',
 'user-9263',
 'user-5814',
 'user-1767',
 'user-5821',
 'user-1403',
 'user-2545',
 'user-5621',
 'user-6458',
 'user-6433',
 'user-8850',
 'user-438',
 'user-6134',
 'user-7405',
 'user-4069',
 'user-5146',
 'user-7713',
 'user-9534',
 'user-1703',
 'user-3303',
 'user-9089',
 'user-9613',
 'user-6496',
 'user-6398',
 'user-7597',
 'user-8965',
 'user-4196',
 'user-7911',
 'user-8791',
 'user-1750',
 'user-1392',
 'user-7212',
 'user-1361',
 'user-419',
 'user-8480',
 'user-3370',
 'user-1108',
 'user-786',
 'user-7585',
 'user-4404',
 'user-5572',
 'user-8892',
 'user-9937',
 'user-927',
 'user-1109',
 'user-4118',
 'user-6773',
 'user-2289',
 'user-9003',
 'user-485',
 'user-1657',
 'user-919',
 'user-2746',
 'user-3430',
 'user-7537',
 'user-7417',
 'user-1305',
 'user-1579',
 'user-2333',
 'user-7807',
 'user-2360',
 'user-5541',
 'user-9001',
 'user-9404',
 'user-504',
 'user-955',
 'user-4947',
 'user-9600',
 'user-158',
 'user-9457',
 'user-7856',
 'user-1007',
 'user-7428',
 'user-5916',
 'user-7832',
 'user-3950',
 'user-3319',
 'user-2494',
 'user-703',
 'user-3139',
 'user-6823',
 'user-4565',
 'user-4792',
 'user-8364',
 'user-6879',
 'user-3415',
 'user-1927',
 'user-5414',
 'user-481',
 'user-1886',
 'user-956',
 'user-9020',
 'user-1614',
 'user-2601',
 'user-5672',
 'user-3700',
 'user-3251',
 'user-6425',
 'user-8534',
 'user-1661',
 'user-9337',
 'user-6513',
 'user-3421',
 'user-5104',
 'user-5500',
 'user-5324',
 'user-4685',
 'user-749',
 'user-5977',
 'user-7890',
 'user-3701',
 'user-5789',
 'user-3079',
 'user-7598',
 'user-8753',
 'user-2967',
 'user-4831',
 'user-8252',
 'user-9211',
 'user-4595',
 'user-4908',
 'user-9076',
 'user-2213',
 'user-3953',
 'user-6288',
 'user-3558',
 'user-8876',
 'user-3581',
 'user-8044',
 'user-7605',
 'user-5624',
 'user-952',
 'user-4514',
 'user-9198',
 'user-6222',
 'user-2183',
 'user-9618',
 'user-6848',
 'user-3796',
 'user-6793',
 'user-131',
 'user-5719',
 'user-1653',
 'user-4154',
 'user-573',
 'user-30',
 'user-7226',
 'user-9779',
 'user-7505',
 'user-7289',
 'user-4439',
 'user-8465',
 'user-6475',
 'user-3160',
 'user-4043',
 'user-8887',
 'user-3501',
 'user-2',
 'user-1864',
 'user-2459',
 'user-1417',
 'user-3541',
 'user-2412',
 'user-1914',
 'user-1700',
 'user-8713',
 'user-14',
 'user-8100',
 'user-2263',
 'user-8928',
 'user-3562',
 'user-2885',
 'user-8944',
 'user-1426',
 'user-1350',
 ...}

### Cut off zone

In [ ]:
user_new = pd.read_csv("/content/relationship_user_movie_new.csv")

In [ ]:
user_node = pd.read_csv("/content/node_user.csv")
user_node = user_node.iloc[0:10000]
user_node.to_csv("node_user_new.csv", index=False)
user_node

,user_id,name,email,phone number
0,user-1,Jacqueline Gonzalez,jamiemunoz@example.com,(815)448-7940x224
1,user-2,Katherine Beltran,jmunoz@example.net,606-374-3708x96800
2,user-3,Samantha Kent,grahamandre@example.com,677-391-3132x873
3,user-4,Renee Montgomery,sanderslaura@example.net,580.693.4656
4,user-5,Erin May,wheelereric@example.org,392.511.6381x9655
...,...,...,...,...
9995,user-9996,William Harrington,paynekevin@example.com,463-251-2796x800
9996,user-9997,Thomas Gonzalez,anunez@example.com,594-396-4903
9997,user-9998,Dr. Alyssa Ritter,randyroberts@example.org,534.775.7204
9998,user-9999,Alexis Burns,woodthomas@example.net,001-833-974-5255x41623
9999,user-10000,Patrick Bush,amanda57@example.org,(425)360-7901x52104

In [ ]:
user_media = pd.read_csv("/content/relationship_user_movie_reduce_size.csv")
user_media = user_media.iloc[0:26]
user_media.to_csv("relationship_user_movie_reduce_size.csv", index=False)

In [ ]:
user_user = pd.read_csv("/content/relationship_user_friend_reduce_size.csv")
user_user = user_user.iloc[0:17]
user_user.to_csv("relationship_user_friend_reduce_size.csv", index=False)

In [ ]:
data = pd.read_csv("/content/data1.csv")
data

           user_id  user_rating    ent_id
0           user-1            3  mov-7580
1           user-1            2  mov-7934
2           user-1            3   mov-964
3           user-1            3  mov-5749
4           user-1            3  mov-6679
...            ...          ...       ...
226022  user-10000            4   mov-222
226023  user-10000            3  mov-6541
226024  user-10000            3  mov-6468
226025  user-10000            3  mov-2253
226026  user-10000            4  mov-6433

[226027 rows x 3 columns]

In [ ]:
def cut_off(data):
  # data = user_movie_rel.drop(user_movie_rel.index[1001::])
  num_list = [i for i in tqdm(range(data.shape[0])) if i%10 != 0]
  result = data.drop(num_list)
  return result
result = cut_off(data)
result.to_csv("relationship_user_movie_new.csv", index=False)

100%|██████████| 226027/226027 [00:00<00:00, 1295820.21it/s]

In [ ]:
pd.read_csv("/content/relationship_user_friend_reduce_size.csv")

        ent_id  user_id  user_rating
0      mov-282   user-1            3
1    mov-13009   user-1            2
2    mov-13116   user-1            4
3    mov-13271   user-1            3
4    mov-13351   user-1            1
..         ...      ...          ...
449  mov-11680  user-10            5
450  mov-11766  user-10            1
451  mov-11813  user-10            1
452   mov-7853  user-10            2
453  mov-10266  user-10            4

[454 rows x 3 columns]

In [ ]:
def cut_off(data):
  data = data.iloc[0:10000]
  return data
new_user_data = cut_off(user)
# new_user_data
new_user_data.to_csv("node_user_reduce_size.csv", index=False)

In [ ]:
pd.read_csv("/content/node_user_reduce_size.csv")

,user_id,name,email,phone number
0,user-1,Jacqueline Gonzalez,jamiemunoz@example.com,(815)448-7940x224
1,user-2,Katherine Beltran,jmunoz@example.net,606-374-3708x96800
2,user-3,Samantha Kent,grahamandre@example.com,677-391-3132x873
3,user-4,Renee Montgomery,sanderslaura@example.net,580.693.4656
4,user-5,Erin May,wheelereric@example.org,392.511.6381x9655
...,...,...,...,...
9995,user-9996,William Harrington,paynekevin@example.com,463-251-2796x800
9996,user-9997,Thomas Gonzalez,anunez@example.com,594-396-4903
9997,user-9998,Dr. Alyssa Ritter,randyroberts@example.org,534.775.7204
9998,user-9999,Alexis Burns,woodthomas@example.net,001-833-974-5255x41623
9999,user-10000,Patrick Bush,amanda57@example.org,(425)360-7901x52104

### User

In [ ]:
def cleaning(rate1, additional1):

  # Mapping rate1 data
  rate1 = rate1.merge(additional1, left_on="Movie_ID", right_on="Movie_ID")
  rate1 = rate1.reindex(columns=["User_ID", "Rating", "Name"])
  rate1.columns = ["user_id", "rating", "name"]
  # combine1 = rate1.merge(media, left_on="name", right_on="title")
  # rate1_title = combine1["name"].unique().tolist()
  # uk_title = uk_movie["title"].unique().tolist()
  # return len([i for i in uk_title if i in rate1_title])
  return rate1

def user_node_and_user_relationship(data, media):

  # Fruitful zone
  user = pd.DataFrame()
  user['user_id_old'] = sorted(data['user_id'].unique())
  user['user_id'] = user.index + 1
  user['user_id'] = user['user_id'].apply(lambda x: f"user-{x}").astype(str)

  # # User Node
  # user_node = pd.DataFrame(columns=["user_id", "name", "email", "phone number"])
  # # user['name'] = user['name'].apply(lambda _: faker.name()).astype(str)
  # user_node['user_id'] = user['user_id']
  # for i in range(len(user_node)):
  #   user_node['name'].iloc[[i]] = faker.name()
  #   user_node['email'].iloc[[i]] = faker.email()
  #   user_node['phone number'].iloc[[i]] = faker.phone_number()

  # User Relationship
  user_rel = data.merge(media, left_on="name", right_on="title")
  # user_rel = data.merge(uk_movie, left_on="title", right_on="title")
  user_rel = user.merge(user_rel, left_on="user_id_old", right_on="user_id")
  user_rel = user_rel.reindex(columns=["user_id_x", "rating", "ent_id"])
  user_rel.columns = ["user_id", "user_rating", "ent_id"]
  # user_list = user["user_id"].unique().tolist()
  # df = pd.DataFrame(columns=["user_id", "user_rating", "ent_id"])
  # ent_id = []
  # rate = []
  # user_id = []
  # # for name in tqdm(user_rel["user_id"].unique().tolist()):
  # media_list = media["ent_id"].unique().tolist()
  # user_rel_media_list = user_rel["ent_id"].unique().tolist()
  # for title in tqdm(media_list):
  #   if title not in user_rel_media_list:
  #     title_number = random.randint(1, 150)
  #     for col3 in range(title_number):
  #       ent_id.append(title)
  # for size in tqdm(range(len(ent_id))):
  #   rate_number = random.randint(1, 5)
  #   con = user_rel["user_id"].iloc[random.randrange(user.shape[0])]
  #   user_id.append(con)
  #   rate.append(rate_number)
  # df["user_id"] = user_id
  # df["user_rating"] = rate
  # df["ent_id"] = ent_id
  # result = pd.concat([user_rel, df], sort=True)
  return user_rel

# faker = Faker()
clean = cleaning(ndr, ndm)
generate = user_node_and_user_relationship(clean, media)
user_rel = generate
# len(clean["ent_id"].unique().tolist())
# user_node, user_rel = generate
# user_node.to_csv('node_user.csv', index=False)
user_rel.to_csv('relationship_user_movie_new.csv', index=False)

In [ ]:
# Generate new entertainment media node
movie_list = user_rel["ent_id"].unique().tolist()
ent_node = media[media["ent_id"].isin(movie_list)]
ent_node.to_csv("node_entertainment_new.csv", index=False)

In [ ]:
# Generate new director node
movie_list = user_rel["ent_id"].unique().tolist()
dir_list = dir_ent["dir_id"][dir_ent["ent_id"].isin(movie_list)].unique().tolist()
dir_node = director[director["dir_id"].isin(dir_list)]
dir_node.to_csv("node_director_new.csv", index=False)

In [ ]:
# Generate new entertainment media and user relationship
movie_list = user_rel["ent_id"].unique().tolist()
user_list = user_node["user_id"].unique().tolist()
random_list = []
new_df = pd.DataFrame()
new_df["user_id"] = user_rel["user_id"][user_rel["user_id"].isin(user_list)]
new_df["user_rating"] = user_rel["user_rating"].iloc[0:238086]
for i in tqdm(range(new_df.shape[0])):
  title = movie_list[random.randrange(len(movie_list))]
  random_list.append(title)
new_df["ent_id"] = random_list
new_df.to_csv("relationship_entertainment_user.csv", index=False)

100%|██████████| 238086/238086 [00:00<00:00, 427455.22it/s]

In [ ]:
new_df

           user_id  user_rating     ent_id
0           user-1            3   mov-6943
1           user-1            2   mov-5916
2           user-1            3   mov-7180
3           user-1            3   mov-1639
4           user-1            3   mov-8032
...            ...          ...        ...
238081  user-10000            3   mov-6329
238082  user-10000            3   mov-6792
238083  user-10000            3   mov-7675
238084  user-10000            4   mov-7599
238085  user-10000            4  mov-14528

[238086 rows x 3 columns]

In [ ]:
user_rel = user_rel.sort_values(by=["ent_id"])
# user_rel[user_rel["user_id"] == "user-10"]
# user_rel.to_csv('relationship_user_movie_new.csv', index=False)
user_rel = pd.read_csv("/content/relationship_user_movie_new.csv")
user_rel
# user_rel[user_rel["user_id"] == "user"]

            ent_id     user_id  user_rating
0          mov-282      user-1            3
1        mov-13009      user-1            2
2        mov-13116      user-1            4
3        mov-13271      user-1            3
4        mov-13351      user-1            1
...            ...         ...          ...
4540487    mov-254  user-99999            4
4540488   mov-9214  user-99999            2
4540489   mov-7713  user-99999            3
4540490   mov-5749  user-99999            3
4540491   mov-8871  user-99999            3

[4540492 rows x 3 columns]

### Friends

In [ ]:
user_new = pd.read_csv("/content/node_user_new.csv")
user_new

,user_id,name,email,phone number
0,user-1,Jacqueline Gonzalez,jamiemunoz@example.com,(815)448-7940x224
1,user-2,Katherine Beltran,jmunoz@example.net,606-374-3708x96800
2,user-3,Samantha Kent,grahamandre@example.com,677-391-3132x873
3,user-4,Renee Montgomery,sanderslaura@example.net,580.693.4656
4,user-5,Erin May,wheelereric@example.org,392.511.6381x9655
...,...,...,...,...
9995,user-9996,William Harrington,paynekevin@example.com,463-251-2796x800
9996,user-9997,Thomas Gonzalez,anunez@example.com,594-396-4903
9997,user-9998,Dr. Alyssa Ritter,randyroberts@example.org,534.775.7204
9998,user-9999,Alexis Burns,woodthomas@example.net,001-833-974-5255x41623
9999,user-10000,Patrick Bush,amanda57@example.org,(425)360-7901x52104

In [ ]:
def friend_relationship(data):
  user_id = []
  user = data["user_id"].tolist()
  for name in tqdm(user):
    number = random.randint(1, 5)
    for i in range(number):
      user_id.append(name)
  result = pd.DataFrame(columns=["user_id", "friend_id"])
  result["user_id"] = user_id
  for i in tqdm(range(result.shape[0])):
    friend = data["user_id"].iloc[random.randrange(data.shape[0])]
    if friend != result["user_id"].iloc[i]:
      result["friend_id"].iloc[i] = friend
  return result

friends = friend_relationship(user_new)
friends.to_csv("relationship_user_friends_new.csv", index=False)

100%|██████████| 10000/10000 [00:00<00:00, 446359.25it/s]
100%|██████████| 29866/29866 [00:19<00:00, 1504.61it/s]

In [ ]:
def friend_relationship(data):
  user_id = []
  user = data["user_id"].tolist()
  for name in tqdm(user):
    number = random.randint(1, 5)
    for i in range(number):
      user_id.append(name)
  result = pd.DataFrame(columns=["user_id", "friend_id"])
  result["user_id"] = user_id
  for i in tqdm(range(result.shape[0])):
    friend = data["user_id"].iloc[random.randrange(data.shape[0])]
    if friend != result["user_id"].iloc[i]:
      result["friend_id"].iloc[i] = friend
  return result

friends = friend_relationship(user_user)
friends.to_csv("relationship_user_friends_test.csv", index=False)

100%|██████████| 17/17 [00:00<00:00, 20922.29it/s]
100%|██████████| 52/52 [00:00<00:00, 2620.18it/s]

In [ ]:
pd.read_csv("/content/relationship_user_friends.csv")

            user_id    friend_id
0            user-1  user-110373
1            user-1   user-17323
2            user-1     user-841
3            user-2    user-5212
4            user-2  user-102040
...             ...          ...
430595  user-143457   user-96084
430596  user-143457   user-55079
430597  user-143458  user-107731
430598  user-143458  user-131887
430599  user-143458  user-103109

[430600 rows x 2 columns]

# **Credit**

In [ ]:
credit1 = pd.read_csv('/content/credits.csv')
credit2 = pd.read_csv('/content/raw_credits.csv')

In [ ]:
credit2

,index,person_id,id,name,character,role
0,0,3748,tm84618,Robert De Niro,Travis Bickle,ACTOR
1,1,14658,tm84618,Jodie Foster,Iris Steensma,ACTOR
2,2,7064,tm84618,Albert Brooks,Tom,ACTOR
3,3,3739,tm84618,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,4,48933,tm84618,Cybill Shepherd,Betsy,ACTOR
...,...,...,...,...,...,...
77208,77208,1347054,tm1098060,Nnenna Rachael Okonkwo,Afinni,ACTOR
77209,77209,157590,tm1098060,Lucien Morgan,Dr. Ian Stones,ACTOR
77210,77210,129059,tm1098060,Magdalena Korpas,Jane,ACTOR
77211,77211,2050199,tm1098060,Mistura Olusanya,Nurse Titi,ACTOR
77212,77212,2050423,tm1098060,Yemi Amodu,NaN,DIRECTOR

In [ ]:
credit2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77213 entries, 0 to 77212
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      77213 non-null  int64
 1   person_id  77213 non-null  int64
 2   id         77213 non-null  object
 3   name       77213 non-null  object
 4   character  67586 non-null  object
 5   role       77213 non-null  object
dtypes: int64(2), object(4)
memory usage: 3.5+ MB

In [ ]:
credit = pd.concat([credit1, credit2], axis = 0)
credit = credit.drop_duplicates(subset=['name', 'character', 'role'])

In [ ]:
credit.reset_index(drop=True, inplace=True)

In [ ]:
credit = credit.drop(columns=['index'])
credit['person_id'] = credit['person_id'].astype(str)

In [ ]:
credit.head(5)

  person_id       id             name                character   role
0      3748  tm84618   Robert De Niro            Travis Bickle  ACTOR
1     14658  tm84618     Jodie Foster            Iris Steensma  ACTOR
2      7064  tm84618    Albert Brooks                      Tom  ACTOR
3      3739  tm84618    Harvey Keitel  Matthew 'Sport' Higgins  ACTOR
4     48933  tm84618  Cybill Shepherd                    Betsy  ACTOR

In [ ]:
dir = credit[credit['role'] == 'DIRECTOR']
actor = credit[credit['role'] == 'ACTOR']

In [ ]:
# รวมกับ data3
data_dir = pd.concat([dir, data_director], axis = 0).reset_index(drop=True)
data_dir = data_dir.drop(columns=['character', 'role'])

data_actor = pd.concat([actor, data_actor], axis = 0).reset_index(drop=True)
data_actor = data_actor.drop(columns=['role'])

In [ ]:
data_dir.head(5)

  person_id        id             name
0      3308   tm84618  Martin Scorsese
1     17727  tm154986     John Boorman
2     11475  tm127384      Terry Jones
3     11473  tm127384    Terry Gilliam
4      1063  tm120801   Robert Aldrich

In [ ]:
data_actor.head(5)

  person_id       id             name                character
0      3748  tm84618   Robert De Niro            Travis Bickle
1     14658  tm84618     Jodie Foster            Iris Steensma
2      7064  tm84618    Albert Brooks                      Tom
3      3739  tm84618    Harvey Keitel  Matthew 'Sport' Higgins
4     48933  tm84618  Cybill Shepherd                    Betsy

# **แยกไฟล์ node**

## **movie**

In [ ]:
# create new movie id
df_movie = pd.DataFrame(movie['id']).astype(str)
df_movie = df_movie.drop_duplicates().reset_index(drop=True)
df_movie['new_id'] = df_movie.index + 1
df_movie['new_id'] = df_movie['new_id'].apply(lambda x: f"mov-{x}").astype(str)

In [ ]:
df_movie.tail(5)

         id     new_id
14558  9820  mov-14559
14559  9821  mov-14560
14560  9823  mov-14561
14561  9824  mov-14562
14562  9825  mov-14563

In [ ]:
# replace to dataframe
movie_dict = df_movie.set_index('id').to_dict(orient='dict')['new_id']
movie['id'] = movie['id'].replace(movie_dict)

In [ ]:
main_data.tail(5)

,id,title,type,description,release_year,age_certification,runtime,seasons,imdb_score,imdb_votes
14597,mov-14559,Shakespeare in Love,movie,NaN,1998,NaN,123.0,NaN,7.1,218921.0
14598,mov-14560,All Monsters Attack,movie,NaN,1969,NaN,69.0,NaN,3.9,4384.0
14599,mov-14561,Epoch,movie,NaN,2001,NaN,96.0,NaN,4.9,2376.0
14600,mov-14562,The Company,movie,NaN,2003,NaN,112.0,NaN,6.3,6501.0
14601,mov-14563,Predator,movie,NaN,1987,NaN,107.0,NaN,7.8,386850.0

## **Type**

In [ ]:
df_type = pd.DataFrame(movie['type']).astype(str)
df_type = df_type.drop_duplicates().sort_values(by='type').reset_index(drop=True)
df_type['id'] = df_type.index + 1
df_type['id'] = df_type['id'].apply(lambda x: f"type-{x}")
df_type = df_type.drop(df_type[df_type['type'] == 'nan'].index, axis=0)
df_type.to_csv('data_type.csv', index=False)

In [ ]:
df_type

         type      id
0       movie  type-1
1      series  type-2
2        show  type-3
3    tv short  type-4
4  video game  type-5

### **Relationship - Type & Movie**

In [ ]:
# create type index
type_dict = df_type.set_index('type').to_dict(orient='dict')['id']

In [ ]:
relationship_type_movie = pd.DataFrame(movie[['id', 'type']])
relationship_type_movie['id'] = relationship_type_movie['id'].replace(movie_dict)
relationship_type_movie['type'] = relationship_type_movie['type'].replace(type_dict)

In [ ]:
relationship_type_movie.to_csv('relationship_movie_type.csv', index=False)

In [ ]:
relationship_type_movie["type"].value_counts()

type-1    11289
type-3     2119
type-2     1161
type-5       23
type-4       10
Name: type, dtype: int64

## **Year**

In [ ]:
df_year = pd.DataFrame(main_data['release_year']).astype(int)
df_year = df_year.drop_duplicates().sort_values(by='release_year').reset_index(drop=True)
# df_year['id'] = df_year.index + 1
df_year['id'] = df_year['release_year'].apply(lambda x: f"year-{x}")

In [ ]:
df_year.to_csv('data_year.csv', index=False)

In [ ]:
df_year

     release_year         id
0            1905  year-1905
1            1910  year-1910
2            1913  year-1913
3            1914  year-1914
4            1916  year-1916
..            ...        ...
104          2019  year-2019
105          2020  year-2020
106          2021  year-2021
107          2022  year-2022
108          2023  year-2023

[109 rows x 2 columns]

### **Relation - Year & Movie**

In [ ]:
# create year index
year_dict = df_year.set_index('release_year').to_dict(orient='dict')['id']

In [ ]:
relationship_year_movie = pd.DataFrame(main_data[['id', 'release_year']])
relationship_year_movie['id'] = relationship_year_movie['id'].replace(movie_dict)
relationship_year_movie['release_year'] = relationship_year_movie['release_year'].replace(year_dict)
relationship_year_movie.to_csv('relationship_movie_year.csv', index=False)

In [ ]:
relationship_year_movie

              id release_year
0          mov-1    year-1945
1          mov-2    year-1976
2          mov-3    year-1972
3          mov-4    year-1975
4          mov-5    year-1967
...          ...          ...
14597  mov-14559    year-1998
14598  mov-14560    year-1969
14599  mov-14561    year-2001
14600  mov-14562    year-2003
14601  mov-14563    year-1987

[14602 rows x 2 columns]

## **Age Certification**

In [ ]:
df_age = pd.DataFrame(main_data['age_certification']).astype(str)
df_age = df_age.drop_duplicates().sort_values(by='age_certification').reset_index(drop=True)
df_age['id'] = df_age.index + 1
df_age['id'] = df_age['id'].apply(lambda x: f"age-{x}")
df_age = df_age.drop(df_age[df_age['age_certification'] == 'nan'].index, axis=0)
df_age.to_csv('data_age_certification.csv', index=False)

In [ ]:
df_age

   age_certification      id
0                  G   age-1
1              NC-17   age-2
2                 PG   age-3
3              PG-13   age-4
4                  R   age-5
5              TV-14   age-6
6               TV-G   age-7
7              TV-MA   age-8
8              TV-PG   age-9
9               TV-Y  age-10
10             TV-Y7  age-11

### **Relationship Age_certification & Movie**

In [ ]:
# create age index
age_dict = df_age.set_index('age_certification').to_dict(orient='dict')['id']

In [ ]:
relationship_age_movie = pd.DataFrame(main_data[['id', 'age_certification']]).dropna(axis=0)
relationship_age_movie = relationship_age_movie.drop(relationship_age_movie[relationship_age_movie['age_certification'] == 'nan'].index, axis=0)
relationship_age_movie['id'] = relationship_age_movie['id'].replace(movie_dict)
relationship_age_movie['age_certification'] = relationship_age_movie['age_certification'].replace(age_dict)
relationship_age_movie.to_csv('relationship_movie_age_certification.csv', index=False)

In [ ]:
relationship_age_movie.to_csv('relationship_movie_age_certification.csv', index=False)

In [ ]:
relationship_age_movie

            id age_certification
0        mov-1             age-8
1        mov-2             age-5
2        mov-3             age-5
3        mov-4             age-3
5        mov-6             age-6
...        ...               ...
6178  mov-5402             age-8
6179  mov-5032             age-9
6180  mov-5066             age-3
6183  mov-5315             age-1
6184  mov-5717             age-9

[3448 rows x 2 columns]

### **movie file complete**

In [ ]:
# Drop column
main_data = main_data.drop(['type', 'release_year', 'age_certification', 'production_countries', 'genres', 'language', 'cast', 'director'], axis=1)
main_data.reset_index(drop=True, inplace=True)
main_data.to_csv('data_movie.csv', index=False)
main_data

,id,title,description,runtime,seasons,imdb_score,imdb_votes
0,mov-1,Five Came Back: The Reference Films,This collection includes 12 World War II-era p...,51.0,1.0,NaN,NaN
1,mov-2,Taxi Driver,A mentally unstable Vietnam War veteran works ...,114.0,NaN,8.2,808582.0
2,mov-3,Deliverance,Intent on seeing the Cahulawassee River before...,109.0,NaN,7.7,107673.0
3,mov-4,Monty Python and the Holy Grail,"King Arthur, accompanied by his squire, recrui...",91.0,NaN,8.2,534486.0
4,mov-5,The Dirty Dozen,12 American military prisoners in World War II...,150.0,NaN,7.7,72662.0
...,...,...,...,...,...,...,...
14597,mov-14559,Shakespeare in Love,NaN,123.0,NaN,7.1,218921.0
14598,mov-14560,All Monsters Attack,NaN,69.0,NaN,3.9,4384.0
14599,mov-14561,Epoch,NaN,96.0,NaN,4.9,2376.0
14600,mov-14562,The Company,NaN,112.0,NaN,6.3,6501.0
14601,mov-14563,Predator,NaN,107.0,NaN,7.8,386850.0

## **GENRE**

In [ ]:
data_genre.head(5)

         id         genres
0  ts300399  documentation
1   tm84618          drama
2   tm84618          crime
3  tm154986          drama
4  tm154986         action

In [ ]:
df_genre = pd.DataFrame(data_genre['genres'])
df_genre = df_genre.loc[~(df_genre['genres'] == '[]')]
df_genre = df_genre.drop_duplicates().reset_index(drop=True)
df_genre['id'] = df_genre.index + 1
df_genre['id'] = df_genre['id'].apply(lambda x: f"gen-{x}")
df_genre.head(10)
df_genre.to_csv('data_genre.csv', index=False)

In [ ]:
df_genre

           genres      id
0   documentation   gen-1
1           drama   gen-2
2           crime   gen-3
3          action   gen-4
4        thriller   gen-5
5        european   gen-6
6         fantasy   gen-7
7          comedy   gen-8
8             war   gen-9
9         romance  gen-10
10        western  gen-11
11        history  gen-12
12          music  gen-13
13         family  gen-14
14         horror  gen-15
15         sci-fi  gen-16
16      animation  gen-17
17        reality  gen-18
18          sport  gen-19
19    documentary  gen-20
20        mystery  gen-21
21      talk-show  gen-22
22      adventure  gen-23
23        musical  gen-24
24          short  gen-25
25      biography  gen-26
26      game-show  gen-27
27     reality-tv  gen-28
28      film-noir  gen-29
29           news  gen-30

In [ ]:
df_genre

           genres      id
0   documentation   gen-1
1           drama   gen-2
2           crime   gen-3
3          action   gen-4
4        thriller   gen-5
5        european   gen-6
6         fantasy   gen-7
7          comedy   gen-8
8             war   gen-9
9         romance  gen-10
10        western  gen-11
11        history  gen-12
12          music  gen-13
13         family  gen-14
14         horror  gen-15
15         sci-fi  gen-16
16      animation  gen-17
17        reality  gen-18
18          sport  gen-19
19    documentary  gen-20
20        mystery  gen-21
21      talk-show  gen-22
22      adventure  gen-23
23        musical  gen-24
24          short  gen-25
25      biography  gen-26
26      game-show  gen-27
27     reality-tv  gen-28
28      film-noir  gen-29
29           news  gen-30

### **Relationship - Genre & Movie**

In [ ]:
# create genre index
genre_dict = df_genre.set_index('genres').to_dict(orient='dict')['id']

In [ ]:
relationship_genre_movie = data_genre
relationship_genre_movie['id'] = relationship_genre_movie['id'].replace(movie_dict)
relationship_genre_movie['genres'] = relationship_genre_movie['genres'].replace(genre_dict)
relationship_genre_movie.to_csv('relationship_movie_genre.csv', index=False)

In [ ]:
relationship_genre_movie.to_csv('relationship_movie_genre.csv', index=False)

In [ ]:
relationship_genre_movie

              id  genres
0          mov-1   gen-1
1          mov-2   gen-2
2          mov-2   gen-3
3          mov-3   gen-2
4          mov-3   gen-4
...          ...     ...
37698  mov-14562  gen-10
37699  mov-14563   gen-4
37700  mov-14563  gen-23
37701  mov-14563  gen-16
37702  mov-14563   gen-5

[37640 rows x 2 columns]

## **LANGUAGE**

In [ ]:
data_language.head(5)

  id  language
0  0   English
1  1  Japanese
2  2   English
3  5  Japanese
4  6   English

In [ ]:
# create file language
df_language = pd.DataFrame(data_language['language'])
df_language = df_language.drop_duplicates().reset_index(drop=True)
df_language['id'] = df_language.index + 1
df_language['id'] = df_language['id'].apply(lambda x: f"lang-{x}")
df_language.to_csv('data_language.csv', index=False)

In [ ]:
df_language.head(5)

   language      id
0   English  lang-1
1  Japanese  lang-2
2    German  lang-3
3   Spanish  lang-4
4   Russian  lang-5

### **Relationship - Language_DATA3 & Movie**

In [ ]:
# create language index
language_dict = df_language.set_index('language').to_dict(orient='dict')['id']

In [ ]:
relationship_language_movie = data_language
relationship_language_movie = relationship_language_movie.astype(str)
relationship_language_movie['id'] = relationship_language_movie['id'].replace(movie_dict)
relationship_language_movie['language'] = relationship_language_movie['language'].replace(language_dict)
relationship_language_movie.to_csv('relationship_movie_language.csv', index=False)

In [ ]:
relationship_language_movie

              id language
0       mov-6147   lang-1
1       mov-6148   lang-2
2       mov-6149   lang-1
3       mov-6151   lang-2
4       mov-6152   lang-1
...          ...      ...
11111  mov-14561   lang-1
11112  mov-14562   lang-1
11113  mov-14563   lang-1
11114  mov-14563   lang-4
11115  mov-14563   lang-5

[11116 rows x 2 columns]

## **PRODUCT_COUNTRY**

In [ ]:
# create file product country
df_country = pd.DataFrame(data_production_country['production_countries'])
df_country = df_country.drop_duplicates().reset_index(drop=True)
df_country['id'] = df_country.index + 1
df_country['id'] = df_country['id'].apply(lambda x: f"country-{x}")
df_country.to_csv('data_product_country.csv', index=False)

In [ ]:
df_country.head(5)

  production_countries         id
0        United States  country-1
1       United Kingdom  country-2
2                Egypt  country-3
3              Germany  country-4
4                India  country-5

### **Relationship - Product_country & Movie**

In [ ]:
# create age index
country_dict = df_country.set_index('production_countries').to_dict(orient='dict')['id']

In [ ]:
relationship_country_movie = data_production_country
relationship_country_movie['id'] = relationship_country_movie['id'].replace(movie_dict)
relationship_country_movie['production_countries'] = relationship_country_movie['production_countries'].replace(country_dict)
relationship_country_movie.to_csv('relationship_movie_production_country.csv', index=False)

In [ ]:
relationship_country_movie

              id production_countries
0          mov-1            country-1
1          mov-2            country-1
2          mov-3            country-1
3          mov-4            country-2
4          mov-5            country-2
...          ...                  ...
17800  mov-14562            country-1
17801  mov-14562            country-4
17802  mov-14562            country-2
17803  mov-14563            country-1
17804  mov-14563           country-21

[17805 rows x 2 columns]

## **Actor & Character**

In [ ]:
data_actor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345131 entries, 0 to 345130
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   person_id  79040 non-null   object
 1   id         345131 non-null  object
 2   name       345131 non-null  object
 3   character  73908 non-null   object
dtypes: object(4)
memory usage: 10.5+ MB

## **Actor**

In [ ]:
actor_inner = pd.merge(df_movie, data_actor, on='id', how='inner')
actor_inner.drop('id', axis='columns', inplace=True)

In [ ]:
actor_inner

           new_id person_id              name                character
0           mov-2      3748    Robert De Niro            Travis Bickle
1           mov-2     14658      Jodie Foster            Iris Steensma
2           mov-2      7064     Albert Brooks                      Tom
3           mov-2      3739     Harvey Keitel  Matthew 'Sport' Higgins
4           mov-2     48933   Cybill Shepherd                    Betsy
...           ...       ...               ...                      ...
345090  mov-14563       NaN    Franco Columbu                      NaN
345091  mov-14563       NaN      Peter Cullen                      NaN
345092  mov-14563       NaN       Henry Kingi                      NaN
345093  mov-14563       NaN  Sven-Ole Thorsen                      NaN
345094  mov-14563       NaN      Jack Verbois                      NaN

[345095 rows x 4 columns]

In [ ]:
df_actor = pd.DataFrame(actor_inner['name'])
data_new_actor = pd.DataFrame(actor_inner[['new_id', 'name']])

df_actor = df_actor.drop_duplicates().reset_index(drop=True)
df_actor['id'] = df_actor.index + 1
df_actor['id'] = df_actor['id'].apply(lambda x: f"act-{x}")
df_actor.to_csv('data_actor.csv', index=False)

In [ ]:
df_actor

                   name          id
0        Robert De Niro       act-1
1          Jodie Foster       act-2
2         Albert Brooks       act-3
3         Harvey Keitel       act-4
4       Cybill Shepherd       act-5
...                 ...         ...
199949    Brigitte Wulf  act-199950
199950    Sonny Landham  act-199951
199951      Shane Black  act-199952
199952      Steve Boyum  act-199953
199953     Jack Verbois  act-199954

[199954 rows x 2 columns]

### **Relationship - Actor & Movie**

In [ ]:
relationship_actor_movie = pd.merge(df_actor, data_new_actor,  on='name', how='inner')
relationship_actor_movie

                  name          id     new_id
0       Robert De Niro       act-1      mov-2
1       Robert De Niro       act-1     mov-37
2       Robert De Niro       act-1     mov-39
3       Robert De Niro       act-1     mov-48
4       Robert De Niro       act-1   mov-2699
...                ...         ...        ...
345090   Brigitte Wulf  act-199950  mov-14562
345091   Sonny Landham  act-199951  mov-14563
345092     Shane Black  act-199952  mov-14563
345093     Steve Boyum  act-199953  mov-14563
345094    Jack Verbois  act-199954  mov-14563

[345095 rows x 3 columns]

In [ ]:
relationship_actor_movie = relationship_actor_movie.drop(columns=['name'])
relationship_actor_movie = relationship_actor_movie.drop_duplicates().reset_index(drop=True)

In [ ]:
relationship_actor_movie.to_csv('relationship_movie_actor.csv', index=False)

In [ ]:
relationship_actor_movie

                id     new_id
0            act-1      mov-2
1            act-1     mov-37
2            act-1     mov-39
3            act-1     mov-48
4            act-1   mov-2699
...            ...        ...
344407  act-199950  mov-14562
344408  act-199951  mov-14563
344409  act-199952  mov-14563
344410  act-199953  mov-14563
344411  act-199954  mov-14563

[344412 rows x 2 columns]

## **Director**

In [ ]:
dir_inner = pd.merge(df_movie, data_dir, on='id', how='inner')
dir_inner.drop('id', axis='columns', inplace=True)

In [ ]:
dir_inner

          new_id person_id             name
0          mov-2      3308  Martin Scorsese
1          mov-3     17727     John Boorman
2          mov-4     11475      Terry Jones
3          mov-4     11473    Terry Gilliam
4          mov-5      1063   Robert Aldrich
...          ...       ...              ...
11918  mov-14560       NaN       Jun Fukuda
11919  mov-14560       NaN   Kengo Furusawa
11920  mov-14561       NaN        Matt Codd
11921  mov-14562       NaN    Robert Altman
11922  mov-14563       NaN   John McTiernan

[11923 rows x 3 columns]

In [ ]:
df_dir = pd.DataFrame(dir_inner['name'])
data_new_dir = pd.DataFrame(dir_inner[['new_id', 'name']])

df_dir = df_dir.drop_duplicates().reset_index(drop=True)
df_dir['id'] = df_dir.index + 1
df_dir['id'] = df_dir['id'].apply(lambda x: f"dir-{x}")
df_dir.to_csv('data_director.csv', index=False)

In [ ]:
df_dir

                 name        id
0     Martin Scorsese     dir-1
1        John Boorman     dir-2
2         Terry Jones     dir-3
3       Terry Gilliam     dir-4
4      Robert Aldrich     dir-5
...               ...       ...
8274      Wayne Groom  dir-8275
8275      Robert Hall  dir-8276
8276       Ed Solomon  dir-8277
8277   Kengo Furusawa  dir-8278
8278        Matt Codd  dir-8279

[8279 rows x 2 columns]

### **Relationship - Director & Movie**

In [ ]:
relationship_director_movie = pd.merge(df_dir, data_new_dir,  on='name', how='inner')
relationship_director_movie = relationship_director_movie.drop(columns=['name'])
relationship_director_movie.to_csv('relationship_director_movie.csv', index=False)

In [ ]:
relationship_director_movie

             id     new_id
0         dir-1      mov-2
1         dir-1   mov-8752
2         dir-1   mov-9442
3         dir-1  mov-10275
4         dir-1  mov-12023
...         ...        ...
11918  dir-8275  mov-14550
11919  dir-8276  mov-14556
11920  dir-8277  mov-14557
11921  dir-8278  mov-14560
11922  dir-8279  mov-14561

[11923 rows x 2 columns]

### **Relationship - Director & Actor**

In [ ]:
relationship_director_actor = pd.merge(dir_inner, actor_inner,  on=['name', 'new_id'], how='inner') # หาคนที่รับบททั้ง act และ dir
relationship_director_actor.drop(columns=['character', 'person_id_x', 'person_id_y'])
relationship_director_actor1 = pd.merge(df_dir, relationship_director_actor, on='name')
relationship_director_actor2 = pd.merge(df_actor, relationship_director_actor1, on='name')
relationship_director_actor2 = relationship_director_actor2.rename(columns={'id_x': 'id_act', 'id_y': 'id_dir'})
relationship_director_actor2 = relationship_director_actor2.drop(columns=['new_id', 'person_id_x', 'person_id_y', 'name', 'character'])
relationship_director_actor2 = relationship_director_actor2.drop_duplicates().reset_index(drop=True)
relationship_director_actor2

          id_act    id_dir
0         act-10     dir-1
1         act-38  dir-4470
2         act-61   dir-450
3         act-62     dir-4
4         act-63     dir-3
...          ...       ...
1101  act-197475  dir-8228
1102  act-198181  dir-8240
1103  act-199144  dir-8265
1104  act-199274  dir-8268
1105  act-199689  dir-8274

[1106 rows x 2 columns]

In [ ]:
relationship_director_actor2.to_csv('relationship_director_actor.csv', index=False)

## **Character**

In [ ]:
data_character = pd.DataFrame(actor_inner[['new_id', 'name', 'character']]).dropna()

In [ ]:
data_character

         new_id              name                character
0         mov-2    Robert De Niro            Travis Bickle
1         mov-2      Jodie Foster            Iris Steensma
2         mov-2     Albert Brooks                      Tom
3         mov-2     Harvey Keitel  Matthew 'Sport' Higgins
4         mov-2   Cybill Shepherd                    Betsy
...         ...               ...                      ...
78991  mov-6144  Deyemi Okanlawon           Michael Idehen
78992  mov-6144   Ini Dima-Okojie                     Mimi
78993  mov-6144    Chigul Omeruah           Madam Echejile
78994  mov-6144           Seyilaw                     Fred
78995  mov-6144        Toni Tones                Stephanie

[73885 rows x 3 columns]

In [ ]:
id_character = []
movie_actor = []
movie_character = []

for i in range(len(data_character)):
    character = data_character['character'].iloc[i]
    if character.find('/') > -1:
        character = character.split("/")
    else:
        character = [character]

    for j in character:
        id_character.append(data_character['new_id'].iloc[i])
        movie_actor.append(data_character['name'].iloc[i])
        j = j
        movie_character.append(j)

df_character = pd.DataFrame({"new_id": id_character, "name": movie_actor,"character":movie_character})
df_character['character'] = df_character['character'].str.strip()
df_character = df_character.drop_duplicates().reset_index(drop=True)
df_character['id'] = df_character.index + 1
df_character['id'] = df_character['id'].apply(lambda x: f"cha-{x}")

In [ ]:
#file character
df_character1 = df_character.drop(columns=['new_id','name']).drop_duplicates().reset_index(drop=True)
df_character1  = df_character1.drop_duplicates().reset_index(drop=True)
df_character1.to_csv('data_character.csv', index=False)

In [ ]:
# character&movie
df_character2movie = df_character.drop(columns=['character', 'name'])
df_character2movie = df_character2movie.drop_duplicates().reset_index(drop=True)
df_character2movie.to_csv('relationship_character_movie.csv', index=False)

In [ ]:
df_character2movie

         new_id         id
0         mov-2      cha-1
1         mov-2      cha-2
2         mov-2      cha-3
3         mov-2      cha-4
4         mov-2      cha-5
...         ...        ...
75798  mov-6144  cha-75799
75799  mov-6144  cha-75800
75800  mov-6144  cha-75801
75801  mov-6144  cha-75802
75802  mov-6144  cha-75803

[75803 rows x 2 columns]

In [ ]:
df_character1

                     character         id
0                Travis Bickle      cha-1
1                Iris Steensma      cha-2
2                          Tom      cha-3
3      Matthew 'Sport' Higgins      cha-4
4                        Betsy      cha-5
...                        ...        ...
75798           Michael Idehen  cha-75799
75799                     Mimi  cha-75800
75800           Madam Echejile  cha-75801
75801                     Fred  cha-75802
75802                Stephanie  cha-75803

[75803 rows x 2 columns]

### **Relationship - Character & Movie**

In [ ]:
df_character2movie = df_character2movie.drop_duplicates().reset_index(drop=True)
df_character2movie

         new_id         id
0         mov-2      cha-1
1         mov-2      cha-2
2         mov-2      cha-3
3         mov-2      cha-4
4         mov-2      cha-5
...         ...        ...
75798  mov-6144  cha-75799
75799  mov-6144  cha-75800
75800  mov-6144  cha-75801
75801  mov-6144  cha-75802
75802  mov-6144  cha-75803

[75803 rows x 2 columns]

In [ ]:
df_character2movie.to_csv('relationship_character_movie.csv', index=False)

### **Relationship - Character & Actor**

In [ ]:
df_character_actor = df_character.drop(columns=['character', 'new_id'])

In [ ]:
df_character_actor

                   name         id
0        Robert De Niro      cha-1
1          Jodie Foster      cha-2
2         Albert Brooks      cha-3
3         Harvey Keitel      cha-4
4       Cybill Shepherd      cha-5
...                 ...        ...
75798  Deyemi Okanlawon  cha-75799
75799   Ini Dima-Okojie  cha-75800
75800    Chigul Omeruah  cha-75801
75801           Seyilaw  cha-75802
75802        Toni Tones  cha-75803

[75803 rows x 2 columns]

In [ ]:
relationship_character_actor = pd.merge(df_actor, df_character_actor,  on='name', how='inner')
relationship_character_actor = relationship_character_actor.rename(columns={'id_x': 'id_act', 'id_y': 'id_char'})
relationship_character_actor = relationship_character_actor.drop(columns=['name']).drop_duplicates().reset_index(drop=True)
relationship_character_actor.to_csv('relationship_character_actor.csv', index=False)

In [ ]:
relationship_character_actor

          id_act    id_char
0          act-1      cha-1
1          act-1    cha-551
2          act-1    cha-726
3          act-1   cha-1010
4          act-1  cha-38386
...          ...        ...
75798  act-55632  cha-75785
75799  act-55639  cha-75787
75800  act-55643  cha-75793
75801  act-55644  cha-75796
75802  act-55645  cha-75801

[75803 rows x 2 columns]

In [ ]:
pd.read_csv("/content/node_user.csv")

,user_id,name,email,phone number
0,user-1,Jacqueline Gonzalez,jamiemunoz@example.com,(815)448-7940x224
1,user-2,Katherine Beltran,jmunoz@example.net,606-374-3708x96800
2,user-3,Samantha Kent,grahamandre@example.com,677-391-3132x873
3,user-4,Renee Montgomery,sanderslaura@example.net,580.693.4656
4,user-5,Erin May,wheelereric@example.org,392.511.6381x9655
...,...,...,...,...
143453,user-143454,Julia Gilmore,grant95@example.com,001-312-734-6427
143454,user-143455,Brian Hudson,patrick70@example.com,530.829.4214x0516
143455,user-143456,Maria Watkins,garywright@example.org,839.611.2497
143456,user-143457,Kathryn Murphy,ejones@example.net,+1-780-850-5627
143457,user-143458,Julie Cruz,colleenjones@example.net,710.656.9714

In [ ]:
pd.read_csv("/content/relationship_movie_user.csv")

             user_id  user_rating     ent_id
0             user-1            3    mov-282
1             user-1            2   mov-6232
2             user-1            3  mov-10529
3             user-1            3   mov-6503
4             user-1            3   mov-6529
...              ...          ...        ...
3468254  user-143458            5   mov-9846
3468255  user-143458            5   mov-5916
3468256  user-143458            3   mov-2090
3468257  user-143458            4  mov-13483
3468258  user-143458            4    mov-254

[3468259 rows x 3 columns]